ratatui/ratatui

README.md
> Upstream: [#683](https://github.com/fdehau/tui-rs/pull/683)
Add [ruscode](https://github.com/MissterHao/ruscode) to list of projects using `tui-rs`.
This crate had already published to [crates.io](https://crates.io/crates/ruscode).
=> docs: Add ruscode to list of apps using tui-rs

src/widgets/paragraph.rs
> Upstream: [#643](https://github.com/fdehau/tui-rs/pull/643)
Fix #642
This PR fixes the out-of-bounds crash on rendering `Paragraph` when zero-width character is at end of line. The fix ignores zero-width symbol on rendering `Paragraph`. Regression test case is added as well.
I checked all unit tests passed. And I checked `paragraph` example manually.
=> fix: Ignore zero-width symbol on rendering `Paragraph`

examples/user_input.rs
> Upstream: [#690](https://github.com/fdehau/tui-rs/pull/690)
In the `user_input` example, it read input when key was released which is not expected.
=> Update example: Read input only when key was pressed

Cargo.toml
#51 bumped MSRV, but `rust-version` field of Cargo.toml is still 1.56.1.
Since this only changes the field in Cargo.toml, I checked only `cargo clippy`
=> chore: update `rust-version` to 1.59 in Cargo.toml

.github/workflows/ci.yml
Currently CI reports 3 kinds of deprecation warnings:
- Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: hecrj/setup-rust-action@967aec96c6a27a0ce15c1dac3aaba332d60565e2, actions/cache@v2.
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
- The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
This PR fixes all the warnings.
I checked all warnings are no longer reported on my forked repository: https://github.com/rhysd/tui-rs-revival/actions/runs/4191656530
=> fix(ci): fix deprecation warnings on CI

src/widgets/list.rs
> Upstream: [#530](https://github.com/fdehau/tui-rs/pull/530)
Added a convenience function to get the width of a ListItem
=> feat(widget): add `width()` to ListItem

src/widgets/table.rs
> Upstream: [#481](https://github.com/fdehau/tui-rs/pull/481)
Add simple getter method to `TableState` that returns a copy of its `offset` field.
My motivating case is a program that allows scrolling a `Table` and an adjacent (related) `Paragraph` at the same time
I don't know that any testing is useful here since it only exposes an existing piece of data.
=> feat(widget): add `offset()` to `TableState`

CONTRIBUTING.md
This PR updates the CONTRIBUTING.md in order to specify when the use of unsafe is waranted, as discussed during [this](https://github.com/tui-rs-revival/tui-rs-revival/discussions/63) meeting.
=> docs(contributing): specify the use of unsafe for optimization

src/text.rs, tests/widgets_list.rs
> Upstream: [#688](https://github.com/fdehau/tui-rs/pull/688)
Fixes issue [#680](https://github.com/fdehau/tui-rs/issues/680#issue-1462518032). Handles the case where a list item is created with an empty string, which is not split by the `lines` iterator.
New test can be ran with `cargo test`
=> fix(widget)!: List should not ignore empty string items

.github/workflows/ci.yml, committed.toml
See: https://github.com/crate-ci/committed
Configuration options: https://github.com/crate-ci/committed/blob/master/docs/reference.md
Closes #50
=> chore: Integrate `committed` for checking conventional commits

.github/workflows/ci.yml
This PR fixes the following build error:
```
error: failed to compile `cargo-make v0.35.16`, intermediate artifacts can be found at `/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cargo-installa5ntdq`
Caused by:
package `base64ct v1.6.0` cannot be built because it requires rustc 1.60 or newer, while the currently active rustc version is 1.59.0
```
=> fix(ci): Bump Rust version to 1.63.0

Cargo.toml, src/buffer.rs
Enable more backends to be built into the default docs than just termion. These were the only backends that built in a representative environment of docs.rs. Options come from https://docs.rs/about#metadata
=> docs: update to build more backends

.github/workflows/ci.yml
Fixes #84
This PR offers two changes:
- 6d7de6e: Install official pre-built `cargo-make` binary instead of building it from source. This change also has the benefit that we no longer need to take care about cache state of built `cargo-make` binary.
- 3474078: Change Rust version tested on CI from 1.63.0 to 1.59.0
I tested these changes on my forked repository and confirmed all jobs passed: https://github.com/rhysd/tui-rs-revival/actions/runs/4360282621/jobs/7623022109
=> fix(ci): Test MSRV compatibility on CI

src/layout.rs
> Upstream: [#647](https://github.com/fdehau/tui-rs/pull/647)
These added weak constraints prevent zero width/height widgets when combining Min(v)/Max(v) together in a chunk.
The UI will now reflow correctly when (re)sizing, gracefully preserving Max(v) constraints as much as possible.
This fixes the root cause of the issues identified in:
https://github.com/fdehau/tui-rs/issues/39
https://github.com/fdehau/tui-rs/issues/420
(amongst probably similar reports).
Combine Min(v) and Max(v) layout constraints in a chunk.
```
...
let chunks = layout::Layout::default()
.direction(layout::Direction::Horizontal)
.constraints([Constraint::Min(50), Constraint::Max(25)])
.split(frame.size());
...
```
Use any other combination, including Percentage/Ratio/Length with Min/Max.
Resize the window …
=> Fix: cassowary/layouts: add extra constraints for fixing Min(v)/Max(v) combination.

src/layout.rs, src/widgets/table.rs
https://github.com/tui-rs-revival/tui-rs-revival/pull/22#issuecomment-1427143924 introduced the idea to return `&'static [Rect]` on `Layout::split` using unsafe, but we can use a safe abstraction here instead with `Rc`.
Using the benchmark introduced in #22, I get these results (master/this respectively)
```
test layout::tests::bench_vertical_split_by_height ... bench: 129 ns/iter (+/- 6)
test layout::tests::bench_vertical_split_by_height ... bench: 100 ns/iter (+/- 3)
```
=> better safe shared layout cache

tests/widgets_block.rs
Fix tests for title_on_bottom, previously these had incorrect expected values that didn't line up with expected behaviour or the tests from widgets_block_title_alignment.
=> Fix tests for title_on_bottom

CHANGELOG.md, CONTRIBUTING.md, src/widgets/canvas/mod.rs, src/widgets/list.rs, src/widgets/reflow.rs, src/widgets/table.rs, tests/terminal.rs, tests/widgets_chart.rs
Found via `typos --format brief`
=> docs: fix typos

src/widgets/canvas/mod.rs
> Upstream: [#666](https://github.com/fdehau/tui-rs/pull/666)
There is no description in docs for `Canvas::x_bounds` and `Canvas::y_bounds`, but there is a [question](https://github.com/fdehau/tui-rs/issues/286) about that with response of the author. So this PR puts this response as documentation for the methods with some small corrections and formatting.
This PR does not add any code, but all code fragments in documentation are valid & buildable.
=> docs(canvas): add documentation for x_bounds, y_bounds

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, examples/panic.rs, examples/user_input.rs, src/lib.rs, src/text.rs, src/widgets/clear.rs, src/widgets/mod.rs
There were a few remaining references in the code docs etc. to tui rather than ratatui. This fixes those references.
E.g. see https://docs.rs/ratatui/0.20.0/ratatui/index.html
=> docs: fixup remaining tui references

src/style.rs
This allows writing:
```rust
const WHITE: Style = Style::new().fg(Color::White);
```
outside of a function. I can't mark `Style::default()` as `const` because it's from a trait.
=> refactor(style): Mark some Style fns const so they can be defined globally

examples/user_input.rs
> Upstream: [#631](https://github.com/fdehau/tui-rs/pull/631)
I found `vec![]` is redundant in `user_input` example. This PR removes it.
I ran `cargo run --example user_input` and tried to change the edit mode, edit the input, and add some lines to messages pane. It worked fine.
=> refactor(example): remove redundant `vec![]` in `user_input` example

examples/demo/crossterm.rs, examples/list.rs, examples/panic.rs, examples/popup.rs, examples/table.rs, examples/tabs.rs
Hi I saw the `user_input` example was already updated to work on windows but I just did the rest of them that use input other than quit.
Also added a hack in panic.rs because on windows/powershell a release event is sent from when you originally press enter to `cargo run`. No more double presses now either.
Fix https://github.com/tui-rs-revival/ratatui/issues/120
Edit: I just looked at the conventional commit thing and it's just a fix, you can merge this now
=> fix(examples): update input in examples to only use press events

Cargo.toml, examples/canvas.rs, src/symbols.rs, src/widgets/canvas/mod.rs
Fixes https://github.com/tui-rs-revival/ratatui/issues/82
When drawing a vertical line on a canvas, using `Marker::Block` would
draw a gap in between each line. This is because the default block
character was a half bar. This changes the default block character to a
full block, and adds a new marker type `Marker::Bar` to replace the
current `Marker::Block`.
BREAKING CHANGE: `Marker::Block` now uses a full block character, and
`Marker::Bar` is the new half block character.
- Adds tests for each `Marker` in the canvas widget.
- Adds marker to the canvas example to show the difference between
the marker types.
=> fix(canvas)!: use full block for Marker::Block

APPS.md
Recently updated to this fork, thanks!
- Fix link to top of README instead of the middle
=> docs(apps): ix rsadsb/adsb_deku radar link

src/lib.rs
Include a thread to handle events so that the pty's buffer doesn't fill up with events from during the program runtime and then get read by the shell and echoed on the prompt.
=> fix(142): cleanup doc example

Cargo.toml, Makefile.toml, examples/calendar.rs, src/lib.rs, src/widgets/calendar.rs, src/widgets/mod.rs, tests/widgets_calendar.rs
A calendar widget that with some display options and styling for individual dates.
This widget displays the month provided to it in the constructor. (see docs and the example for more info).
One thing to note: This pulls in a new dependency, the [time](https://crates.io/crates/time) crate. Since this adds a dependency, it might be worth putting the widget behind a feature flag - I'm happy to do so if that's desired.
=> feat(calendar): add calendar widget

examples/paragraph.rs
While looking at #33 I opened the paragraph example and almost lost my eyesight with the white background haha. So anyways this PR brings minor tweaks aiming to make the example easier on the eyes, as well as a couple minor changes.
**Changes :**
- Background color not set anymore
- Text foreground color changed to gray (seemed like the most sensible option that would suit both light and dark theme users)
- Moved scroll example to last chunk
- Reworked block names
=> refactor(examples): refactor paragraph example

cliff.toml, committed.toml
This is the same list as https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional\#rules
I find myself often reaching for ci: and build: and realizing that they aren't configured in this repo, and having to rewrite to chore: to make the linter happy.
=> ci: add ci, build, and revert to allowed commit types

src/backend/test.rs
Allow a way to expose the buffer of the `TestBackend`, to easier support different testing methodologies.
=> feat(test): expose test buffer

src/widgets/list.rs, tests/widgets_list.rs
> Upstream: [#609](https://github.com/fdehau/tui-rs/pull/609)
close #536 
I added the methods for List.
A structure with the name "list" can be length-checked in many libraries, so I added the methods in this library too.
I added the tests.
Thank you in advance.
=> feat(list): add len() to List

src/buffer.rs, src/widgets/sparkline.rs
This makes it easier to write unit tests with fast feedback against buffers. The implementation is copied from TestBackend (with some refactoring). Also adds a unit test for buffer_set_string_multi_width_overwrite which was missing from the buffer tests
Output (from some intentionally failing tests):
```
failures:
---- buffer::tests::buffer_set_string stdout ----
thread 'buffer::tests::buffer_set_string' panicked at 'buffer contents not equal
expected:
"baa  "
actual:
"aaa  "
diff:
0: at (0, 0)
expected: Cell { symbol: "b", fg: Reset, bg: Reset, modifier: (empty) }
actual:   Cell { symbol: "a", fg: Reset, bg: Reset, modifier: (empty) }', src/buffer.rs:604:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- buffer::tests::buffer_set_string_zero_width stdout …
```
=> test(buffer): add `assert_buffer_eq!` and Debug implementation

src/backend/test.rs, src/buffer.rs, src/terminal.rs, src/widgets/barchart.rs, src/widgets/chart.rs, src/widgets/gauge.rs
Simply makes the suggested changes from clippy for inline variables in string templates.
Can be closed if undesired but maybe worth to be discussed.
=> style(format): use variable inlining in format! macros

src/widgets/list.rs
- also adds builder methods on list state to make it easy to construct
a list state with selected and offset as a one-liner. Uses `with_` as
the prefix for these methods as the selected method currently acts as
a getter rather than a builder.
- cargo tarpaulin suggests only two lines are not covered (the two
match patterns of the self.start_corner match 223 and 227).
the body of these lines is covered, so this is probably 100% 
Contextually, this PR is about putting in place some tests for the list widget so that we can easily refactor some of the complexity of the methods to be easy to read and maintain.
Note: this sits on #161 which is not yet merged, so ignore the changes to buffer / sparkline for now.
=> test(list): add characterization tests for list

examples/paragraph.rs, examples/user_input.rs, src/text.rs, src/widgets/mod.rs
Adds a new type Masked that can mask data with a mask character, and can be used anywhere we expect Cow<'a, str> or Text<'a>. E.g. Paragraph, ListItem, Table Cells etc.
BREAKING CHANGE:
Because Masked implements From for Text<'a>, code that binds Into<Text<'a>> without type annotations may no longer compile (e.g. `Paragraph::new("".as_ref())`)
To fix this, annotate or call to_string() / to_owned() / as_str()
This is an alternative to https://github.com/tui-rs-revival/ratatui/pull/32
[![asciicast](https://asciinema.org/a/ftwC1T9gyvW6VA0WVRokF11I9.svg)](https://asciinema.org/a/ftwC1T9gyvW6VA0WVRokF11I9)
=> feat(text)!: add `Masked` to display secure data

.github/workflows/ci.yml, Cargo.toml, README.md, src/backend/mod.rs, src/terminal.rs, src/widgets/block.rs, src/widgets/chart.rs
The latest version of the time crate requires Rust 1.65.0
```
cargo +1.64.0-x86_64-apple-darwin test --no-default-features \
--features serde,crossterm,all-widgets --lib --tests --examples
error: package `time v0.3.21` cannot be built because it requires rustc
1.65.0 or newer, while the currently active rustc version is 1.64.0
```
The calendar widget added a dependency on time v0.3.11 (though a quick check suggests that 0.3.9 compiles, I'm unsure if the later bug fixes are notable for ratatui. Regardless, the dependency requirement is satisfied by any version later than 0.3.11. Later versions require rust 1.65.0, so our MSRV is 1.65.0.
I don't think there's an obvious way to only specify a MSRV for a specific set of features (i.e. 1.59 if you're not using termwiz/calendar), though perhaps …
=> build: bump MSRV to 1.65.0

APPS.md
Linked to issue #179 
* Adding categories
* New applications from the original tui-rs repo
=> style(apps): update the style of application list

examples/barchart.rs, examples/block.rs, examples/canvas.rs, examples/chart.rs, examples/custom_widget.rs, examples/demo/crossterm.rs, examples/demo/termion.rs, examples/demo/termwiz.rs, examples/demo/ui.rs, examples/gauge.rs, examples/inline.rs, examples/layout.rs, examples/list.rs, examples/paragraph.rs, examples/popup.rs, examples/sparkline.rs, examples/table.rs, examples/tabs.rs, examples/user_input.rs, src/backend/termion.rs, src/backend/test.rs, src/buffer.rs, src/style.rs
Applied auto-clippy fix and some manual minor cleanup:
```
cargo clippy --all-features --benches --examples --tests --workspace --fix -- -A clippy::all -W clippy::uninlined_format_args
```
=> chore: inline format args

Cargo.toml
see https://doc.rust-lang.org/nightly/rustdoc/scraped-examples.html
I noticed this in another library and thought it was a pretty neat idea. We have a bunch of examples that we can use for this.
Here's how it shows up:
To test this locally, use:
```
rustup toolchain add nightly
cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples --all-features --open
```
=> docs: scrape example code from examples/*

src/text/line.rs, src/text/spans.rs, src/widgets/paragraph.rs, src/widgets/reflow.rs, tests/widgets_paragraph.rs
For a small project of mine I needed to support different `Alignment`s (`Center`, `Left` and `Right`) not only on whole paragraphs but also on `Line`s within these paragraphs. 
So I implemented that in my local copy of the project and thought, why not contribute that effort to the original project. So here is my PR:
I added a new field to the `Line` struct containing information about the `Alignment`. By default, if no alignment is specified, the one from the rendering `Paragraph` will be used. 
I had to rewrite the `LineComposer`s to operate on a line-by-line level and not symbol-by-symbol, since the alignment information is bound to the line the `Line` struct represents.  
Furthermore, the `Line`'s `spans` have been made private so future additions will not cause a breaking change. …
=> feat(paragraph): allow Lines to be individually aligned

src/widgets/reflow.rs
This was accidentally left in the previous commit and causes all the
demos to fail.
=> fix(reflow): remove debug macro call

.github/workflows/ci.yml
This runs the coverage and uploads the output to
https://app.codecov.io/gh/tui-rs-revival/ratatui/
~Requires the codecov.io repo secret to be set first.~
=> ci: add code coverage action

Cargo.toml, README.md, examples/hello_world.rs
- Reformat summary info
- Add badges for dependencies, discord, license
- point existing badges to shields.io
- add Table of Contents
- tweaked installation instructions to show instructions for new and
existing crates
- moved fork status lower
- chop lines generally to 100 limit
- add a quickstart based on a simplified hello_world example
- added / updated some internal links to point locally
- removed some details to simplify the readme (e.g. tick-rate)
- reordered widgets and pointed these at the widget docs
- adds a hello_world example that has just the absolute basic code
necessary to run a ratatui app. This includes some comments that help
guide the user towards other approaches and considerations for a real
world app.
Direct link to view README:
- …
=> docs: update README.md and add hello_world example

Cargo.toml, src/buffer.rs, src/style.rs, src/widgets/mod.rs
build(deps)!: upgrade bitflags to 2.3
BREAKING CHANGE: The serde representation of bitflags has changed. Any
existing serialized types that have Borders or Modifiers will need to be
re-serialized. This is documented in the bitflags changelog.
https://github.com/bitflags/bitflags/blob/main/CHANGELOG.md#200-rc2
=> build(deps)!: upgrade bitflags to 2.3

examples/list.rs, examples/user_input.rs, rustfmt.toml, src/buffer.rs, src/lib.rs, src/terminal.rs, src/text.rs, src/widgets/chart.rs, src/widgets/clear.rs, src/widgets/mod.rs, src/widgets/paragraph.rs, src/widgets/reflow.rs, tests/widgets_paragraph.rs
This is an opinionated default that helps avoid horizontal scrolling.
100 is the most common width on github rust projects and works well for
displaying code on a 16in macbook pro.
=> style(comments): set comment length to wrap at 100 chars

.github/workflows/ci.yml, deny.toml
See https://github.com/EmbarkStudios/cargo-deny
=> chore(ci): integrate cargo-deny for linting dependencies

src/widgets/paragraph.rs, typos.toml
- Adds a new typos.toml
- Prevents ratatui from being marked as a typo of ratatouille
- Changes paragraph tests so that the truncated word is a valid word
=> fix(typos): configure typos linter

src/terminal.rs, tests/terminal.rs
I needed raw access to clearing/swapping the buffers, I think it doesn't hurt to expose this functionality.
=> feat(terminal): expose 'swap_buffers' method

.github/CODEOWNERS, CODEOWNERS
- Fixed the syntax (mind the `*` for giving access to the files)
- Moved CODEOWNERS to .github directory (since it is more relevant there)
=> chore(github): fix the syntax in CODEOWNERS file

README.md, RELEASE.md
The demo GIF was not showing for me so I replaced the link with a GitHub provider.
Also, changed the wording a bit in RELEASE.md
=> chore(demo): update demo gif

examples/gauge.rs
:wave: Hey folks,
Was trialing out the library last night when I noticed that gauge4's label vs percentage complete was a bit off.  Read through the example a bit more closely to understand what the issue was.  Just thought I'd throw this up for posterity.
Cheers,
Chris
=> fix(examples): Correct progress label in gague example

Cargo.toml, benches/paragraph.rs, deny.toml
To run the benchmarks:
cargo bench
And then open the generated `target/criterion/report/index.html` in a
browser.
=> test(benchmarks): add criterion benchmarks for paragraph

deny.toml
This is actually used for terminfo (transitively from termwiz
```
error[rejected]: failed to satisfy license requirements
┌─ terminfo 0.7.5 (registry+https://github.com/rust-lang/crates.io-index):4:12
│
4 │ license = "WTFPL"
│            ^^^^^
│            │
│            license expression retrieved via Cargo.toml `license`
│            rejected: not explicitly allowed
│
= terminfo v0.7.5
└── termwiz v0.20.0
└── ratatui v0.21.0
advisories ok, bans ok, licenses FAILED, sources ok
```
=> fix: revert removal of WTFPL from deny.toml

src/layout.rs
This function is only currently used in by the chart widget for constraining the width and height of the legend.
=> fix(layout): cap Contstraint::apply to 100% length

Cargo.toml, examples/scrollbar.rs, src/widgets/mod.rs, src/widgets/scrollbar.rs
I've added a simple scrollbar widget.
```
<--▮------->
^  ^   ^   ^
│  │   │   └ end arrow
│  │   └──── track symbol
│  └──────── thumb symbol
└─────────── begin arrow
```
It can be used to add a scrollbar to any `Rect`. 
It can also be customized with different styles and symbols for, the bar, the "scrollwheel" and arrows.
This addresses https://github.com/tui-rs-revival/ratatui/issues/173
A larger discussion is to be had about scrollable widgets in general: https://github.com/tui-rs-revival/ratatui/issues/174
I'm open to feedback on improving this. I've needed a scrollbar for a couple of projects now and figured I'd clean up the code and share it as a `Widget` here. 
_Docstrings were generated using ChatGPT_.
=> feat: add scrollbar widget

README.md
Add [`tui-term`](https://github.com/a-kenji/tui-term/tree/main) to the list of third party libraries. 
Is the capitalization of ratatui correct here?
=> docs(lib): add `tui-term` a pseudoterminal library

examples/block.rs, examples/inline.rs, src/layout.rs, src/title.rs, src/widgets/block.rs, src/widgets/mod.rs, tests/widgets_block.rs
To be able to create TUIs such as that of [btop](https://github.com/tui-rs-revival/ratatui/assets/99157490/2a7cbde2-f943-435b-96ea-07d4ddf94a67), I believe it to be necessary to be able to have multiple titles for a single block. This pull request adds the ability to have multiple titles per block. Each title can have a different alignment thought multiple titles can have the same alignment.
For backwards compatibility sake, I let the old title system and just added a new one that takes precedence over the old one in cases it has been set.
In the new system, you declare your titles in the following ways:
```rust
Block::default()
.title("old system"),
.titles(vec![
Title::default()
.content("Title 1")
.alignment(Alignment::Right),
Title::default()
.content("Title 2") …
```
=> feat(block): support for having more than one title

src/widgets/block.rs, src/widgets/calendar.rs, src/widgets/scrollbar.rs
This PR fixes scrollbar's documentation, which tried to showcase its elements. This requires for the text to be rendered exactly how it was written, which isn't the case for the cargo and other tools. Thus, it requires to be wrapped inside text blocks, which preserves text as is.
Secondly, there were problems with doc paths in calendar's documentation. 
Finally, recently merged changes in `block.rs` were not formatted properly
=> docs: fix scrollbar ascii illustrations and calendar doc paths

src/widgets/mod.rs
This is a continuation of #190, that I noticed while working on the `const` branch.
=> style(widget): use inline format arguments

src/layout.rs, src/style.rs, src/widgets/block.rs
Mark functions of `structs` that suit themselves to be composed with multiple other widgets as const, namely:
- `Block`
- `Layout`
- `Rect`
Continuation of: #115
This allows with some limitations to share blocks, layouts, through many widgets and with some luck also to remove `lazy_static!` from some of those use cases.
=> refactor(const): Mark low level fns const

benches/paragraph.rs
Reduce benchmarks from 60 calls to 18. Now 3 different line counts
(64, 2048, 65535) * 6 different tests (new, render, scroll half / full,
wrap, wrap and scroll)
=> test(paragraph): simplify paragraph benchmarks

src/layout.rs
This lint is slightly more agressive in +nightly than it is in stable.
=> fix(clippy): fix unused_mut lint for layout

examples/block.rs, examples/canvas.rs, examples/chart.rs, examples/list.rs, examples/paragraph.rs, examples/popup.rs, examples/scrollbar.rs, examples/tabs.rs, examples/user_input.rs, src/style.rs, src/style/stylized.rs, src/text.rs, src/widgets/block.rs, src/widgets/paragraph.rs, tests/stylize.rs
fix: #241
This PR adds the ability to use style shorthands to `str`, `Span`, and `Paragraph`.
```rust
assert_eq!(
"hello".red().on_blue().bold(),
styled("hello", Style::default().fg(Color::Red).bg(Color::Blue).add_modifier(Modifier::BOLD))
)
```
=> feat: stylization shorthands

Cargo.toml, bacon.toml, examples/demo/main.rs, src/lib.rs
Before this change, it wasn't possible to build all features and all
targets at the same time, which prevents rust-analyzer from working
for the whole project.
Adds a bacon.toml file to the project, which is used by bacon
https://dystroy.org/bacon/
Configures docs.rs to show the feature flags that are necessary to
make modules / types / functions available.
=> chore(features): enable building with all-features

LICENSE
Updated the @fdehau's copyright to 2016-2022 and added "The Ratatui developers 2023"
This is in compliance with the license conditions (specifically the right to sublicense and the need to include the copyright notice):
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
=> chore(license): add Ratatui developers to license

src/style.rs
This allows the full style to be constructed in a const context.
A const style can be used in the following way:
```
const DEFAULT_MODIFIER: Modifier = Modifier::BOLD.union(Modifier::ITALIC);
const EMPTY: Modifier = Modifier::empty();
const DEFAULT_STYLE: Style = Style::with(DEFAULT_MODIFIER, EMPTY)
.fg(Color::Red).bg(Color::Black);
```
=> feat(style): Add style with fn

examples/barchart.rs, examples/block.rs, examples/calendar.rs, examples/canvas.rs, examples/chart.rs, examples/custom_widget.rs, examples/demo/app.rs, examples/demo/crossterm.rs, examples/demo/termion.rs, examples/demo/termwiz.rs, examples/demo/ui.rs, examples/gauge.rs, examples/hello_world.rs, examples/inline.rs, examples/layout.rs, examples/list.rs, examples/panic.rs, examples/paragraph.rs, examples/popup.rs, examples/scrollbar.rs, examples/sparkline.rs, examples/table.rs, examples/tabs.rs, examples/user_input.rs, src/lib.rs, src/widgets/block.rs
This allows users of the library to easily use ratatui without a huge amount of imports
Review hints:
- The main change is [lib.rs](https://github.com/tui-rs-revival/ratatui/pull/304/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759)
- I'm curious whether the aliasing decisions make sense (BlockTitle, CanvasLine, etc.)
- Are there any types included in the prelude that are too generic and clash with commonly used rust types?
=> feat(prelude): add a prelude

src/text/masked.rs
Fixed tests and completed coverage for `Masked` type.
=> fix(lint): suspicious_double_ref_op is new in 1.71

examples/barchart.rs, src/widgets/barchart/bar.rs, src/widgets/barchart/mod.rs, tests/widgets_barchart.rs
Hello again :smile_cat: 
somehow I missed this feature, while integrating the new code. (In my original PR #288, I had a function pointer, which formats the values. `format: fn(u64) -> String`).
This patch suggests adding a new function `text_value` to the `Bar`, which will override the default text value
```
Bar::default()
.label("Temperature".into())
.value(10)
.text_value("10°C".to_string());
```
Commit message:
for now the value is converted to a string and then printed. in many cases the values are too wide or double values. so it make sense to set a custom value text instead of the default behavior.
this patch suggests to add a method `fn text_value(mut self, text_value: String)` to the Bar, which allows to override the value printed in the bar
=> feat(barchart) set custom text value in the bar

CONTRIBUTING.md, bacon.toml
- Add two jobs to bacon.toml (one for unit tests, one for all tests)
- Remove "run" job as it doesn't work well with bacon due to no stdin
- Document coverage tooling in CONTRIBUTING.md
=> chore(tests): setup coverage monitoring in bacon

examples/barchart.rs, examples/block.rs, examples/calendar.rs, examples/canvas.rs, examples/chart.rs, examples/custom_widget.rs, examples/demo/app.rs, examples/demo/ui.rs, examples/gauge.rs, examples/hello_world.rs, examples/inline.rs, examples/layout.rs, examples/list.rs, examples/panic.rs, examples/paragraph.rs, examples/popup.rs, examples/scrollbar.rs, examples/sparkline.rs, examples/table.rs, examples/tabs.rs, examples/user_input.rs, src/lib.rs, src/prelude.rs, src/style.rs, src/widgets/barchart/bar.rs, src/widgets/barchart/bar_group.rs, src/widgets/barchart/mod.rs
This helps to keep the prelude small and less likely to conflict with
other crates.
- remove widgets module from prelude as the entire module can be just as
easily imported with `use ratatui::widgets::*;`
- move prelude module into its own file
- update examples to import widgets module instead of just prelude
- added several modules to prelude to make it possible to qualify
imports that collide with other types that have similar names
In the [discussion of this on discord](https://discord.com/channels/1070692720437383208/1072879985762762812/1129381084010909756), just the canvas was suggested to be removed, however given that it's fairly easy to import widgets::*, it makes sense to drop the entire module from the prelude.
=> fix(prelude): remove widgets module from prelude

README.md
Changed the URL https://github.com/orhun/rust-tui-template
into https://github.com/rust-tui-revival/rust-tui-template
Finishes https://github.com/tui-rs-revival/ratatui/pull/314#issuecomment-1636992682 for @stappersg due to issues setting up commit signing / maintainer edits.
=> fix(readme): update the link of rust-tui-template

src/title.rs, src/widgets/block.rs, tests/widgets_block.rs
fixes #322
we already have defaults in:
https://github.com/tui-rs-revival/ratatui/blob/446efae185a5bb02a9ab6481542d1dc3024b66a9/src/widgets/block.rs#L151-L152
=> fix(title): remove default alignment and position

.github/workflows/ci.yml, Makefile.toml, src/backend/termwiz.rs
- remove the dependency on the lint job from all other jobs
- implement workflow concurrency
- run jobs which run for each backend in parallel by calling e.g.
cargo make test-termion, instead of cargo make test
- add a coverage task to the makefile
- change "cargo-make check" to check all valid features in parallel
- add clippy-all tasks to enable all features
- tidy up the workflow file
Fixes:
- https://github.com/tui-rs-revival/ratatui/issues/291
- https://github.com/tui-rs-revival/ratatui/issues/194
Second commit simplifies Makefile.toml to use [platform overrides](https://github.com/sagiegurari/cargo-make#usage-platform-override) for windows to avoid termion, and makes the backend choice a parameter for tasks that actually need it (e.g. `cargo make test-backend termion` is now …
=> ci: parallelize CI jobs

src/widgets/scrollbar.rs
I find the title is not really needed for the doc comment.
Alternative:
Rename `tui-rs` to `ratatui` in the title, but I find that this is not needed.
=> docs: improve scrollbar doc comment

Makefile.toml
Enables the all-widgets feature so that the calendar example runs correctly
=> build(examples): fix cargo make run-examples

src/lib.rs
This indicates good (high level) code and is used by tools like cargo-geiger.
Reading #66 it also sounds like a good idea to have this unless someone has a really good explanation to remove this.
Also see https://github.com/tui-rs-revival/ratatui/pull/157#discussion_r1200281899
=> build: forbid unsafe code

src/widgets/barchart/mod.rs
This unlikely to happen, since nobody wants to add an empty group. 
Even if we fix the panic, things will not render correctly. So it is better to just not add them at all.
=> fix(barchart): empty groups causes panic

Cargo.toml
First of all wanted to say that I love ratatui/tui and appreciate the continued maintenance of it :)
I ran into a [CI issue](https://github.com/ndd7xv/heh/actions/runs/5664863950/job/15348805140?pr=75) when trying to release a new version of my [terminal hex editor](https://github.com/ndd7xv/heh) that uses ratatui. The job essentially checks if the minimal versions specified in the `Cargo.toml` are able to compile the rust project. With how this currently works, `-Z minimal-versions` [currently checks transitive dependencies](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#minimal-versions), and I've identified the source of the error to be that the minimum required version of `paste` should actually be `1.0.2` instead of `1.0`.
This isn't really a problem,  considering …
=> fix(cargo): adjust minimum paste version

examples/scrollbar.rs, src/symbols.rs, src/widgets/mod.rs, src/widgets/scrollbar.rs
This makes it consistent with the other symbol sets
BREAKING CHANGE: The symbols are now in the `symbols` module. To update
your code, add an import for `ratatui::symbols::scrollbar::*` (or the
specific symbols you need).
=> fix(scrollbar)!: move symbols and set to symbols module

.github/workflows/ci.yml
Fixes the problem where the code coverage github action cannot upload the coverage results.
=> ci: add coverage token

src/backend/crossterm.rs, src/backend/termion.rs, src/backend/test.rs, src/layout.rs, src/terminal.rs, src/widgets/block.rs, src/widgets/calendar.rs, src/widgets/canvas/mod.rs, src/widgets/gauge.rs, src/widgets/reflow.rs, src/widgets/scrollbar.rs
Implement `Clone & Copy` common traits for most structs in src.
Only implement `Copy` for structs that are simple and trivial to copy.
Reorder the derive fields to be more consistent:
Debug, Default, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash
see: https://github.com/ratatui-org/ratatui/issues/307
=> chore: implement `Clone & Copy` common traits

examples/scrollbar.rs, src/widgets/scrollbar.rs
The track symbol is now optional, simplifying composition with other widgets.
BREAKING_CHANGE: The `track_symbol` needs to be set in the following way now:
```
let scrollbar = Scrollbar::default().track_symbol(Some("-"));
```
This change makes it easier to use the scrollbar in tandem with a block with special block characters. It also makes it possible to render a custom track that is composed out of multiple differing track symbols.
=> feat(scrollbar)!: optional track symbol

src/backend/crossterm.rs, src/backend/mod.rs, src/backend/termion.rs, src/backend/test.rs, src/layout.rs, src/style.rs, src/symbols.rs, src/terminal.rs, src/text/grapheme.rs, src/widgets/barchart/bar.rs, src/widgets/barchart/bar_group.rs, src/widgets/barchart/mod.rs, src/widgets/block.rs, src/widgets/calendar.rs, src/widgets/canvas/circle.rs, src/widgets/canvas/line.rs, src/widgets/canvas/map.rs, src/widgets/canvas/mod.rs, src/widgets/canvas/points.rs, src/widgets/canvas/rectangle.rs, src/widgets/chart.rs, src/widgets/clear.rs, src/widgets/gauge.rs, src/widgets/list.rs, src/widgets/mod.rs, src/widgets/paragraph.rs, src/widgets/scrollbar.rs, src/widgets/sparkline.rs, src/widgets/table.rs, src/widgets/tabs.rs
Also reorder some derive fields to be more consistent:
Debug, Default, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash
see: https://github.com/ratatui-org/ratatui/issues/307
=> chore: implement `Eq & PartialEq` common traits

.github/workflows/ci.yml, Cargo.toml, README.md
This updates the msrv to  `1.67`.
Because an optional dependency of ratatui requires it.
Alternatives: Choose to not bump the versions for optional dependencies, or pin the time version to the latest version that supports `1.65`
=> chore(toolchain)!: bump msrv to 1.67

README.md
Just a small fix in the readme, the version since the last msrv bump was erroneous.
Original PR : #361
=> chore(readme): Corrected the version since msrv is 1.67

.github/workflows/cd.yml, Cargo.toml
As discussed in the [last meeting](https://github.com/ratatui-org/ratatui/discussions/316), this PR updates the release workflow (`cd.yml`) for creating periodic nightly releases.
The version schema is `<version>-alpha.<num>` and `<num>` is increased each time the workflow runs. It is also possible to trigger a nightly release manually via the GitHub interface (see [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow)).
Tested here: https://github.com/orhun/tui-rs-revival/tags
Closes #147
=> feat(release): add automated nightly releases

Cargo.toml, benches/block.rs
I added benchmarks to the `block` widget to uncover eventual performance issues.  
I tried to cover common (creation, render) or expensive (inner area) calculations. I also ran the benchmark with three different common buffer sizes.  
From what I can see it doesn't seem to have any bottleneck here.
What is covered by the benches :
- `Block` creation
- Render with different parameters (empty, titles, borders, padding)
- Computing inner area
- This PR adds benchmarks only for `block`. I think it's a better idea to split the work on benchmarks to add them incrementally.
- I'm not sure the `black_box` is really necessary for the `block` creation bench. Otherwise the compiler advises to put the `new` function reference as parameter (see below). I'm afraid this is less legible and might not …
=> test(block): add benchmarks

src/layout.rs
This PR adds at least some documentation on what each variant does, with examples (and so doc-tests)
fixes #354
=> docs(layout::Constraint): add doc-comments for all variants

Cargo.toml, examples/README.md, examples/colors.rs, examples/colors.tape, examples/modifiers.rs, examples/modifiers.tape, src/style.rs
The intent of these examples is to show the available colors and
modifiers.
- added impl Display for Color
=> docs(examples): Add color and modifiers examples

Cargo.toml, benches/list.rs
I added benchmarks for the `list` widget : 
- Render
- Render half scrolled
Chose 16284 as the highest number of lines so we can see the three tests on the graph.
I tried benchmarking the `new` operation but I think it is not necessary as it only involves copying/moving.
---
Some benchmarks
_Figure 1: Render time relative to number of lines_
_Figure 2: Halfway scrolled render time relative to number of lines_
_Figure 3: Render vs halfway scrolled render_
The number of lines impact the performances (probably because of memory usage?) but where the list is rendered (the `offset`) doesn't seem to.
---
Relates to #137
=> test(list): Added benchmarks

Cargo.toml, benches/sparkline.rs
This PR adds benchmark for the `sparkline` widget testing a basic render with different amounts of data.
The `sparkline` renders only the values that can fit in the buffer width (200 for this test), above that amount, there is almost no difference in the performance.
=> test(sparkline): added benchmark

src/widgets/mod.rs, src/widgets/table.rs, tests/widgets_table.rs
This PR adds a option for `Table` to always allocate the "selection column", regardless of if something is selected, this way there is less "moving around" of the layout.
The default is still `false` (only allocated if something is selected), but it can both be enabled or disabled in a builder function.
Note: also renamed some internal variables to better reflect on what they do / track
=> feat(widgets::table): add option to always allocate the "selection" constraint

Makefile.toml
All the tasks can be listed via `cargo make --list-all-steps`:
```
build - Compile the project
build-examples - Compile project examples
check - Check code for errors and warnings
ci - Run continuous integration tasks [aliases: default]
clippy - Run Clippy for linting
coverage - Generate code coverage report
fmt - Format source code
run-examples - Run project examples
style-check - Check code style
test - Run tests
test-backend - Run backend-specific tests
test-doc - Run documentation tests
test-windows - Run tests on Windows
typos - Run typo checks
```
=> chore(make): add task descriptions to Makefile.toml

.github/workflows/cd.yml
The latest [alpha release job](https://github.com/ratatui-org/ratatui/actions/runs/5838396596) failed due to this.
=> fix(release): set the correct permissions for creating alpha releases

examples/README.md, examples/layout.rs, examples/layout.tape
Shows the way that layout constraints interact visually
I'm not sure if this is "good" as an example for users to get value out of the code, as it isn't super simple code. But it covers a reasonable combination of all constraints. It doesn't cover layout margins, and situations where constraints cause gaps (e.g. when Percentage results in a size < full cell width).
Inspired by the following issues:
- https://github.com/ratatui-org/ratatui/issues/354
- https://github.com/ratatui-org/ratatui/issues/367
- https://github.com/ratatui-org/ratatui/issues/374
- https://github.com/ratatui-org/ratatui/pull/385
=> docs(examples): show layout constraints

src/widgets/list.rs, src/widgets/table.rs, tests/widgets_list.rs
Before this option was available, selecting a item in a list when nothing was selected previously made the row layout change (the same applies to unselecting) by adding the width of the "highlight symbol" in the front of the list, this option allows to configure this behavior.
re #375
TL;DR: the same as #375, but for `widgets::List`
implementing this for list was easier than `Table` because it already had basically everything in-place
=> feat(list): add option to always allocate the "selection" column width

src/widgets/table.rs
Since `Cell` objects already internally contain instances of `Line` and `Line` already has alignment info, we can use this to position a line of text inside a table cell.
This PR makes the table render function follow the text line alignment and resolves #257
=> feat(table): add support for line alignment in the table widget

README.md, RELEASE.md, examples/README.md, examples/demo.tape, src/lib.rs
The bug that prevented braille rendering is fixed, so switch to VHS for
rendering the demo gif
=> chore: use vhs to create demo.gif

codecov.yml
a yaml file cannot contain tabs outside of strings
was added by #373, i dont know why codecov is in a state of "working" or "not working"
=> chore(codecov): fix yaml syntax

Cargo.toml, src/backend/test.rs, src/layout.rs
This is mainly a reduction in density of the code with a goal of
improving mainatainability so that the algorithm is clear.
(Testing - the layout example renders the same)
=> refactor(layout): simplify and doc split()

src/text/span.rs
This PR adds some tests for `widget::Span`, also adding a `From<&String>` implementation
what should be done about the doc-tests, should they stay in-place or should they be refactored?
=> Span tests

examples/colors.rs, src/layout.rs, tests/widgets_table.rs
Fixes https://github.com/ratatui-org/ratatui/issues/367
~~Note: this builds on #405, so it has the commits for that here.~~ Look at just the last commit in this PR to understand it. The relevant change is just the addition of `round()`:
https://github.com/ratatui-org/ratatui/blob/2364d9b3098024459c4360900228e2b3e79fb848/src/layout.rs#L453-L454
Note each of the test changes is a subjectively better rendering choice. I'm not 100% sure if there are some tests that would make it easier to see this change's effect rather than those that are already changed.
I updated the colors example to use a ratio instead of a percentage as this now renders correctly without gaps.
Before (using `constraint: vec![Ratio(1,8); 8]` )
After:
=> Fix layout gap

.github/workflows/ci.yml
For the sake of consistency with:
https://github.com/ratatui-org/ratatui/blob/d2429bc3e44a34197511192dbd215dd32fdf2d9c/.github/workflows/cd.yml#L1
=> chore(ci): update the name of the CI workflow

.github/workflows/cd.yml
There are 2 tags (`alpha.0`, `alpha.1`) associated with the same commit and the previous `git` command was failing to retrieve the _latest_ tag.
This PR fixes https://github.com/ratatui-org/ratatui/actions/runs/5908461923/job/16027928791
=> fix(release): fix the last tag retrieval for alpha releases

src/widgets/paragraph.rs
This PR adds some rustdoc documentation and type helper to clarify what the values in `Paragraph`'s `scroll` are
the `type`s are useful because they are shown in rust-analyzer (though i can remove it if wanted)
Why?
because before it was not clear in what order the values should be
=> style(paragraph): add documentation for "scroll"'s "offset"

src/layout.rs, src/widgets/table.rs
The merge of the table unit tests after the rounding layout fix was not
rebased correctly, this addresses the broken tests, makes them more
concise while adding comments to help clarify that the rounding behavior
is working as expected.
Fixes the issue mentioned in https://github.com/ratatui-org/ratatui/pull/395#discussion_r1299220841
=> fix(table): fix unit tests broken due to rounding

Cargo.toml, src/layout.rs, src/widgets/table.rs
This PR introduces a `SegmentSize` `enum` that will allow adding the following constraints optionally:
```rust
for i in 0..elements.len() {
for j in (i + 1)..elements.len() {
solver.add_constraint(elements[j].size() | EQ(WEAK) | (elements[i].size()))?;
}
}
```
This makes chunks similar in size to each other if other constraints are satisfied.
This PR also changes the implementation of `Max` and `Min` by adding a `MEDIUM` equality constraint instead of a `WEAK` equality constraint. 
```diff
Constraint::Max(m) => {
solver.add_constraints(&[                           
element.size() | LE(STRONG) | f64::from(m),     
-            element.size() | EQ(WEAK) | f64::from(m),
+            element.size() | EQ(MEDIUM) | f64::from(m),
])?;                                                
} …
```
=> Add weak constraints to make rects closer to each other in size 

Cargo.toml, src/lib.rs
This PR extends the `lib.rs` `Features` section to list all the features that are available (publicly)
also changes `time` to `dep:time` for `widget-calendar` to be consistent with other features (like `serde`)
=> Document all features in one place

Cargo.toml, src/backend/mod.rs, src/layout.rs, src/symbols.rs, src/terminal.rs, src/title.rs, src/widgets/block.rs, src/widgets/canvas/map.rs, src/widgets/chart.rs, src/widgets/scrollbar.rs, src/widgets/sparkline.rs, src/widgets/table.rs
Use [strum](https://docs.rs/strum/latest/strum/) for most of these, with a couple of manual implementations, and
related tests
Fixes #307
note: this is mainly the enums, the structs tend not to have obvious display representations.
ping @TieWay59 (due to previous work on trait impls)
=> chore(traits): add Display and FromStr traits

Cargo.toml, src/lib.rs
Utilize [document-features](https://github.com/slint-ui/document-features) crate to extract the feature documentation from `Cargo.toml`
before / after:
One thing to note, we can possibly make it an optional dependency: https://github.com/slint-ui/document-features/pull/8
Let me know what you think 🐻
=> docs(lib): extract feature documentation from Cargo.toml

cliff.toml
With this change, all the changes from alpha releases will be incorporated in the stable release changelog. Also, we will have all the entries in the latest alpha release instead of separating the changelog. For example, `alpha.2` changelog will contain changes from `alpha.1` and `alpha.0`. If we do not want to do that, I can tweak the release workflow accordingly.
=> chore(changelog): ignore alpha tags

README.md
In my opinion, this change in the docs will be a better user experience for most people, for the following reasons:
- With breaking changes users can't just do this to upgrade from `tui`:
```toml
[dependencies]
tui = { package = "ratatui", version = "0.23.0", features = ["all-widgets"]} # will cause errors because of breaking changes going forward
```
At best, we should only recommend this:
```toml
[dependencies]
tui = { package = "ratatui", version = "0.19.0", features = ["all-widgets"]}
```
But I think we should save that for the docs or the ratatui-book; and the README should have one obvious way for newcomers to add the `ratatui` crate to their project.
- Third party crates linked have migrated from `tui` to `ratatui`.
- If users use `ratatui` explicitly in the code, it'll will allow …
=> Update README to use ratatui 

src/title.rs
This adds documentation for `Title` and `Position`.
Relates to #386.
=> docs(title): add documentation to title

src/backend/crossterm.rs, src/backend/mod.rs, src/backend/termion.rs, src/backend/termwiz.rs, src/backend/test.rs, src/layout.rs
Depends on https://github.com/crossterm-rs/crossterm/pull/790, and should update crossterm in an independent PR. Related to #215
For image (sixel, iTerm2, Kitty...) support that handles graphics in
terms of `Rect` so that the image area can be included in layouts.
For example: an image is loaded with a known pixel-size, and drawn, but
the image protocol has no mechanism of knowing the actual cell/character
area that been drawn on. It is then impossible to skip overdrawing the
area.
Returning the window size in pixel-width / pixel-height, together with
colums / rows, it can be possible to account the pixel size of each cell
/ character, and then known the `Rect` of a given image, and also resize
the image so that it fits exactly in a `Rect` and avoid artifacts.
=> feat(backend): add window size api

CONTRIBUTING.md
This PR adds general guidelines on how to write documentation for Ratatui.
I based the guidelines off of #386 and #443.
=> chore: add documentation guidelines

src/backend/mod.rs, src/style.rs, src/widgets/calendar.rs
I just fixed some doc lint warning that were annoying while documenting as they prevented the switch to the `doc` job.
I don't see any documentation **build** test in `cargo make ci`, we probably should add it to avoid documentation mistakes?
<details><summary>Lint errors for `doc-open` job</summary>
<p>
</p>
</details>
=> docs: fix documentation lint warnings

src/terminal.rs
The current doc comment makes it seem as if `Termion` was the only supported backend.
=> chore(docs): fix doc comment

examples/scrollbar.rs, src/widgets/mod.rs, src/widgets/scrollbar.rs
This PR improves the documentation and adds a `new` constructor function to incentivize users to create a `ScrollbarState` with the appropriate `content_length` value.
Related to https://github.com/ratatui-org/ratatui/issues/414#issuecomment-1699801843
=> Better ergonomics for ScrollbarState and improved documentation 

.github/workflows/check-pr-title.yml
This runs a quick check to see if the PR title matches conventions commit guidelines. This action reruns if the title is edited and modified.
=> chore: Check that PR title matches conventional commit guidelines

Cargo.toml, benches/barchart.rs
Adds benchmarks for the `BarChart` widget.
Relates to #137.
Here is the resulting graph.
=> test(barchart): add benchmarks

.github/workflows/ci.yml, Makefile.toml
Adds a `check-doc` job to the Makefile. This job checks for errors and warnings in the doc-comments.
~I've added a meta-job `check` that runs `check-code` and `check-doc`.~
~The `check` job is run in CI so now the pipelines would check for code and documentation.~
~`check-code` replaces the old `check` job.~
~For me this is not a breaking change as it concerns tooling and not public APIs. I've also checked every place the `cargo check` job could have been referenced.~
I've used an unstable Rustdoc flag: `--check`, [see here](https://doc.rust-lang.org/rustdoc/unstable-features.html#--check-only-checks-the-documentation). Here is the [tracking issue](https://github.com/rust-lang/cargo/issues/10025).
I've used [`cargo rustdoc`](https://doc.rust-lang.org/cargo/commands/cargo-rustdoc.html) …
=> chore: check documentation lint

src/widgets/barchart/bar.rs, src/widgets/barchart/bar_group.rs, src/widgets/barchart/mod.rs
Add documentation to the `BarChart` widgets and its sub-modules.
Relates to #386.
<details><summary>Screenshots</summary>
<p>
</p>
</details>
=> docs(barchart): add documentation to `BarChart`

.github/workflows/ci.yml
Putting the formatting and doc checks first to ensure that more critical
errors are caught first (e.g. a conventional commit error or typo should
not prevent the formatting and doc checks from running).
See https://github.com/ratatui-org/ratatui/actions/runs/6058985586/job/16441639521?pr=462:
=> ci(lint): move formatting and doc checks first

.github/workflows/ci.yml, CONTRIBUTING.md, Makefile.toml
- add format target to Makefile.toml that actually fixes the formatting
- rename fmt target to lint-format
- rename style-check target to lint-style
- rename typos target to lint-typos
- rename check-docs target to lint-docs
- add section to CONTRIBUTING.md about formatting
=> ci(makefile): add format target

cliff.toml
```shell
git cliff --unreleased
```
[CHANGELOG.md](https://github.com/ratatui-org/ratatui/files/12503810/CHANGELOG.md)
=> ci: put commit id first in changelog

src/widgets/chart.rs, tests/widgets_chart.rs
Fixes: #379
old behavior
new fixed
=> fix(chart): fix chart row style being incorrect when using Axis::title

Makefile.toml
Only build termion on non-windows targets
=> ci(makefile): remove termion dependency from doc lint

src/widgets/table.rs
Added documentation for the `new` method of the `Table` widget
=> docs(table): added documentation for the 'new' method of the 'table' widget

src/title.rs, src/widgets/block.rs
Add documentation to the `Block` widget and its sub-components (`Padding`, `Borders`).
Relates to #386
=> docs(Block): add documentation to Block

cliff.toml
Before:
```md
- [0c68ebe](https://github.com/ratatui-org/ratatui/commit/0c68ebed4f63a595811006e0af221b11a83780cf)
*(Block)* Add documentation to Block ([#469](https://github.com/ratatui-org/ratatui/issues/469))
```
After:
```md
- [0c68ebe](https://github.com/ratatui-org/ratatui/commit/0c68ebed4f63a595811006e0af221b11a83780cf)
*(block)* Add documentation to Block ([#469](https://github.com/ratatui-org/ratatui/issues/469))
```
=> chore(changelog): make the scopes lowercase in the changelog

examples/scrollbar.rs, src/style/stylize.rs
Although the `Stylize` trait is already implemented for `&str` which
extends to `String`, it is not implemented for `String` itself. This
commit adds an impl of Stylize that returns a Span<'static> for `String`
so that code can call Stylize methods on temporary `String`s.
E.g. the following now compiles instead of failing with a compile error
about referencing a temporary value:
let s = format!("hello {name}!", "world").red();
BREAKING CHANGE: This may break some code that expects to call Stylize
methods on `String` values and then use the String value later. This
will now fail to compile because the String is consumed by set_style
instead of a slice being created and consumed.
This can be fixed by cloning the `String`. E.g.:
let s = String::from("hello world");
let line = …
=> fix(stylize)!: add Stylize impl for String

.github/workflows/check-pr-title.yml
This PR will do 3 things
1. Add a comment if the title is not in conventional commit specification, urging the PR submitter to change it
2. Remove the comment if the title is updated
3. Add a `breaking change` label if the title has a `!:` in it and follows the conventional commit specification.
=> chore: Add a check for if breaking change label should be added 

.github/workflows/check-pr.yml
This PR prevents merges if a `do not merge` label is added on GitHub.
This PR also fixes an issue that allows checking PR titles with backticks in the title string.
=> chore: Prevent PR merge with `do not merge` labels 

.github/workflows/check-pr.yml
From the documentation: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks. Avoid using this event if you need to build or run code from the pull request.
=> chore: only run check pr action on pull_request_target events

src/style.rs, src/style/stylize.rs
The Stylize trait was introduced in 0.22 to make styling less verbose.
This adds a bunch of documentation comments to the style module and
types to make this easier to discover.
Addresses the lack of info on the Stylize shorthands mentioned in https://github.com/ratatui-org/ratatui/issues/448
=> docs(stylize): improve docs for style shorthands

src/backend/test.rs, src/buffer.rs, src/layout.rs, src/lib.rs, src/prelude.rs, src/style.rs, src/style/color.rs, src/terminal.rs, src/text/line.rs, src/text/masked.rs, src/text/mod.rs, src/text/span.rs, src/text/spans.rs, src/text/text.rs, src/title.rs, src/widgets/barchart/bar.rs, src/widgets/barchart/bar_group.rs, src/widgets/barchart/mod.rs, src/widgets/block.rs, src/widgets/canvas/mod.rs, src/widgets/chart.rs, src/widgets/clear.rs, src/widgets/gauge.rs, src/widgets/list.rs, src/widgets/mod.rs, src/widgets/paragraph.rs, src/widgets/scrollbar.rs, src/widgets/sparkline.rs, src/widgets/table.rs, src/widgets/tabs.rs
This commit adds `prelude::*` all doc examples and widget::* to those
that need it. This is done to highlight the use of the prelude and
simplify the examples.
- Examples in Type and module level comments show all imports and use
`prelude::*` and `widget::*` where possible.
- Function level comments hide imports unless there are imports other
than `prelude::*` and `widget::*`.
Fixes https://github.com/ratatui-org/ratatui/issues/448 by ensuring that module and type level code always contains all the imports required to compile the example.
=> docs: import prelude::* in doc examples

src/lib.rs, src/prelude.rs, src/terminal.rs
- moves the impl Terminal block up to be closer to the type definition
Pulls in doc changes from #280 in an attempt to simplify that PR (more to come for other types).
=> docs(terminal): add docs for terminal module

src/buffer.rs, src/layout.rs, src/widgets/list.rs, src/widgets/tabs.rs, tests/widgets_chart.rs
This allows writing unit tests without having to call set_style on the
expected buffer.
E.g.:
```rust
use crate::style::Stylize;
let mut buf = Buffer::empty(Rect::new(0, 0, 10, 10));
buf.set_string(0, 0, "foo", Style::new().red());
buf.set_string(0, 1, "bar", Style::new().blue());
assert_eq!(buf, Buffer::with_lines(vec!["foo".red(), "bar".blue()]));
```
Inspired by https://github.com/ratatui-org/ratatui/issues/493#issuecomment-1714844468
=> test(buffer): allow with_lines to accept Vec<Into<Line>>

Cargo.toml, src/layout.rs
This pull request avoids the growth of Layout cache without any bounds.
The Layout cache is now using an LruCache ([doc](https://docs.rs/lru/latest/lru/)).
The current default cache size is set to 16. It seems reasonable for me to keep this value low.
A user can set the cache size during the Layout instantiation.
fix #402
=> fix(Layout): layout cache does not grow without bounds

src/backend.rs
Windows cannot compile termion, so it is not included in the docs.
Rustdoc will fail if it cannot find a link, so the docs fail to build
on windows.
This replaces the link to TermionBackend with one that does not fail
during checks.
Fixes https://github.com/ratatui-org/ratatui/issues/498
=> fix(docs): don't fail rustdoc due to termion

src/backend.rs, src/widgets/table.rs
Additionally, add `fix(docs): don't fail rustdoc due to termion`
=> docs(table): add documentation for `block` and `header` methods of the `Table` widget

src/widgets/gauge.rs
Adds documentation to `Gauge` and `LineGauge` widgets.
Relates to #386
<details><summary>Screenshots</summary>
<p>
</p>
</details>
=> docs(Gauge): add documentation to `Gauge`

src/widgets/barchart.rs, src/widgets/barchart/bar.rs
value_label.len() deliver byte length of the unicode strings, which are
not printed as a result.
use witdh() instead.
=> fix(barchart): fix(barchart): use width() instead of len() to get unicode string length

src/layout.rs
Fix arithmetic overflow reported on #517 #520
=> fix(Rect): Modify to use saturating ops to prevent arith overflow

.markdownlint.yaml, Cargo.toml, README.md, RELEASE.md, examples/README.md, examples/colors_rgb.rs, examples/demo2-social.tape, examples/demo2.tape, examples/demo2/app.rs, examples/demo2/colors.rs, examples/demo2/main.rs, examples/demo2/root.rs, examples/demo2/tabs.rs, examples/demo2/tabs/about.rs, examples/demo2/tabs/email.rs, examples/demo2/tabs/recipe.rs, examples/demo2/tabs/traceroute.rs, examples/demo2/tabs/weather.rs, examples/demo2/term.rs, examples/demo2/theme.rs, src/lib.rs
This is example is aimed at creating a github social preview image and
eventually replacing the current main demo.
<details>
<summary>outdated images</summary>
https://github.com/ratatui-org/ratatui/assets/381361/8255624d-9237-44da-8655-a489aaf5e1e5
</details>
=> feat(examples): add demo2 example

src/widgets/barchart.rs
- fix(table): add default column widths for when none are supplied
- implement suggestions in comments
- add docs, correct length calculation
- simplify logic in constructing constraints
- add docs to public methods
- fix overflow panic
- fix(barchart): avoid divide by zero in rendering
=> fix(barchart): divide by zero in render

src/widgets/barchart.rs
Fixed horizontal bars label not displayed.
Also adds ways to configure label truncation because it would be hard to use labels horizontally otherwise.
This fixes #499
=> fix(Barchart): horizontal labels were not displayed

src/symbols.rs, src/widgets/block.rs
Adds a new `Block::border_set` method that allows the user to specify
the symbols used for the border.
Added two new border types: `BorderType::QuadrantOutside` and
`BorderType::QuadrantInside`. These are used to draw borders using the
unicode quadrant characters (which look like half block "pixels").
```
▛▀▀▜
▌  ▐
▙▄▄▟
▗▄▄▖
▐  ▌
▝▀▀▘
```
Fixes: https://github.com/ratatui-org/ratatui/issues/528
BREAKING CHANGES:
- BorderType::to_line_set is renamed to to_border_set
- BorderType::line_symbols is renamed to border_symbols
=> feat(block)!: allow custom symbols for borders

src/layout.rs, src/layout/rect.rs
- refactor(rect): extract Rect to layout/rect.rs
- feat(rect): add is_empty() to simplify some common checks
=> feat(rect): add is_empty() to simplify some common checks

examples/barchart.rs, examples/block.rs, examples/calendar.rs, examples/canvas.rs, examples/chart.rs, examples/colors.rs, examples/custom_widget.rs, examples/demo/ui.rs, examples/gauge.rs, examples/hello_world.rs, examples/inline.rs, examples/layout.rs, examples/list.rs, examples/modifiers.rs, examples/panic.rs, examples/paragraph.rs, examples/popup.rs, examples/scrollbar.rs, examples/sparkline.rs, examples/table.rs, examples/tabs.rs, examples/user_input.rs, src/layout.rs, src/lib.rs, src/terminal.rs, src/widgets/block.rs, src/widgets/clear.rs, src/widgets/scrollbar.rs
The purpose of this change is to simplify UI code that uses the Frame
type. E.g.:
```
fn draw<B: Backend>(frame: &mut Frame<B>) {
// ...
}
```
Frame was generic over Backend because it stored a reference to the
terminal in the field. Instead it now directly stores the viewport area
and current buffer. These are provided at creation time and are valid
for the duration of the frame.
BREAKING CHANGE: Frame is no longer generic over Backend. Code that
accepted a Frame<Backend> will now need to accept a Frame.
=> feat(frame)!: Remove generic Backend parameter

examples/tabs.rs, src/widgets/tabs.rs
<details><summary>Screenshot</summary>
<p>
</p>
</details>
=> docs(tabs): add documentation to `Tabs`

src/widgets/barchart.rs, src/widgets/barchart/bar.rs
Add an internal structure `LabelInfo`, which stores the reserved height for the labels (0, 1 or 2) and also the state of the labels, whether they will be shown or not.
Add internal property to the Bar `transformed_value`, which is used only for in the vertical charts. This value is needed in 2 reasons:
1. to draw the vertical bar
2. to draw the bar value or text_value. If the transformed_value is below 8 and the bar_width is 1, then the value will not be printed
transformed_value is line height multiplied by 8.
(8 is the number of element of symbols::bar::Set struct)
fixes #513
[![asciicast](https://asciinema.org/a/s69ZQrsjNDO8syNuA5415aVgp.svg)](https://asciinema.org/a/s69ZQrsjNDO8syNuA5415aVgp)
=> feat(barchart): allow to render charts smaller than 3 lines

examples/custom_widget.rs, examples/custom_widget.tape
The widget also now supports mouse
https://github.com/ratatui-org/ratatui/assets/381361/a4de662e-1367-4f62-ba69-d7061fa858f4
=> docs(examples): make custom widget example into a button

RELEASE.md
Fixes https://github.com/ratatui-org/ratatui/issues/412
=> docs: document alpha release process

src/layout/rect.rs
Fixes https://github.com/ratatui-org/ratatui/issues/258
=> fix(rect): fix arithmetic overflow edge cases

src/terminal.rs
This PR removes an incomplete phrase in the docstring for `Terminal`.
=> docs: Fix `Terminal` docstring

src/terminal.rs
The documentation currently says `This allows for widgets to be drawn in any order.` which I believe is incorrect.
I removed that line and tweaked the remaining text for more clarity.
=> docs: Improve clarity in documentation for `Frame`

src/terminal.rs
`current_buffer_mut` already exists on `Terminal`. It would be nice to expose the same thing to `Frame` as well.
=> feat: Add `buffer_mut` method on `Frame`

examples/canvas.rs, examples/canvas.tape, examples/demo2/tabs/traceroute.rs, src/symbols.rs, src/widgets/canvas.rs, src/widgets/canvas/rectangle.rs
A useful technique for the terminal is to use half blocks to draw a grid
of "pixels" on the screen. Because we can set two colors per cell, and
because terminal cells are about twice as tall as they are wide, we can
draw a grid of half blocks that looks like a grid of square pixels.
This commit adds a new `HalfBlock` marker that can be used in the Canvas
widget and the associated HalfBlockGrid.
=> feat(canvas): implement half block marker

README.md, examples/barchart.rs, examples/block.rs, examples/calendar.rs, examples/canvas.rs, examples/chart.rs, examples/colors.rs, examples/colors_rgb.rs, examples/custom_widget.rs, examples/demo/ui.rs, examples/demo2/tabs/traceroute.rs, examples/docsrs.rs, examples/gauge.rs, examples/inline.rs, examples/layout.rs, examples/list.rs, examples/modifiers.rs, examples/paragraph.rs, examples/popup.rs, examples/scrollbar.rs, examples/sparkline.rs, examples/table.rs, examples/tabs.rs, examples/user_input.rs, src/layout.rs, src/lib.rs, tests/widgets_gauge.rs
Use bare arrays rather than array refs / Vecs for all constraint
examples.
Ref: https://github.com/ratatui-org/ratatui-book/issues/94
=> chore: simplify constraints

examples/custom_widget.rs
Makes the example more intuitive (imo) when trying out the demo with mouse. User can click to make state of the button `Active`, and click again to make it `Normal`. When in `Active` state, hover related changes are ignored.
=> docs(custom_widget): make button sticky when clicking with mouse

src/terminal.rs
As of https://github.com/ratatui-org/ratatui/pull/530, `Frame` is no longer generic over the `Backend`.
=> docs: Update `Frame` docstring to remove reference to generic backend

README.md
Replaced 4 bullet points with colons under the "third-party libraries" header in README.md with dashes. This is because most other bullet points had a link to the library and then a dash, not a colon.
=> docs: Replace colons with dashes in README.md for consistency

Cargo.toml, Makefile.toml, src/backend/crossterm.rs, src/buffer.rs, src/style.rs, src/widgets/gauge.rs
Windows 7 doesn't support the underline color attribute, so we need to
make it optional. This commit adds a feature flag for the underline
color attribute - it is enabled by default, but can be disabled by
passing `--no-default-features` to cargo.
We could specically check for Windows 7 and disable the feature flag
automatically, but I think it's better for this check to be done by the
crossterm crate, since it's the one that actually knows about the
underlying terminal.
To disable the feature flag in an application that supports Windows 7,
add the following to your Cargo.toml:
```toml
ratatui = { version = "0.24.0", default-features = false, features = ["crossterm"] }
```
Fixes https://github.com/ratatui-org/ratatui/issues/555
=> fix(backend): add feature flag for underline-color

examples/gauge.rs, examples/gauge.tape, src/widgets/gauge.rs, tests/widgets_gauge.rs
The background colors of the gauge had a workaround for the issue we had
with VHS / TTYD rendering the background color of the gauge. This
workaround is no longer necessary in the updated versions of VHS / TTYD.
Fixes https://github.com/ratatui-org/ratatui/issues/501
=> fix(gauge): fix gauge widget colors

README.md
fixes a problem in README.md where the links to CONTRIBUTING.md and BREAKING-CHANGES.md weren't working.
=> docs(README): fix links to CONTRIBUTING.md and BREAKING-CHANGES.md

examples/barchart.rs, examples/chart.rs, examples/demo/crossterm.rs, examples/demo/termwiz.rs, examples/inline.rs, examples/list.rs, examples/paragraph.rs, examples/scrollbar.rs, examples/sparkline.rs
This PR improves some examples a bit.
- The combination of `Duration::checked_sub` and `Option::unwrap_or_else` calls can be simplified with single `Duration::saturating_sub` call.
- Errors from `poll_input` should not be ignored in `termwiz` support example.
=> chore(examples): refactor some examples

.github/CODEOWNERS
I tried to reach out to @sophacles on Discord but couldn't get a reply. I think we can remove him until he's more available to provide reviews for pull requests.
=> docs(github): update code owners

.github/workflows/ci.yml, BREAKING-CHANGES.md, Cargo.toml
`OnceLock` has been stabilized in `rustc --version`: `1.70.0`.
=> fix: MSRV is now `1.70.0`

src/backend.rs, src/backend/test.rs, src/terminal.rs, tests/terminal.rs
This PR fixes some issues encountered in #584 by way of rewriting the `insert_before` method.
> **The function signature for reference:** 
> ```rs
> pub fn insert_before<F>(&mut self, height: u16, draw_fn: F) -> io::Result<()>
> ```
Ultimately it does two things:
1. It fixes a bug triggered by the `height` parameter of a call to `insert_before` being greater than `self.viewport_area.height` - This bug would cause an extra newline to be inserted leaving a gap in the output.
2. Removes the `height` cap by rendering output in chunks. if `height` is too large to fit on the screen (with the viewport) then chunks are rendered as the screen is scrolled.
~~There are currently no tests for the `insert_before` method; I've attempted to test this change with the `TestBackend` but unfortunately due …
=> fix: Rewrite the insert_before method on Terminal to fix a bug and remove the height cap

src/backend/crossterm.rs, src/backend/termion.rs, src/backend/termwiz.rs, src/backend/test.rs, src/buffer.rs, src/widgets/canvas/line.rs, tests/terminal.rs
This PR deprecates accessing `Cell::symbol` field following the discussion at #601.
1. Add deprecation message on `Cell::symbol` field and getter API for the field
2. Release ratatui v0.24.1 (or v0.24.2 if v0.24.1 doesn't fit)
3. Hide the symbol field
4. Release the change at v0.25.0
This PR does the step 1. assuming to be included in v0.24.1.
=> feat(buffer): deprecate `Cell::symbol` field

src/buffer.rs
I noticed one doc example still accessed `Cell::symbol` field deprecated at #624. `cargo test --doc` doesn't show any warnings. `cargo clippy` doesn't check doc examples. So I didn't notice it. This PR fixes the example.
=> fix(doc): do not access deprecated `Cell::symbol` field in doc example

BREAKING-CHANGES.md, examples/demo/ui.rs, examples/demo2/tabs/recipe.rs, examples/demo2/tabs/traceroute.rs, examples/table.rs, src/widgets/table.rs, tests/widgets_table.rs
This allows passing an array, slice or Vec of constraints, which is more
ergonomic than requiring this to always be a slice.
The following calls now all succeed:
```rust
Table::new(rows).widths([Constraint::Length(5), Constraint::Length(5)]);
Table::new(rows).widths(&[Constraint::Length(5), Constraint::Length(5)]);
// widths could also be computed at runtime
let widths = vec![Constraint::Length(5), Constraint::Length(5)];
Table::new(rows).widths(widths.clone());
Table::new(rows).widths(&widths);
```
Fixes: https://discord.com/channels/1070692720437383208/1072907135664529508/1174137200909221988
---
> I have a ratatui table widget which I return from a function, but due to the widths function requiring a reference to a value, it yells at me for referencing a temporary value
```rs …
```
=> fix(table): widths() now accepts AsRef<[Constraint]>

Cargo.toml
This disables the default benchmarking behaviour for the lib target to fix unrecognized criterion benchmark arguments as specified in the [FAQ](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options) of criterion.
I came accross this error when trying to save a baseline for the benchmarks using the [`--save-baseline`](https://bheisler.github.io/criterion.rs/book/user_guide/command_line_options.html#baselines) option.
=> chore: disable default benchmarking

BREAKING-CHANGES.md, README.md, src/layout.rs, src/lib.rs
Adds a convenience function to create a layout with a direction and a
list of constraints which are the most common parameters that would be
generally configured using the builder pattern. The constraints can be
passed in as any iterator of constraints.
```rust
let layout = Layout::new(Direction::Horizontal, [
Constraint::Percentage(50),
Constraint::Percentage(50),
]);
```
BREAKING CHANGE:
Layout::new() now takes a direction and a list of constraints instead of
no arguments. This is a breaking change because it changes the signature
of the function. Layout::new() is also no longer const because it takes
an iterator of constraints.
Layout::new() was added in a recent release, so the amount of code broken by this is reasonably small. Tagging the owners of affected repos as a headsup: …
=> feat(layout)!: add parameters to Layout::new()

BREAKING-CHANGES.md
Moves the layout::new change to unreleasedd section and adds the table change
=> chore: fix breaking changes doc versions

src/widgets/sparkline.rs
Adds documentation to the `Sparkline` widget.
Relates to #386
<details><summary>Screenshots</summary>
<p>
</p>
</details>
=> docs(Sparkline): add documentation

src/layout/rect.rs, src/layout/rect/offset.rs
As discussed [here](https://github.com/ratatui-org/ratatui/pull/518#discussion_r1333715626). 
Add `inset` and `offset` methods to respectively adjust a `Rect` size and move it.
This is common logic in renders and apps.
I used generics to allow direct calculation in the call, like [here](https://github.com/ratatui-org/ratatui/compare/main...Valentin271:ratatui:feat/rect-manipulation-utils?expand=1#diff-7a977f85afc247cf4ed30e8453eb44fd67f06ba2c92115f157c58ebb23d0a3f6R351). This just avoids having to wrap calculations in parenthesis and calling `into()`.
I used two different generics to allow giving different types (e.g. `u16` calculation and `i32` literal).
A signed int allows to move the `Rect` forward or backward.
I used an ~`i64`~ `i32` as parameter to allow moving `x` and `y` from their …
=> feat(Rect): add `offset` method

src/widgets/block.rs, src/widgets/paragraph.rs
Previously, when computing the inner rendering area of a block, all titles were assumed to be positioned at the top. If some or all titles were at the bottom, this caused various incorrect computations of the inner area, depending on which borders were set; no border at the bottom would lead to an area that's too big, no border at the top but at the bottom and _all_ titles at the bottom would lead to an area that's too small.
Now, when computing the inner area, the positions of the titles are taken into account.
fix #658
=> fix(block): make `inner` aware of title positions

src/widgets/tabs.rs
Two changes without any line overlap caused the tabs tests to break
=> fix(tabs): fixup tests broken by semantic merge conflict

src/layout.rs, src/widgets/table.rs, src/widgets/tabs.rs
- style(tabs): fix doc formatting
- feat(layout): Accept IntoIterator for constraints
=> feat(layout): Accept IntoIterator for constraints

src/layout.rs, src/widgets/table.rs
It works just like Layout::segment_size, but for Tables.  Previously, it was impossible to distribute extra space anywhere in a Table.
Fixes #370
=> feat(table): Add a Table::segment_size method

BREAKING-CHANGES.md, examples/demo/ui.rs, examples/demo2/tabs/recipe.rs, examples/demo2/tabs/traceroute.rs, examples/table.rs, src/widgets/table.rs, tests/widgets_table.rs
- style(tabs): fix doc formatting
- feat(layout): Accept IntoIterator for constraints
- fix(table)!: Add widths parameter to new()
=> fix(table)!: Add widths parameter to new()

src/widgets/paragraph.rs, src/widgets/reflow.rs
It makes the type easier to document, and more obvious for users, given that #607 makes this part of the public API
=> refactor: define struct WrappedLine instead of anonymous tuple

src/widgets/list.rs
Adds documentation to the `List` widget and all its sub components like `ListState` and `ListItem`
Relates to #386
<details><summary>List</summary>
<p>
</p>
</details>
<details><summary>ListItem</summary>
<p>
</p>
</details> 
<details><summary>ListState</summary>
<p>
</p>
</details>
=> docs(list): add documentation to the List widget

Cargo.toml, src/widgets/paragraph.rs
This PR adds two methods to the `Paragraph` widget to help get information about the rendered paragraph. The first method, `Paragraph::line_count`, takes a bounding width and returns the number of lines necessary to display the full paragraph when rendered. My motivation for this method is to use it with scrollbars. If a paragraph has wrapped text, it is currently impossible to get the number of lines it will need.
The second method is a natural extension of this, `Paragraph::line_width`. This returns the smallest line width needed to fully display every line of a paragraph. This is simply the maximum line widths. Together, these two methods can be used to calculate the minimum bounding box for a paragraph.
=> feat(Paragraph): add `line_count` and `line_width` unstable helper methods

BREAKING-CHANGES.md, src/widgets/list.rs, tests/widgets_list.rs
This allows to build list like
```rust
List::new(["Item 1", "Item 2"])
```
Fixes #670 
I think this should be added for 0.26 to not add too much breaking change for 0.25. Moreover there's another breaking change for list coming with #671. It makes sense to release them together.
=> feat(List)!: `new` now accepts `IntoIterator<Item = Into<ListItem>>`

src/layout/rect.rs
From @bugnano in #677
> The `Rect.intersection` method contained the simple `-` operator, which panics on underflow.
> This is strange, as all the other methods in `Rect` use `saturating_add` and `saturating_sub`.
> So I changed the `-` operation to a `saturating_sub`, so that `Rect.intersection` never panics.
With a signed commit and a unit test.
=> fix(Rect): fixes underflow in the `Rect::intersection` method

BREAKING-CHANGES.md, examples/list.rs, src/widgets.rs, src/widgets/list.rs
The previous name `start_corner` did not communicate clearly what the function was doing. The method was renamed to `direction` and a new enum `ListDirection` was added.
Fixes #671 
Same as #672, I feel like this should be for 0.26.
=> refactor(List): `start_corner` is now `direction`

src/layout.rs
Adds helper methods that convert from iterators of u16 values to the
specific Constraint type. This makes it easy to create constraints like:
```rust
// a fixed layout
let constraints = Constraint::from_lengths([10, 20, 10]);
// a centered layout
let constraints = Constraint::from_ratios([(1, 4), (1, 2), (1, 4)]);
let constraints = Constraint::from_percentages([25, 50, 25]);
// a centered layout with a minimum size
let constraints = Constraint::from_mins([0, 100, 0]);
// a sidebar / main layout with maximum sizes
let constraints = Constraint::from_maxes([30, 200]);
```
=> feat: add Constraint helpers (e.g. from_lengths)

src/widgets/table.rs
This PR aims to fix an issue in the `render_cell` function that could lead to an index out of range error. The problem was caused by incorrect positioning of the `x` coordinate in the original code.
Fixes #684
=> fix: Render table with overflow

src/widgets/table.rs
- Refactor the `table` module to for better top to bottom readability by
putting types first and arranging them in a logical order (Table, Row,
Cell, other).
- Adds new methods for:
- `Table::rows`
- `Row::cells`
- `Cell::new`
- `Cell::content`
- `TableState::new`
- `TableState::selected_mut`
- Makes `HighlightSpacing::should_add` pub(crate) since it's an internal
detail.
- Adds tests for all the new methods and simple property tests for all
the other builder style methods.
=> chore(table): cleanup docs and builder methods

Cargo.toml, examples/README.md, examples/ratatui-logo.rs, examples/ratatui-logo.tape
Just a fun example because the font I looked at as the "temporary" logo text seemed like it lends itself to an experiment.
=> docs(examples): Add example of half block rendering

examples/canvas.rs, examples/custom_widget.rs, examples/demo/crossterm.rs, examples/demo/termion.rs, examples/demo/termwiz.rs, examples/list.rs, examples/table.rs, examples/tabs.rs
Adds vim bindings to examples.
I use examples a lot to test my implementations and this was driving me nuts.
I also feel like someone interested in a TUI is somewhat familiar with these. Kept the arrow keys anyway as it's good to have the choice.
=> refactor(examples): add vim binding

examples/chart.rs, src/widgets.rs, src/widgets/chart.rs
Migerated PR from tui-rs is #25
Add option to position the legend at corner. The option uses tui::layout::Corner emum that already made.
If the layout have axis title, the layout draw the legend position above x axis title or under y axis title.
Examples all positions of legend
I make 3 tests for each corners of legend based on original test for legend.
=> feat(widgets/chart): add option to set the position of legend

BREAKING-CHANGES.md, src/buffer.rs, src/widgets/chart.rs
Remove `Axis::title_style` and `Buffer::set_background` which are deprecated since 0.10
I also removed the breaking message from #673 because as discussed there a deprecation notice is not a breaking change.
=> refactor!: remove items deprecated since 0.10

rustfmt.toml, src/backend.rs, src/backend/crossterm.rs, src/backend/termion.rs, src/buffer.rs, src/layout.rs, src/lib.rs, src/style.rs, src/style/color.rs, src/style/stylize.rs, src/terminal.rs, src/text.rs, src/text/line.rs, src/text/span.rs, src/text/text.rs, src/title.rs, src/widgets.rs, src/widgets/block.rs, src/widgets/canvas.rs, src/widgets/chart.rs, src/widgets/list.rs, src/widgets/paragraph.rs, src/widgets/scrollbar.rs, src/widgets/table.rs
This enables more consistently formatted code in doc comments, especially since ratatui heavily uses fluent setters.
See https://rust-lang.github.io/rustfmt/?version=v1.6.0#format_code_in_doc_comments
We're already using rustfmt nightly so this shouldn't change the pipelines or toolchains.
See the diff for the benefits this brings.
What do you guys think about that?
=> chore(rustfmt): enable format_code_in_doc_comments

src/symbols.rs, src/widgets/chart.rs
This fixes #386 and completes the documentation for the widgets module apart from canvas.
<details><summary>doc screenshots</summary>
<p>
</p>
</details>
=> docs(chart): document chart module

src/backend/termion.rs
=> feat: implement `From` trait for termion to `Style` related structs

Cargo.toml, examples/README.md, examples/colors_rgb.rs, examples/colors_rgb.tape
This doesn't render nicely in VHS yet unfortunately (there's some odd screen tearing that happens)
https://github.com/ratatui-org/ratatui/assets/381361/5cd99151-0511-4501-a4b6-3704b82317dd
=> docs(examples): add animation and FPS counter to colors_rgb

BREAKING-CHANGES.md
We have 2 breaking changes that effects `Table` so I think we should recommend using the new constructor instead of the old one.
=> docs: remove deprecated table constructor from breaking changes

BREAKING-CHANGES.md, CHANGELOG.md, Cargo.toml
=> chore(release): prepare for 0.25.0

.github/workflows/calculate-alpha-release.bash, .github/workflows/cd.yml
Automatically detect breaking changes based on commit messages
and bump the alpha release number accordingly.
E.g. v0.23.1-alpha.1 will be bumped to v0.24.0-alpha.0 if any commit
since v0.23.0 has a breaking change.
=> chore(ci): bump alpha release for breaking changes

examples/chart.rs
I reworked the chart example to showcase the scatter chart which was missing before. While at it, I also used some real data.
| Before | After |
|--------|--------|
| ![image](https://github.com/ratatui-org/ratatui/assets/36198422/06966fb3-9ba8-4f24-bb19-aba2d126ebc5) | ![image](https://github.com/ratatui-org/ratatui/assets/36198422/99177c01-c68d-4cda-95b3-3cbf87a7ae4c) |
=> docs(examples): refactor chart example to showcase scatter

BREAKING-CHANGES.md, src/text/line.rs
- The `Line` struct now stores the style of the line rather than each
`Span` storing it.
- Adds two new setters for style and spans
- Adds missing docs
BREAKING CHANGE: `Line::style` is now a field of `Line` instead of being
stored in each `Span`.
=> feat(line)!: add style field, setters and docs

.github/workflows/ci.yml, Makefile.toml
Switch to [nextest](https://nexte.st/) for running tests.
Motivation:
- `cargo test`: 19.332s
- `cargo nextest run`: 0.981s
Please note:
- `cargo-nextest` does not support running doctests yet: https://github.com/nextest-rs/nextest/issues/16
- The `cargo-nextest` binary is installed automatically via `cargo-make`, see https://github.com/sagiegurari/cargo-make#crates
=> chore(ci): use cargo-nextest for running tests

src/text.rs, src/text/line.rs
This allows us to use Line as a child of other widgets, and to use
Line::render() to render it rather than calling buffer.set_line().
```rust
frame.render_widget(Line::raw("Hello, world!"), area);
// or
Line::raw("Hello, world!").render(frame, area);
```
---
Rebase and merge after #713 is merged
=> feat(line): implement Widget for Line

examples/table.rs, src/widgets/table/row.rs, src/widgets/table/table.rs
Add a footer method for a table, adding a Row always visible at the bottom.
The behavior is similar to the header of the table.
Due to comity #718 and gpg sign requirement in #719, the PR is reopened with the same ideal as https://github.com/ratatui-org/ratatui/pull/716.
=> feat(table): Add Table::footer and Row::top_margin methods

BREAKING-CHANGES.md, examples/calendar.rs, src/buffer.rs, src/buffer/buffer.rs, src/buffer/cell.rs, src/style.rs, src/style/color.rs, src/style/stylize.rs, src/text/grapheme.rs, src/text/line.rs, src/text/span.rs, src/text/text.rs, src/widgets/barchart.rs, src/widgets/barchart/bar.rs, src/widgets/block.rs, src/widgets/calendar.rs, src/widgets/chart.rs, src/widgets/gauge.rs, src/widgets/list.rs, src/widgets/paragraph.rs, src/widgets/scrollbar.rs, src/widgets/sparkline.rs, src/widgets/table/cell.rs, src/widgets/table/row.rs, src/widgets/table/table.rs, src/widgets/tabs.rs
All style related methods now accept `S: Into<Style>` instead of
`Style`.
`Color` and `Modifier` implement `Into<Style>` so this is allows for
more ergonomic usage. E.g.:
```rust
Line::styled("hello", Style::new().red());
Line::styled("world", Style::new().bold());
// can now be simplified to
Line::styled("hello", Color::Red);
Line::styled("world", Modifier::BOLD);
```
Fixes https://github.com/ratatui-org/ratatui/issues/694
BREAKING CHANGE: All style related methods now accept `S: Into<Style>`
instead of `Style`. This means that if you are already passing an
ambiguous type that implements `Into<Style>` you will need to remove
the `.into()` call.
`Block`s with styles can no longer be created in a const context as
traits do not yet support const functions.
=> feat: accept Color and Modifier for all Styles

examples/README.md
By adding a newline, the NOTE can be rendered as follows:
=> docs(example): fix markdown syntax for note

src/layout/constraint.rs, src/layout/layout.rs
This allows Layout constructors to accept any type that implements
Into<Constraint> instead of just AsRef<Constraint>. This is useful when
you want to specify a fixed size for a layout, but don't want to
explicitly create a Constraint::Length yourself.
```rust
Layout::new(Direction::Vertical, [1, 2, 3]);
Layout::horizontal([1, 2, 3]);
Layout::vertical([1, 2, 3]);
Layout::default().constraints([1, 2, 3]);
```
=> feat(layout): accept Into<Constraint> for constructors

src/layout/layout.rs, src/widgets/table/table.rs
This allows Table constructors to accept any type that implements
Into<Constraint> instead of just AsRef<Constraint>. This is useful when
you want to specify a fixed size for a table columns, but don't want to
explicitly create a Constraint::Length yourself.
```rust
Table::new(rows, [1,2,3])
Table::default().widths([1,2,3])
```
---
PR includes https://github.com/ratatui-org/ratatui/pull/744 - merge that first
=> feat(table): accept Into<Constraint> for widths

src/widgets/block.rs
This avoid creating a block with no borders and then settings Borders::ALL. i.e.
```diff
- Block::default().borders(Borders::ALL);
+ Block::all_borders();
```
Searching on github, [1.3K use `.borders(Borders:ALL)`](https://github.com/search?q=ratatui+.borders%28Borders%3A%3AALL%29+lang%3Arust+NOT+repo%3Aratatui-org%2Fratatui&type=code) for a total of [1.5K `.borders(` usage](https://github.com/search?q=ratatui+.borders%28+lang%3Arust+NOT+repo%3Aratatui-org%2Fratatui&type=code).
Names I considered:
- `all`: too implicit, `Block::all()` in the wild isn't clear
- `with_borders`: would be confused with `with_borders(b: Borders)` i.e. with a parameter
- `with_all_borders`: the most explicit but too long imo
- `borders_all`: to match with `Borders::ALL` enum, nothing wrong with that, I just …
=> feat(block): add `Block::bordered`

examples/barchart.rs, examples/block.rs, examples/calendar.rs, examples/canvas.rs, examples/chart.rs, examples/colors.rs, examples/colors_rgb.rs, examples/custom_widget.rs, examples/demo/ui.rs, examples/demo2/root.rs, examples/demo2/tabs/about.rs, examples/demo2/tabs/email.rs, examples/demo2/tabs/recipe.rs, examples/demo2/tabs/traceroute.rs, examples/demo2/tabs/weather.rs, examples/docsrs.rs, examples/gauge.rs, examples/inline.rs, examples/layout.rs, examples/list.rs, examples/modifiers.rs, examples/paragraph.rs, examples/popup.rs, examples/scrollbar.rs, examples/sparkline.rs, examples/table.rs, examples/tabs.rs, examples/user_input.rs, src/widgets/table/table.rs
Use the new `Layout::horizontal` and `vertical` constructors and
`Rect::split_array` through all the examples.
=> docs(examples): simplify docs using new layout methods

Cargo.toml, src/layout/rect.rs
This ensures a rectangle does not end up outside an area. This is useful
when you want to be able to dynamically move a rectangle around, but
keep it constrained to a certain area.
For example, this can be used to implement a draggable window that can
be moved around, but not outside the terminal window.
```rust
let window_area = Rect::new(state.x, state.y, 20, 20).clamp(area);
state.x = rect.x;
state.y = rect.y;
```
=> feat(layout): add `Rect::clamp()` method

BREAKING-CHANGES.md, src/widgets/block.rs
`Block::title_on_bottom` was deprecated in v0.22. Use `Block::title` and `Title::position` instead.
References #738
=> refactor(block)!: remove deprecated `title_on_bottom`

examples/table.rs, src/widgets/table/row.rs
The `Row::new` constructor accepts a single argument that implements `IntoIterator`.  This commit adds an implementation of `FromIterator`, as a thin wrapper around `Row::new`.  This allows `.collect::<Row>()` to be used at the end of an iterator chain, rather than wrapping the entire iterator chain in `Row::new`.
Examples in `examples/table.rs` that used an intermediate variable for the cell iterator have been updated to instead collect directly into a `Row`.  Examples that have an explicit `vec![cell1, ..., cellN]` have been kept as-is.
=> feat(table): Implement FromIterator for widgets::Row

BREAKING-CHANGES.md, examples/user_input.rs, src/text/line.rs, src/text/span.rs, src/text/text.rs
Previously, `patch_style` and `reset_style` in `Text`, `Line` and `Span` were using a mutable reference to `Self`. To be more consistent with the rest of `ratatui`, which is using fluent setters, these now take ownership of `Self` and return it.
Closes #644
=> refactor!: make `patch_style` & `reset_style` chainable

examples/chart.rs, src/widgets/chart.rs
Resubmission of #527 as the author seems to be inactive since 3 weeks and the PR is almost done.
@alemidev wrote:
> Currently, creating a `Dataset` to be used with the `Chart` widget will put an empty name by default. When not overriding it with the `.name()` builder method, it will still appear in the resulting chart legend as an empty space.
>
> In a project of mine I draw more specific reference grids as lines with no names, and the legend field either gets filled with empty spaces or not drawn at all due to its length.
>
> With this change, legend won't be drawn for datasets with no name.
>
> To make the name optional in the struct, I changed the `Cow<str>` into an `Option<Cow<str>>` and excluded datasets with empty names using `.filter_map()` in place of simple `.maps()` while …
=> fix(chart): exclude unnamed datasets from legend

.github/workflows/calculate-alpha-release.bash
The alpha deployment has been broken for 3 weeks, precisely since https://github.com/ratatui-org/ratatui/pull/495
(older first)
- https://github.com/ratatui-org/ratatui/actions/runs/7304892972/job/19907742693
- https://github.com/ratatui-org/ratatui/actions/runs/7360766607/job/20037290884
- https://github.com/ratatui-org/ratatui/actions/runs/7428042304/job/20214757237
There was no log but testing locally I figured grepping the last release wasn't working because of `\d` not working with `-E` flag.
I used perl compatible regular expression `-P`, we might also use `-E` together with `[0-9]` if we prefer.
Once this is merged I think it's worth manually triggering the workflow to have an alpha after 0.25 and see if everything works.
EDIT: I also fixed a typo in a variable name …
=> fix(cd): fix grepping the last release

Cargo.toml
This PR updates termion to its latest version. There is only one breaking change https://gitlab.redox-os.org/redox-os/termion#200-to-300-guide.
We don't really use this but our users do in when initializing the terminal. I'm not sure then if this is a breaking change. I'd say no because users can probably still specify termion 2 right?
=> chore(deps): update termion to v3.0

.github/workflows/check-pr.yml
We sometimes forget to check for commit signature and are only reminded at the time of merging.
We also sometime forget to link to relevant documentation and whatnot.
This adds friction to new contributors and some redundant work for us.
I propose to use [this action](https://github.com/marketplace/actions/check-signed-commits-in-pr) to post a comment on PRs with unsigned commits. Contributors will be pinged when pushing even if no one is around and can work on that.
Let me know your thoughts and good resources to link in the comment.
~~I'll put an unsigned commit on this PR so we can see what it looks like (I'll rebase once this is approved).~~
Pipelines take the workflow from main so I guess we'll hope and see ...
=> chore: add comment on PRs with unsigned commits

.github/workflows/check-pr.yml
Follow up to https://github.com/ratatui-org/ratatui/pull/768
Checked here https://github.com/Valentin271/ratatui/pull/1
My guess is job-local permissions overwrite workflow permissions instead of merging. I couldn't find the official info in the doc.
=> fix: fix PR write permission to upload unsigned commit comment

src/widgets/list.rs
A follow-up from https://github.com/ratatui-org/ratatui/pull/755, allowing any iterator whose item is convertible into `ListItem` to be collected into a `List`.
=> feat(widgets): Collect iterator of `ListItem` into `List`

examples/table.rs, examples/table.tape, src/widgets/table/table.rs
This allows for multi-line symbols to be used as the highlight symbol.
```rust
let table = Table::new(rows, widths)
.highlight_symbol(Text::from(vec![
"".into(),
" █ ".into(),
" █ ".into(),
"".into(),
]));
```
=> feat(table): accept Text for highlight_symbol

BREAKING-CHANGES.md, examples/demo/ui.rs, examples/tabs.rs, src/widgets/tabs.rs, tests/widgets_tabs.rs
A follow-up from https://github.com/ratatui-org/ratatui/pull/755, allowing any iterator whose item is convertible into `Line` to be collected into `Tabs`.
=> feat(widgets): Collect iterator of `Line` into `Tabs`

BREAKING-CHANGES.md, examples/demo2/tabs/recipe.rs, src/widgets/table/table.rs, tests/widgets_table.rs
A follow-up from https://github.com/ratatui-org/ratatui/pull/755, allowing any iterator whose item is convertible into `Row` to be collected into a `Table`.
=> feat(widgets): Collect iterator of `Row` into `Table`

src/style/color.rs
Convert a u32 in the format 0x00RRGGBB to a Color.
=> feat(color): add Color::from_u32 constructor

src/style.rs, src/style/palette.rs, src/style/palette/tailwind.rs
Enable the `tailwind` feature flag to use the colors from the Tailwind
CSS framework. The colors are available in the `style::tailwind` module.
See https://tailwindcss.com/docs/customizing-colors for more information
on Tailwind.
```rust
use ratatui::style::tailwind::SLATE;
Line::styled("Hello", SLATE.c500);
```
=> feat(style): add TailwindCSS colors

src/style/palette.rs, src/style/palette/material.rs
Enable the `material` feature flag to use the colors from the Material
design color scheme. This adds a dependency on the `matdesign-color`
crate. The colors are available in the `style::material` module.
See https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors
for more information.
```rust
use ratatui::style::material::BLUE_GRAY;
Line::styled("Hello", BLUE_GRAY.c500);
```
=> feat(style): add Material Design colors

examples/README.md
=> docs: GitHub admonition syntax for examples README.md

examples/scrollbar.rs
This has always been like that since scrollbar was introduced so the title was never displayed(?).
=> fix(examples/scrollbar): title wasn't displayed because of background reset

src/widgets/table/table.rs
Fixed a small typo I found while reading your otherwise excellent docs.
=> docs: fix typo in Table widget description

Cargo.toml, examples/constraints.rs, examples/constraints.tape, examples/layout.rs, src/layout/constraint.rs, src/layout/layout.rs, src/widgets/chart.rs
This PR adds `Constraint::Fixed(x)` and `Constraint::Proportional(x)`. I've also added a simple example showing how some constraints interact with each other:
This PR also deprecates the unused `Constraint::apply` method.
This PR allows users to create more advanced layouts. For example, we can force column spacing in the table layouts with a `Fixed` constraint.
Without this PR:
With this PR:
In the second screenshot, there's a column spacing after the description column. This does not exist in the first screenshot.
I've also improved the docstring for the enum variants (with some static ascii illustrations from the example):
**Additional information**
Currently we have the following levels of priorities:
- `Constraint::Min(lower)` and `Constraint::Max(upper)`
- `segment >= lower` and …
=> feat: Add `Constraint::Fixed(x)` and `Constraint::Proportional(x)`

cliff.toml
Fixes: https://github.com/orhun/git-cliff/issues/297
Any line in the commit that ends in a colon gets truncated by git-cliff in the default configuration. This fixes that.
The following is the output of `git-cliff -u -o CHANGELOG.md` compared before and after this change.
`````diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 8f0082ca..1028e066 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -172,6 +172,10 @@ All notable changes to this project will be documented in this file.
- Adds missing docs
````
+  BREAKING CHANGE:
+  `Line::style` is now a field of `Line` instead of being
+  stored in each `Span`.
+
- [bbf2f90](https://github.com/ratatui-org/ratatui/commit/bbf2f906fbe7e593fdeb5dd7530d3479788f77a5)
*(rect.rs)* Implement Rows and Columns iterators in Rect …
=> chore: add commit footers to git-cliff config

Cargo.toml, examples/flex.rs, examples/flex.tape
On a standard size terminal, flex example is cut off which is a shame because of how great it is.
I added scroll to the example.
`constraints` will also need that but I first want to validate this kind of janky implementation.
=> refactor(example): add scroll to flex example

src/layout/layout.rs
These fails seem to fail on occasion, locally and on CI.
This issue will be revisited in the PR on constraint weights: https://github.com/ratatui-org/ratatui/pull/788
=> chore(layout): comment tests that may fail on occasion

examples/constraints.rs, examples/flex.rs
This was causing very bad performances especially on scrolling and also some flickering (which is a bug anyway). It's also a good usage demonstration.
<details><summary>Details</summary>
<p>
To show it works I added logging in `Layout::split`:
```diff
diff --git a/src/layout/layout.rs b/src/layout/layout.rs
index b2e1f72..ebcce85 100644
--- a/src/layout/layout.rs
+++ b/src/layout/layout.rs
@@ -410,6 +410,7 @@ impl Layout {
/// assert_eq!(layout[..], [Rect::new(0, 0, 3, 2), Rect::new(3, 0, 6, 2)]);
/// ```
pub fn split(&self, area: Rect) -> Rc<[Rect]> {
+        eprintln!("split");
LAYOUT_CACHE.with(|c| {
c.get_or_init(|| {
RefCell::new(LruCache::new(
@@ -418,6 +419,7 @@ impl Layout {
})
.borrow_mut()
.get_or_insert((area, self.clone()), || {
+                eprintln!("calculated"); …
=> fix(example): increase layout cache size

src/layout/layout.rs
When there's just one element, `SpaceBetween` should do the same thing as `Stretch`.
=> fix: make SpaceBetween with one element Stretch 🐛

src/widgets/calendar.rs
`CalendarEventStore::today()` panics if the system's UTC offset cannot be determined. In this circumstance, it's better to use `now_utc` instead.
=> fix(calendar): CalendarEventStore panic

examples/constraints.rs, examples/constraints.tape, examples/flex.rs
This PR is a follow up to https://github.com/ratatui-org/ratatui/pull/811.
It improves the UI of the layouts by
- thoughtful accessible color that represent priority in constraints resolving
- using QUADRANT_OUTSIDE symbol set for block rendering
- adding a scrollbar
- panic handling
- refactoring for readability
to name a few. Here are some example gifs of the outcome:
=> refactor(example): improve constraints and flex examples

src/text/line.rs, src/text/span.rs, src/text/text.rs
Issue: https://github.com/ratatui-org/ratatui/issues/816
This PR adds:
`std::fmt::Display` for `Text`, `Line`, and `Span` structs.
Display implementation displays actual content while ignoring style.
=> feat: implement Display for Text, Line, Span

src/layout/layout.rs
This PR fixes a bug with layouts when using spacing on proportional constraints.
=> fix: bug with flex stretch with spacing and proportional constraints 

src/symbols.rs
This PR adds the [`McGugan`](https://www.willmcgugan.com/blog/tech/post/ceo-just-wants-to-draw-boxes/) border set, which allows for tighter borders.
For example, with the `flex` example you can get this effect (top is mcgugan wide, bottom is mcgugan tall):
As of this PR, `MCGUGAN_WIDE` has to be styled manually, like so:
```rust
let main_color = color_for_constraint(*constraint);
let cell = buf.get_mut(block.x, block.y + 1);
cell.set_style(Style::reset().fg(main_color).reversed());
let cell = buf.get_mut(block.x, block.y + 2);
cell.set_style(Style::reset().fg(main_color).reversed());
let cell = buf.get_mut(block.x + block.width.saturating_sub(1), block.y + 1);
cell.set_style(Style::reset().fg(main_color).reversed());
let cell = buf.get_mut(block.x + block.width.saturating_sub(1), block.y …
```
=> feat: Add one eighth inner and outer border set ✨

src/widgets/table/table.rs, tests/state_serde.rs, tests/widgets_table.rs
This uses the new `spacing` feature of the `Layout` struct to allocate columns spacing in the `Table` widget.
This changes the behavior of the table column layout in the following ways:
1. Selection width is always allocated.
- if a user does not want a selection width ever they should use `HighlightSpacing::Never`
2. Column spacing is prioritized over other constraints
- if a user does not want column spacing, they should use `Table::new(...).column_spacing(0)`
=> feat: Table column calculation uses layout spacing ✨

src/widgets/block.rs
Issue: https://github.com/ratatui-org/ratatui/issues/798
This PR adds:
`pretty`, `left`, `right`, `top`, and `bottom` constructors for Padding struct.
`pretty` implements this note
```
/// **NOTE**: Terminal cells are often taller than they are wide, so to make horizontal and vertical
/// padding seem equal, doubling the horizontal padding is usually pretty good.
```
Modified current test functions to make them also test new constructors.
=> feat(Padding): add new constructors for padding

examples/list.rs, src/text/line.rs, src/text/span.rs, src/text/text.rs, src/widgets/list.rs, src/widgets/table/cell.rs, src/widgets/table/table.rs
Fixes #758, fixes #801
This PR adds:
- `style` and `alignment` to `Text`
- impl `Widget` for `Text`
- replace `Text` manual draw to call for Widget impl
All places that use `Text` have been updated and support its new features expect paragraph which still has a custom implementation.
---
I fixed some docs in line. I also refactored the truncation tests for line and span to clarify them because line wasn't truncating correctly (also fixed that).
=> feat(text): add style and alignment

README.md, examples/README.md, src/backend.rs, src/backend/crossterm.rs, src/backend/termwiz.rs, src/layout/layout.rs, src/lib.rs, src/widgets/list.rs, src/widgets/table/table.rs, src/widgets/table/table_state.rs
Examples often take advantage of unreleased API changes, which makes them not copy-paste friendly.
=> docs(examples): document incompatible examples better

examples/list.rs, src/widgets/list.rs
The current `List` example will unselect and reset the position of a list.
This PR will save the last selected item, and updates `List` to honor its offset, preventing the list from resetting when the user `unselect()`s a `StatefulList`.
=> fix(list): Modify List and List example to support saving offsets.

src/symbols.rs
Adds `PROPORTIONAL_WIDE` and `PROPORTIONAL_TALL` border sets.
`symbols::border::PROPORTIONAL_WIDE`
```
▄▄▄▄
█xx█
█xx█
▀▀▀▀
```
`symbols::border::PROPORTIONAL_TALL`
```
█▀▀█
█xx█
█xx█
█▄▄█
```
Fixes: https://github.com/ratatui-org/ratatui/issues/834
=> feat(symbols): add wide and tall proportional border set

examples/README.md, examples/table.rs, examples/table.tape
Issue: https://github.com/ratatui-org/ratatui/issues/800
This PR adds:
for table.rs
- scrollbar to the table
- colors changed to style::palette::material::AccentedPalette
- now colors can be changed with keys (l or →) for the next color, (h or ←) for the previous color
- added a footer for key info
for table.tape
- typing speed changed to 0.75s from 0.5s
- screen size changed to 1600x864 from 1200x800
- pushed keys changed to show the current example better
I'll push the new GIF to the images branch. Edit: https://github.com/ratatui-org/ratatui/pull/841
=> feat: update table example and table.tape

Cargo.toml, src/buffer/buffer.rs, src/buffer/cell.rs
ratatui allocates one `String` buffer for each `buffer::Cell`. `char` is not sufficient since one character can consist of multiple code points. However, in almost all cases the cells have a single code point. It means that ratatui allocates many small heap memories (~16 Bytes/cell) only for the rare cases.
Allocation on heap is slower than allocation on stack so moving these allocations to stack can improve performance of allocating `buffer::Buffer`.
To archive this, a small string optimization (SSO) is available in general (which is adopted by C++'s `std::string`). Fortunately, [compact_str](https://crates.io/crates/compact_str) crate is a solid implementation of SSO. It provides a drop in replacement of standard `String` so we can use it with very small changes (as diffs of this PR …
=> perf(buffer)!: apply SSO technique to text buffer in `buffer::Cell`

src/layout/layout.rs
This is a somewhat arbitrary size for the layout cache based on adding
the columns and rows on my laptop's terminal (171+51 = 222) and doubling
it for good measure and then adding a bit more to make it a round
number. This gives enough entries to store a layout for every row and
every column, twice over, which should be enough for most apps. For
those that need more, the cache size can be set with
`Layout::init_cache()`.
Fixes: https://github.com/ratatui-org/ratatui/issues/820
=> feat(layout): increase default cache size to 500

src/widgets/table/table.rs
Issue: https://github.com/ratatui-org/ratatui/issues/835
This PR adds:
for table
- Added new flex method with flex field
- Changed segment_size method to use flex method
- Deprecated segment_size method and removed segment_size field
- Updated documentation
- modified tests to use flex instead of segment_size except for one test.
-test `fn underconstrained_segment_size()` still uses segment_size to test if it still works.
=> feat(table): deprecate SegmentSize on table

src/text/text.rs
Issue: https://github.com/ratatui-org/ratatui/issues/854
This PR adds:
An overview of the relevant methods under `Constructor Methods`, `Setter Methods`, and `Other Methods` subtitles.
=> docs(Text): add overview of the relevant methods

examples/tabs.rs, examples/tabs.tape
Issue: https://github.com/ratatui-org/ratatui/issues/846, https://github.com/ratatui-org/ratatui/issues/819
This PR adds:
for tabs.rs
- general refactoring on code
- subjectively better looking front
- add tailwind colors
for tabs.tape
- change to get better output from the new code
Here is the new output:
=> docs(examples): update tabs example and tabs.tape

examples/list.rs, examples/list.tape
Issue: https://github.com/ratatui-org/ratatui/issues/846
This PR adds:
for list.rs
- subjectively better-looking front
- change list example to a todo list example
- status of a TODO can be changed, further info can be seen under the list.
for list.tape
- change to get better output from the new code
Here is the new output:
=> docs(examples): update list example and list.tape

examples/colors_rgb.rs, examples/demo2/colors.rs, src/layout/layout.rs, src/prelude.rs, src/terminal/frame.rs, src/text/line.rs, src/text/span.rs, src/text/text.rs, src/widgets.rs, src/widgets/barchart.rs, src/widgets/barchart/bar.rs, src/widgets/barchart/bar_group.rs, src/widgets/block.rs, src/widgets/calendar.rs, src/widgets/canvas.rs, src/widgets/canvas/line.rs, src/widgets/canvas/map.rs, src/widgets/canvas/rectangle.rs, src/widgets/chart.rs, src/widgets/clear.rs, src/widgets/gauge.rs, src/widgets/list.rs, src/widgets/paragraph.rs, src/widgets/sparkline.rs, src/widgets/table/cell.rs, src/widgets/table/table.rs, src/widgets/tabs.rs, tests/widgets_calendar.rs, tests/widgets_chart.rs
Many widgets can be rendered without changing their state.
This commit implements The `Widget` trait for references to
widgets and changes their implementations to be immutable.
This allows us to render widgets without consuming them by passing a ref
to the widget when calling `Frame::render_widget()`.
```rust
// this might be stored in a struct
let paragraph = Paragraph::new("Hello world!");
let [left, right] = area.split(&Layout::horizontal([20, 20]));
frame.render_widget(&paragraph, left);
frame.render_widget(&paragraph, right); // we can reuse the widget
```
Implemented for all widgets except BarChart (which has an implementation that
modifies the internal state and requires a rewrite to fix.
Other widgets will be implemented in follow up commits.
Fixes: …
=> feat(widgets): implement Widget for Widget refs

CONTRIBUTING.md
Removes the part about squashing commits from the CONTRIBUTING file.
We no longer require that because github squashes commits when merging. This will cleanup the CONTRIBUTING file a bit which is already quite dense.
=> chore(CONTRIBUTING): remove part about squashing commits

examples/constraints.rs, examples/flex.rs, examples/layout.rs, src/layout/constraint.rs, src/layout/flex.rs, src/layout/layout.rs, src/widgets/calendar.rs, src/widgets/table/table.rs
`Constraint::Fill` is a more intuitive name for the behavior, and it is shorter.
Resolves #859
=> feat(constraints): Rename `Constraint::Proportional` to `Constraint::Fill`

.github/workflows/ci.yml
Tested with https://github.com/ratatui-org/ratatui-macros/blob/main/.github/workflows/ci.yml
=> chore: cache dependencies in the CI workflow to speed up builds

examples/flex.rs, src/layout/layout.rs, src/widgets/table/table.rs
This PR implements user provided spacing gaps for `SpaceAround` and `SpaceBetween`.
https://github.com/ratatui-org/ratatui/assets/1813121/2e260708-e8a7-48ef-aec7-9cf84b655e91
Now user provided spacing gaps always take priority in all `Flex` modes.
=> feat: Make spacing work in `Flex::SpaceAround` and `Flex::SpaceBetween`

Cargo.toml, examples/constraint-explorer.rs
Here's a constraint explorer demo put together with @joshka 
https://github.com/ratatui-org/ratatui/assets/1813121/08d7d8f6-d013-44b4-8331-f4eee3589cce
It allows users to interactive explore how the constraints behave with respect to each other and compare that across flex modes. It allows users to swap constraints out for other constraints, increment or decrement the values, add and remove constraints, and add spacing
It is also a good example for how to structure a simple TUI with several Ratatui code patterns that are useful for refactoring.
Fixes: https://github.com/ratatui-org/ratatui/issues/792
=> feat: Constraint Explorer example

src/buffer/buffer.rs, src/text/line.rs, src/widgets/reflow.rs
This allows iterating over the `Span`s of a line using `for` loops and
other iterator methods.
- add `iter` and `iter_mut` methods to `Line`
- implement `IntoIterator` for `Line`, `&Line`, and `&mut Line` traits
- update call sites to iterate over `Line` rather than `Line::spans`
=> feat(line): implement iterators for Line

examples/constraint-explorer.rs
With this PR the constraint explorer demo only shows space constrained UIs instead:
Smallest (15 row height):
Small (20 row height):
Medium (30 row height):
Full (40 row height):
=> feat: show space constrained UIs conditionally

src/text/text.rs, src/widgets/paragraph.rs, src/widgets/reflow.rs
This allows iterating over the `Lines`s of a text using `for` loops and
other iterator methods.
- add `iter` and `iter_mut` methods to `Text`
- implement `IntoIterator` for `Text`, `&Text`, and `&mut Text` traits
- update call sites to iterate over `Text` rather than `Text::lines`
=> feat(text): implement iterators for Text

src/buffer/buffer.rs, src/widgets/canvas.rs, src/widgets/scrollbar.rs, tests/state_serde.rs, tests/widgets_chart.rs
This can make it easier to use `Buffer::with_lines` with iterators that
don't necessarily produce a `Vec`. For example, this allows using
`Buffer::with_lines` with `&[&str]` directly, without having to call
`collect` on it first.
=> chore: allow Buffer::with_lines to accept IntoIterator

examples/barchart.rs, examples/block.rs, examples/canvas.rs, examples/chart.rs, examples/colors_rgb.rs, examples/constraint-explorer.rs, examples/constraints.rs, examples/custom_widget.rs, examples/demo2/app.rs, examples/demo2/destroy.rs, examples/demo2/tabs/about.rs, examples/demo2/tabs/email.rs, examples/demo2/tabs/recipe.rs, examples/demo2/tabs/traceroute.rs, examples/demo2/tabs/weather.rs, examples/docsrs.rs, examples/flex.rs, examples/gauge.rs, examples/inline.rs, examples/layout.rs, examples/list.rs, examples/modifiers.rs, examples/popup.rs, examples/tabs.rs, examples/user_input.rs, src/layout/layout.rs, src/layout/rect.rs, src/widgets/calendar.rs, src/widgets/chart.rs, src/widgets/table/table.rs
In a recent commit we added Rec::split, but this feels more ergonomic as
Layout::areas. We also add Layout::spacers to get the spacers between
the areas.
=> feat: replace Rect::split with Layout::areas and spacers

Cargo.toml, src/prelude.rs, src/terminal/frame.rs, src/text/line.rs, src/text/span.rs, src/text/text.rs, src/widgets.rs, src/widgets/barchart.rs, src/widgets/block.rs, src/widgets/calendar.rs, src/widgets/canvas.rs, src/widgets/chart.rs, src/widgets/clear.rs, src/widgets/gauge.rs, src/widgets/list.rs, src/widgets/paragraph.rs, src/widgets/sparkline.rs, src/widgets/table/table.rs, src/widgets/tabs.rs
The Widget trait consumes self, which makes it impossible to use in a
boxed context. Previously we implemented the Widget trait for &T, but
this was not enough to render a boxed widget. We now have a new trait
called `WidgetRef` that allows rendering a widget by reference. This
trait is useful when you want to store a reference to one or more
widgets and render them later. Additionaly this makes it possible to
render boxed widgets where the type is not known at compile time (e.g.
in a composite layout with multiple panes of different types).
This change also adds a new trait called `StatefulWidgetRef` which is
the stateful equivalent of `WidgetRef`.
Both new traits are gated behind the `unstable-widget-ref` feature flag
as we may change the exact name / approach a little on this based on …
=> feat: add WidgetRef and StatefulWidgetRef traits

src/widgets.rs, src/widgets/barchart.rs, src/widgets/block.rs, src/widgets/canvas.rs, src/widgets/canvas/circle.rs, src/widgets/canvas/line.rs, src/widgets/canvas/map.rs, src/widgets/canvas/points.rs, src/widgets/canvas/rectangle.rs, src/widgets/chart.rs, src/widgets/gauge.rs, src/widgets/list.rs, src/widgets/scrollbar.rs, src/widgets/sparkline.rs, src/widgets/table.rs, src/widgets/tabs.rs
Document the whole `canvas` module. With this, the whole `widgets` module is documented.
This is also a first step to https://github.com/ratatui-org/ratatui/issues/693
=> docs(canvas): add documentation to canvas module

bacon.toml, src/buffer/buffer.rs
Fixes a regression in 0.26 where buffer::set_line was no longer setting
the style. This was due to the new style field on Line instead of being
stored only in the spans.
Also adds a configuration for just running unit tests to bacon.toml.
=> fix: ensure that buffer::set_line sets the line style

src/layout/rect.rs, src/layout/rect/iter.rs
Useful for performing some action on all the cells in a particular area. E.g.,
```rust
fn render(area: Rect, buf: &mut Buffer) {
for position in area.positions() {
buf.get_mut(position.x, position.y).set_symbol("x");
}
}
```
=> feat(rect): add Rect::positions iterator

src/widgets/paragraph.rs
rendering a `Paragraph` with a `Line::styled` ignores the style, but using styled spans with a `Line::default().spans(vec![Span::styled])` works just fine.
the issue seems to be, that the paragraph tries to render the `styled_graphemes` of the `Span`s instead of the `Line` directly
<details>
<summary>repro of the problem</summary>
```rs
fn ui(frame: &mut Frame) {
let l1 = Line::styled("should be bold", Style::default().bold());
let l2 = Line::styled("should be colorful", Style::default().cyan());
let l3 = Line::styled("should be dim", Style::default().dim());
let lp = Line::default();
let s1 = vec![Span::styled("but it works with spans", Style::default().cyan())];
let ls = Line::default().spans(s1);
let block = Block::default()
.borders(Borders::ALL)
.padding(Padding::new(4, 4, 2, 2)); …
```
=> fix(line): render Line::styled correctly inside a paragraph

.github/workflows/check-pr.yml
We can consider reverting this commit once this PR is merged: https://github.com/1Password/check-signed-commits-action/pull/9
=> chore: Remove github action bot that makes comments nudging commit signing

src/widgets/block.rs, tests/widgets_block.rs
- Simplified implementation of the rendering for block.
- Introduces a subtle rendering change where centered titles that are
odd in length will now be rendered one character to the left compared
to before. This aligns with other places that we render centered text
and is a more consistent behavior. See
https://github.com/ratatui-org/ratatui/pull/807#discussion_r1455645954
for another example of this.
Fixes: 929
fix: tests
=> fix(block): fix crash on empty right aligned title

src/widgets/block.rs, src/widgets/block/title.rs
This adds the ability to add titles to the top and bottom of a block
without having to use the `Title` struct (which will be removed in a
future release - likely v0.28.0).
Fixes a subtle bug if the title was created from a right aligned Line
and was also right aligned. The title would be rendered one cell too far
to the right.
```rust
Block::bordered()
.title_top(Line::raw("A").left_aligned())
.title_top(Line::raw("B").centered())
.title_top(Line::raw("C").right_aligned())
.title_bottom(Line::raw("D").left_aligned())
.title_bottom(Line::raw("E").centered())
.title_bottom(Line::raw("F").right_aligned())
.render(buffer.area, &mut buffer);
// renders
"┌A─────B─────C┐",
"│             │",
"└D─────E─────F┘",
```
Addresses part of https://github.com/ratatui-org/ratatui/issues/738
=> feat: add Block::title_top and Block::title_top_bottom

src/layout.rs, src/layout/position.rs, src/layout/rect.rs, src/layout/rect/iter.rs, src/layout/size.rs, src/widgets/canvas/line.rs
The layout can often contain things that are already known at compile time which speeds up things on runtime. Especially as render is called a lot.
With 0.26.0 the `Rect::contains` method is now accepting a Position. While `contains` is `const`, `Position::new` is not which triggered the creation of this PR. I switched to `Position { x, y }`, but the compiler should be able to do the same in `const` with `::new()`.
I added the lint to the layout module, but I don't really know what other plans of this project are in regard to configuring lints. I could also just remove the lint there, but mistakes like the current one will happen again as the code uses a lot of `const` already. Do you have other thoughts on how to configure the lints best?
I observed the …
=> perf(layout): const functions

src/widgets.rs
Currently, `f.render_widget("hello world".bold(), area)` works but `f.render_widget("hello world", area)` doesn't. This PR changes that my implementing `Widget` for `&str` and `String`. This makes it easier to render strings with no styles as widgets.
Example usage:
```rust
terminal.draw(|f| f.render_widget("Hello World!", f.size()))?;
```
=> feat: impl Widget for `&str` and `String`

.github/workflows/ci.yml
This removes conventional commit check for PRs.
Since we use the PR title and description this is useless. It fails a lot of time and we ignore it.
IMPORTANT NOTE: This does **not** mean Ratatui abandons conventional commits. This only relates to commits in PRs.
=> chore: remove conventional commit check for PR

src/widgets/scrollbar.rs
When displaying somewhat-long lists, the `Scrollbar` widget might not display a single thumb character, and only the track will be visible. Here are some GIFs showing the issue:
The code to reproduce this issue was based off the scrollbar example and can be found in [this pastebin](https://pastebin.com/x4DzthcF).
I fixed this issue by converting the logic in the `part_lengths` function to use integer calculations instead of floating-point (the only reason for the use of floating point seemed to be the rounding after division, which can be done in integers by replacing `(a / b).round() as usize` with `(a + b/2) / b`) and then doing a bit of clamping. The result of the previous test is as shown in these GIFs:
=> fix: scrollbar thumb not visible on long lists

examples/scrollbar.rs, src/widgets/scrollbar.rs
While doing other things in the Scrollbar widget I used a bunch of lints to improve things. A bunch of `const fn` allow for more performance and `Default` now uses the `const` new implementations.
For simplicity reasons I created `Scrollbar::new_with_symbols` for a cleaner `new` without calling `orientation()` on new.
=> perf(scrollbar): const creation

src/widgets/scrollbar.rs
Fixes a panic when `track_length - 1` is used. (clamp panics on `-1.0` being smaller than `0.0`)
https://github.com/ratatui-org/ratatui/blob/d0067c8815d5244d319934d58a9366c8ad36b3e5/src/widgets/scrollbar.rs#L520
=> fix(scrollbar): dont render on 0 length track

src/widgets/list.rs, tests/state_serde.rs
This PR introduces scroll padding, which allows the api user to request that a certain number of ListItems be kept visible above and below the currently selected item while scrolling. 
It does this by adjusting the 'index_to_display' value in the List::get_item_bounds function. Reducing the provided padding value if the padding would push the selected item out of the renderable area or if there's not enough room for the requested amount of padding, and correctly handling ListItems of inconsistent sizes. 
I have stored the 'padding' value in the ListState object. Using serde(default) on the parameter to avoid creating a breaking change in relation to user deserialization of existing data. 
I believe the ListState object is the correct place to put this, as if we're not rendering a stateful …
=> feat(list): Add Scroll Padding to Lists

src/text/line.rs, src/text/span.rs, src/text/text.rs
This adds `FromIterator` impls for `Line` and `Text` that allow creating
`Line` and `Text` instances from iterators of `Span` and `Line`
instances, respectively.
```rust
let line = Line::from_iter(vec!["Hello".blue(), " world!".green()]);
let line: Line = iter::once("Hello".blue())
.chain(iter::once(" world!".green()))
.collect();
let text = Text::from_iter(vec!["The first line", "The second line"]);
let text: Text = iter::once("The first line")
.chain(iter::once("The second line"))
.collect();
```
=> feat(text): add `FromIterator` impls for `Line` and `Text`

src/text/line.rs, src/text/span.rs, src/text/text.rs
This adds `FromIterator` impls for `Line` and `Text` that allow creating
`Line` and `Text` instances from iterators of `Span` and `Line`
instances, respectively.
```rust
let line = Line::from_iter(vec!["Hello".blue(), " world!".green()]);
let line: Line = iter::once("Hello".blue())
.chain(iter::once(" world!".green()))
.collect();
let text = Text::from_iter(vec!["The first line", "The second line"]);
let text: Text = iter::once("The first line")
.chain(iter::once("The second line"))
.collect();
```
=> feat(line): impl Styled for Line

src/buffer/cell.rs
Some minor find when messing around trying to `const` all the things.
While `reset()` and `default()` can not be `const` it's still a benefit when their contents are.
=> perf(cell): use const CompactString::new_inline

src/backend/crossterm.rs, src/backend/termion.rs, src/widgets/canvas.rs, src/widgets/chart.rs
See #978
Also remove other derives. They are unused and just slow down compilation.
=> refactor: remove pointless default on internal structs

src/widgets/paragraph.rs
Paragraph was ignoring the new style field on Text added in 0.26.0
Fixes: https://github.com/ratatui-org/ratatui/issues/990
=> fix: ensure that paragraph correctly renders styled text

examples/constraint-explorer.rs, src/text/span.rs
This deprecates the old methods hinting the new name.
With the Rust method naming conventions this method is an into method consuming the Span. Therefore, it's more consistent to name it into instead of to.
=> refactor(span): rename to_aligned_line into into_aligned_line

src/text/line.rs, src/text/span.rs, src/text/text.rs
Previously it was possible to cause a panic when rendering to an area
outside of the buffer bounds. Instead this now correctly renders nothing
to the buffer.
=> fix(text): fix panic when rendering out of bounds

src/widgets.rs, src/widgets/calendar.rs, src/widgets/chart.rs, src/widgets/list.rs
This PR fixes the typos found with [`cargo-spellcheck`](https://github.com/drahnr/cargo-spellcheck)
I originally wanted to integrate this tool into our CI but there are _a lot_ of false positives so I went ahead and fixed the appropriate ones with hand.
=> chore(docs): fix typos in crate documentation

src/text/line.rs, src/text/span.rs, src/text/text.rs
Adds the following methods to the `Text` and `Line` structs:
- Text::push_line
- Text::push_span
- Line::push_span
This allows for adding lines and spans to a text object without having
to call methods on the fields directly, which is usefult for incremental
construction of text objects.
=> feat(text): add push methods for text and line

BREAKING-CHANGES.md
=> docs(breaking-changes): typos and markdownlint

src/backend/crossterm.rs, src/backend/termion.rs, src/backend/termwiz.rs, src/backend/test.rs
Simplifies the code, logic stays exactly the same.
=> refactor: simplify to io::Result

examples/demo2/app.rs, examples/demo2/main.rs
Use `App::default()` directly.
=> refactor(example): remove pointless new method

Cargo.toml
Add the package categories field in Cargo.toml, with value `["command-line-interface"]`. This fixes the (currently non-default) clippy cargo group lint [`clippy::cargo_common_metadata`](https://rust-lang.github.io/rust-clippy/master/index.html#/cargo_common_metadata).
As per discussion in [Cargo package categories suggestions](https://github.com/ratatui-org/ratatui/discussions/1034), this lint is not suggested to be run by default in CI, but rather as an occasional one-off as part of the larger [`clippy::cargo`](https://doc.rust-lang.org/stable/clippy/lints.html#cargo) lint group.
=> chore: Add package categories field

Cargo.toml, clippy.toml
Followup to https://github.com/ratatui-org/ratatui/pull/1035 and
https://github.com/ratatui-org/ratatui/discussions/1034
It's reasonable to enable this and deal with breakage by fixing any
specific issues that arise.
=> build: add clippy::cargo lint

benches/block.rs, src/buffer/buffer.rs
The `vec![]` macro is highly optimized by the Rust team and shorter. Don't do it manually.
This change is mainly cleaner code. The only production code that uses this is `Terminal::with_options` and `Terminal::insert_before` so it's not performance relevant on every render.
=> perf(buffer): simplify Buffer::filled with macro

src/widgets/calendar.rs
There are likely many more places where `Style::default()` → `Style::new()` allows for `const`.
Also, do the comparison without `as u8`. Stays the same at runtime and is cleaner code.
=> perf(calendar): use const fn

src/widgets/table/table_state.rs
Personally I think there should be either `TableState::default()` or `TableState::new()` but not both (#978). Here we have both, so at least allow for `const fn new`.
=> perf(table): const TableState::new

src/widgets/canvas/map.rs, src/widgets/canvas/world.rs
I suspect this was done `static` instead of `const` based on C/C++. The usage stays the same, I don't know any reason why it should stay `static`. Or am I overlooking something? But `MapResolution::data` can be `const` with this change.
=> perf(canvas): const world data

src/buffer/buffer.rs
The caller put in the wrong x/y -> the caller is the cause.
In the future get and get_mut should return Option but thats a bigger change.
=> feat(buffer): track_caller for index_of

README.md
The badges in the readme were all the default theme. Giving them prettier colors that match the terminal gif is better. I've used the colors from the VHS repo.
```json
{
"name": "Aardvark Blue",
"black": "#191919",
"red": "#aa342e",
"green": "#4b8c0f",
"yellow": "#dbba00",
"blue": "#1370d3",
"magenta": "#c43ac3",
"cyan": "#008eb0",
"white": "#bebebe",
"brightBlack": "#454545",
"brightRed": "#f05b50",
"brightGreen": "#95dc55",
"brightYellow": "#ffe763",
"brightBlue": "#60a4ec",
"brightMagenta": "#e26be2",
"brightCyan": "#60b6cb",
"brightWhite": "#f7f7f7",
"background": "#102040",
"foreground": "#dddddd",
"cursor": "#007acc",
"selection": "#bfdbfe",
"meta": {
"isDark": true,
"credits": null
}
},
``` 
The dependencies badge couldn't unfortunately be themed
=> chore(README): badges now are in the terminal theme

examples/constraints.rs
Add check for `KeyEventKind::Press` to constraints example's event handler to eliminate double keys
on Windows.
Fixes: #1062
=> fix(examples): fix key handling in constraints

examples/user_input.rs
This is the proposed solution for issue #1068. It solves the bug in the user_input example with multi-byte UTF-8 characters as input.
=> fix(examples): changed user_input example to work with multi-byte unicode chars

src/backend/crossterm.rs
Use Crossterm SetColors instead of SetForegroundColor and
SetBackgroundColor.
In https://github.com/crossterm-rs/crossterm/pull/879 I changed the
SetColors command to write both colors at once with a single write
instead of multiple writes that more bytes. This led to a 15-25% fps
increase when testing the colors_rgb example on iTerm2 on an M2 Macbook
Pro.
=> perf(crossterm): Speed up combined fg and bg color changes by up to 20%

.github/CODEOWNERS
As per suggestion in https://github.com/ratatui-org/ratatui/pull/1067#issuecomment-2079766990
It's good for historical purposes!
=> docs(github): update code owners about past maintainers

src/widgets/reflow.rs
Handle ZWSP as a possible wrapping point.
See https://github.com/ratatui-org/ratatui/issues/293#issuecomment-2080824898 for more details.
=> fix(reflow): handle ZWSP

src/widgets/scrollbar.rs
Updates the `Scrollbar` docs [as discussed](https://discord.com/channels/1070692720437383208/1072907135664529508/1235032608283557918) on the Discord.
Please let me know if I did anything wrong, and also happy to iterate on the docs change itself. Just added something small and quick for now.
=> docs: add note about scrollbar state content length

clippy.toml
Crossterm brings in multiple versions of the same dep
=> chore: fixup cargo lint for windows targets

src/buffer/buffer.rs
Simplifies the logic. Instead of trying to figure out the `max_offset` in a seemingly complicated way keep the `remaining_width` and count down as long as there are characters left. This is way easier to understand for me what is going on.
---
Part of the improvements I did with #1049. As this is without `_opt` methods this can still panic (same as current code on wrong input).
=> refactor(buffer): simplify set_stringn logic

src/backend/termwiz.rs
underline-color was incorrectly spelt as underline_color
=> fix: correct feature flag typo for termwiz

src/backend/test.rs, src/buffer/buffer.rs, src/layout/constraint.rs, src/layout/margin.rs, src/style.rs, src/style/color.rs, src/text/line.rs, src/text/masked.rs, src/text/span.rs, src/text/text.rs, src/widgets/borders.rs, src/widgets/canvas.rs
Based on a [discussion](https://github.com/ratatui-org/ratatui/pull/1083#discussion_r1588466060) with @EdJoPaTo on a PR.
This is a small universal style change to avoid making this change a part of other PRs.
=> style: use std::fmt instead of importing Debug and Display

src/backend/termwiz.rs
Fixes code that doesn't compile in the termwiz tests when underline-color feature is enabled.
=> fix: termwiz underline color test

src/layout/rect.rs, src/widgets/block.rs
=> test(block): use rstest to simplify test cases

Cargo.toml, benches/line.rs, src/layout/rect.rs, src/text/line.rs, src/text/span.rs
- Rewrote the line / span rendering code to take into account how multi-byte / wide emoji characters are truncated when rendering into areas that cannot accommodate them in the available space
- Added comprehensive coverage over the edge cases
- Adds a benchmark to ensure perf
Fixes: https://github.com/ratatui-org/ratatui/issues/1032
=> fix: unicode truncation bug

BREAKING-CHANGES.md, src/style/stylize.rs
This PR makes `.bg(color)` generic accepting anything that can be converted into `Color`; similar to the `.fg(color)` method on the same trait
=> feat: Make Stylize's `.bg(color)` generic

src/buffer/buffer.rs
Fix panic in `Debug for Buffer` when `width == 0`.
Also corrects the output when symbols are overridden.
---
Let's do some final testing for #1007… test runner aborts on panic in panic handler. Nice. :ghost:
=> fix(buffer): fix Debug panic and fix formatting of overridden parts

BREAKING-CHANGES.md, src/style/stylize.rs
This reverts commit ec763af8512df731799c8f30c38c37252068a4c4 from #1099
=> chore: Revert "Make Stylize's `.bg(color)` generic"

Makefile.toml, src/backend/termwiz.rs
Ensures that we upload coverage details for the underline-color tests (at the expense of possible removing some coverage where the feature is not enabled). Given `underline-color` is a default feature this is sensible.
Also fixes up a small build warning that pops up when not building with the underline-color feature
=> build: add underline-color to all features flag in makefile

src/buffer/cell.rs, src/text/masked.rs, src/text/span.rs
This allows for `format!("{:>42})` formatting.
See https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.pad
---
I am not very attached to this. It feels more correct to reuse the inner Display implementation but we can also drop this. Main reason for this PR was to move it out of #1007
=> feat: use inner Display implementation

src/layout/layout.rs
Noticed we create an intermediate vec in `Layout::areas` and `Layout::spacers` but there's no need for one.
=> perf(layout): avoid allocating memory when using split ergonomic utils

clippy.toml, src/layout/rect.rs, src/widgets/gauge.rs
We need to make sure to not change existing methods without a notice. But at the same time this also finds public additions with mistakes before they are even released which is what I would like to have.
This renames a method and deprecated the old name hinting to a new name. Should this be mentioned somewhere, so it's added to the release notes? It's not breaking because the old method is still there.
=> refactor(clippy): enable breaking lint checks

Cargo.toml, src/terminal/frame.rs, src/widgets.rs
Fixes: https://github.com/ratatui-org/ratatui/issues/1109
=> fix: make cargo test --doc work with unstable-widget-ref examples

examples/demo2/destroy.rs, src/backend/test.rs, src/buffer/buffer.rs
Using reset is clearer to me what actually happens. On the other case a struct is created to override the old one completely which basically does the same in a less clear way.
=> refactor(cell): reset instead of applying default

Cargo.toml
Codegen units are optimized on their own. Per default bench / release have 16 codegen units. What ends up in a codeget unit is rather random and can influence a benchmark result as a code change can move stuff into a different codegen unit → prevent / allow LLVM optimizations unrelated to the actual change.
More details: https://doc.rust-lang.org/cargo/reference/profiles.html
=> build(bench): improve benchmark consistency

src/buffer/cell.rs
=> refactor(cell): must_use and simplify style()

examples/list.rs
Simplify the List example by removing lifetimes not strictly necessary to demonstrate how Ratatui lists work. Instead, the sample strings are copied into each `TodoItem`. To further simplify, I changed the code to use a new TodoItem::new function, rather than an implementation of the `From` trait.
Lifetimes are one of the more confusing things people learning Rust have to understand. The goal here is to remove that concern from the example. The `From` trait, also, is something a person new to Rust may not fully understand.
=> docs(examples): Remove lifetimes from the List example

src/widgets/barchart.rs, src/widgets/sparkline.rs
While looking through lints [`clippy::option_if_let_else`](https://rust-lang.github.io/rust-clippy/master/index.html#option_if_let_else) found these. Other findings are more complex so I skipped them.
=> refactor: simplify if let

Cargo.toml, src/style/color.rs, src/widgets/reflow.rs
<https://rust-lang.github.io/rust-clippy/master/index.html#string_slice>
=> fix: prevent panic from string_slice

src/style.rs, src/widgets/gauge.rs, src/widgets/scrollbar.rs, src/widgets/sparkline.rs
Replace `impl Default` by `#[derive(Default)]` when its implementation equals.
---
Funny finding, the default Canvas doesn't use the default Marker:
https://github.com/ratatui-org/ratatui/blob/4f7791079edd16b54dc8cdfc95bb72b282a09576/src/widgets/canvas.rs#L621
https://github.com/ratatui-org/ratatui/blob/4f7791079edd16b54dc8cdfc95bb72b282a09576/src/symbols.rs#L489-L492
=> refactor: dont manually impl Default for defaults

Cargo.toml, src/lib.rs
This also results in a more readable Cargo.toml as the locations of the things are more obvious now.
Includes rewording of the underline-color feature.
Logs of the errors: https://docs.rs/crate/ratatui/0.26.3/builds/1224962
Also see #989
=> docs: fix links on docs.rs

src/backend/test.rs, src/buffer/buffer.rs, src/buffer/cell.rs, src/text/line.rs, src/widgets/canvas.rs, src/widgets/sparkline.rs
This simplifies calls to `Buffer::filled` in tests.
=> feat(cell): add EMPTY and (const) new method

BREAKING-CHANGES.md, src/buffer/buffer.rs, src/text/line.rs, src/widgets/canvas.rs, src/widgets/sparkline.rs
This removes a clone from inside the method allowing the user to do it explicitly when needing.
BREAKING CHANGE: `Buffer::filled` moves the cell instead of taking a reference.
```diff
-Buffer::filled(area, &Cell::new("X"));
+Buffer::filled(area, Cell::new("X"));
```
---
https://github.com/ratatui-org/ratatui/pull/1143#issuecomment-2131247181
=> perf(buffer)!: filled moves the cell to be filled

Cargo.toml
semver breaking change in 0.1.13 <https://github.com/unicode-rs/unicode-width/issues/55>
=> fix: pin unicode-width crate to 0.1.13

Cargo.toml, src/buffer/buffer.rs, src/widgets/paragraph.rs, src/widgets/reflow.rs
unicode-width 0.1.13 changed the width of \u{1} from 0 to 1.
Our tests assumed that \u{1} had a width of 0, so this change replaces
the \u{1} character with \u{200B} (zero width space) in the tests.
Upstream issue (closed as won't fix):
https://github.com/unicode-rs/unicode-width/issues/55
=> fix: avoid unicode-width breaking change in tests

Cargo.toml, src/layout/layout.rs, src/style.rs, src/style/palette_conversion.rs, src/widgets/barchart/bar_group.rs
This is behind the "palette" feature flag.
```rust
use palette::{LinSrgb, Srgb};
use ratatui::style::Color;
let color = Color::from(Srgb::new(1.0f32, 0.0, 0.0));
let color = Color::from(LinSrgb::new(1.0f32, 0.0, 0.0));
```
=> feat(style): add conversions from the palette crate colors

src/buffer/cell.rs, src/text/span.rs
Zero-width characters at the start of a span are now rendered with the
subsequent character in the same cell. Zero-width characters in the
middle of a span are rendered at the end of the previous cell.
Fixes: https://github.com/ratatui-org/ratatui/issues/1160
=> fix(span): ensure that zero-width characters are rendered correctly

examples/demo/app.rs, src/layout/rect.rs, src/style/palette_conversion.rs
=> refactor(lint): fix new lint warnings

src/widgets.rs
Those two shouldn't write outside the given area I would think.
=> fix: render of &str and String doesn't respect area.width

src/widgets/table/table.rs
Fixes: <https://github.com/ratatui-org/ratatui/issues/1179>
=> fix(table): ensure render offset without selection properly

src/text/line.rs
`Line::from("a\nb")` now returns a line with two `Span`s instead of 1
Fixes: https://github.com/ratatui-org/ratatui/issues/1111
=> fix(line): remove newlines when converting strings to Lines

Cargo.toml, examples/tracing.rs, examples/vhs/tracing.tape
Add an example that demonstrates logging to a file for:
<https://forum.ratatui.rs/t/how-do-you-println-debug-your-tui-programs/66>
```shell
cargo run --example tracing
RUST_LOG=trace cargo run --example=tracing
cat tracing.log
```
=> feat(docs): add tracing example

BREAKING-CHANGES.md, examples/list.rs, src/widgets/list.rs, tests/widgets_list.rs
Also cleans up the list example significantly (see also
<https://github.com/ratatui-org/ratatui/issues/1157>)
Fixes: <https://github.com/ratatui-org/ratatui/pull/1159>
BREAKING CHANGE: The `List` widget now clamps the selected index to the
bounds of the list when navigating with `first`, `last`, `previous`, and
`next`, as well as when setting the index directly with `select`.
=> feat(list)!: add list navigation methods (first, last, previous, next)

src/widgets/table/table.rs, src/widgets/table/table_state.rs
Add select_previous, select_next, select_first & select_last to TableState
Used equivalent API as in ListState
=> feat(table): select first, last, etc to table state

src/text/grapheme.rs, src/widgets/reflow.rs
The `WordWrapper` implementation is a large and almost unreadable chunk of code, so I decided to do a ground-up cleaning.
Highlights and notes in no particular order:
- Before, due to extensive nesting and poor communication the control flow was foggy and mentally exhausting. Now the code is more clearly separated into a) emitting any currently cached lines (`self.wrapped_lines`) and b) processing the input iterator for any input to be wrapped and cached for step `a`
- I tried to invert and compact any larger if blocks, using let-else and labeled blocks. These features came in Rust 1.65 so they shouldn't affect our MSRV
- I attempted to rename some variables to more clearly signal intent, e.g. `unfinished_word` -> `pending_word`, `has_seen_non_whitespace` -> `non_whitespace_previous`
- …
=> refactor: simplify WordWrapper implementation

src/widgets/block.rs
Update block documentation with constructor methods and setter methods in the main doc comment Added an example for using it to surround widgets
Solves this: https://github.com/ratatui-org/ratatui/issues/914
=> docs(block): update block documentation

src/layout/constraint.rs
Quick fix for the documentation of the `from_fills` method. 
Should be uncontroversial
=> docs: Constraints::from_fills docs correction

examples/vhs/hyperlink.tape
Fix for the current tape for the hyperlink example producing an empty image. Width was adjusted to be consistent with other tapes.
=> docs(examples): fix hyperlink example tape

examples/vhs/constraint-explorer.tape, examples/vhs/demo2-destroy.tape, examples/vhs/demo2-social.tape, examples/vhs/demo2.tape, examples/vhs/docsrs.tape, examples/vhs/flex.tape, examples/vhs/hyperlink.tape, examples/vhs/minimal.tape, examples/vhs/ratatui-logo.tape, examples/vhs/tracing.tape
Fixes filename typos in example tape files to be consistent.
=> docs(examples): fix typos in tape files

examples/chart.rs, src/widgets/chart.rs
=> feat(chart): add GraphType::Bar

Cargo.toml
better-panic is unused, palette is a feature and should be used as such.
palette was specified with two different versions which creates issues when running https://github.com/taiki-e/cargo-minimal-versions
=> build: cleanup dev dependencies

src/buffer/buffer.rs
fixes #1211
As I have the stuff tested in a local branch, I can also push it for more discussions.
See https://doc.rust-lang.org/std/primitive.char.html#method.is_control
=> fix(buffer): dont render control characters

src/text/text.rs
BREAKING CHANGE: The ToText trait no longer has a lifetime parameter.
This change simplifies the trait and makes it easier implement.
=> feat(text)!: remove unnecessary lifetime from ToText trait

src/widgets/block.rs, src/widgets/paragraph.rs
Fixes: #1233
The `line_width`, and `line_count` methods for `Paragraph` would not take into account the `Block` if one was set. This will now correctly calculate the values including the `Block`'s width/height.
The `Blocks` newly implemented `horizontal_space`, and `vertical_space` can also be used in `Block::inner` since its mostly duplicate logic. Can add it to this PR or a separate one later. This is also why I decided it would be better to return the results as `(top, bottom)`, and `(left, right)` since it would allow for use in more areas.
=> fix(paragraph): Account for Block in Paragraphs line_width, and line_count methods.

src/text/line.rs, src/text/span.rs, src/text/text.rs
This enables:
```rust
let line = Span::raw("Red").red() + Span::raw("blue").blue();
let line = Line::raw("Red").red() + Span::raw("blue").blue();
let line = Line::raw("Red").red() + Line::raw("Blue").blue();
let text = Line::raw("Red").red() + Line::raw("Blue").blue();
let text = Text::raw("Red").red() + Line::raw("Blue").blue();
let mut line = Line::raw("Red").red();
line += Span::raw("Blue").blue();
let mut text = Text::raw("Red").red();
text += Line::raw("Blue").blue();
line.extend(vec![Span::raw("1"), Span::raw("2"), Span::raw("3")]);
```
=> feat(text): Add `Add` and `AddAssign` implementations for `Line`, `Span`, and `Text`

src/widgets/list/rendering.rs
When rendering a `List`, each `ListItem` would be cloned. Removing the clone, and replacing `Widget::render` with `WidgetRef::render_ref` saves us allocations caused by the clone of the `Text<'_>` stored inside of `ListItem`. 
Based on the results of running the "list" benchmark locally; Performance is improved by %1-3 for all `render` benchmarks for `List`.
=> perf(list): avoid extra allocations when rendering `List`

.github/workflows/check-pr.yml
This PR changes the label that is auto attached to a PR with a breaking change per the conventional commits specification.
=> chore(ci): change label from `breaking change` to `Type: Breaking Change`

src/widgets/table/cell.rs, src/widgets/table/table.rs
When rendering a `Table` the `Text` stored inside of a `Cell` gets cloned before rendering. This removes the clone and uses `WidgetRef` instead, saving us from allocating a `Vec<Line<'_>>` inside `Text`. Also avoids an allocation when rendering the highlight symbol if it contains an owned value.
=> perf(table): avoid extra allocations when rendering `Table`

src/text/line.rs
A `Line` widget should only apply its style to the first line when
rendering and not the entire area. This is because the `Line` widget
should only render a single line of text. This commit fixes the issue by
clamping the area to a single line before rendering the text.
=> fix: only apply style to first line when rendering a `Line`

src/layout/margin.rs, src/layout/position.rs, src/layout/rect.rs, src/layout/size.rs
=> feat(layout): allow more serialization with serde

BREAKING-CHANGES.md, examples/constraints.rs, examples/flex.rs, src/layout/layout.rs
The cache is a thread-local, so doesn't make much sense to require synchronized initialization.
=> fix: remove pointless synchronization in layout cache

.github/workflows/ci.yml
This helps with identifying what failed right from the title. Also steps after a failing one are now always executed.
Also shortens the steps a bit by removing obvious names.
=> ci: split up lint job

src/text/line.rs, src/text/span.rs, src/widgets/chart.rs
Extracted from https://github.com/ratatui-org/ratatui/pull/1249
=> fix: various newline handling improvements

BREAKING-CHANGES.md, examples/chart.rs, src/widgets/chart.rs, tests/widgets_chart.rs
Fixes: https://github.com/ratatui-org/ratatui/issues/1272
=> feat(barchart)!: allow axes to accept Lines

src/widgets/chart.rs
`axis.labels(vec![])` removes all the labels correctly.
Probably never used but prevents weird cases by removing the mix-up of `Option::None` and `Vec::is_empty`.
---
Thought about naming this refactor or feat as its probably something not even used by someone. It's mainly preventing weird edge cases by removing the type mix-up.
=> feat(chart): allow removing all the axis labels

src/widgets.rs
Addresses some confusion about when to implement `WidgetRef` vs `impl Widget for &W`. Notes the stability rationale and links to an issue that helps explain the context of where we're at in working this out.
=> docs(widgets): document stability of WidgetRef

BREAKING-CHANGES.md, examples/chart.rs, examples/demo/ui.rs, src/widgets/chart.rs, tests/widgets_chart.rs
BREAKING CHANGES: #1273 is already breaking and this only advances the already breaking part
=> feat(chart)!: accept `IntoIterator` for axis labels

BREAKING-CHANGES.md, examples/user_input.rs, src/backend.rs, src/backend/crossterm.rs, src/backend/termion.rs, src/backend/termwiz.rs, src/backend/test.rs, src/terminal/frame.rs, src/terminal/terminal.rs
Idea from https://github.com/ratatui-org/ratatui/pull/1254#issuecomment-2264919603
Usage search: https://github.com/search?q=ratatui+.set_cursor+AND+(NOT+org%3Aratatui-org)+AND+(NOT+is%3Afork)+AND+(NOT+is%3Aarchived)&type=code
=> feat!: add `get/set_cursor_position()` methods to Terminal and Backend

Cargo.toml, benches/main.rs, benches/main/barchart.rs, benches/main/block.rs, benches/main/line.rs, benches/main/list.rs, benches/main/paragraph.rs, benches/main/rect.rs, benches/main/sparkline.rs
Consolidates the benchmarks into a single executable rather than having to create a new cargo.toml setting per and makes it easier to rearrange these when adding new benchmarks.
=> perf: move benchmarks into a single benchmark harness

src/widgets/reflow.rs
On large paragraphs (~1MB), this saves hundreds of thousands of allocations.
TL;DR: reuse as much memory as possible across `next_line` calls. Instead of allocating new buffers each time, allocate the buffers once and clear them before reuse.
=> perf(reflow): eliminate most WordWrapper allocations

src/terminal/terminal.rs
Fix typo for depreciated `set_cursor` method comment.
From `aet_cursor_position` to `set_cursor_position`
=> docs: terminal.rs typo

src/lib.rs
It's no longer needed since #1260
=> docs: remove superfluous doc(inline)

examples/async.rs, examples/barchart-grouped.rs, examples/barchart.rs, examples/chart.rs, examples/demo/crossterm.rs, examples/hyperlink.rs, examples/inline.rs, examples/list.rs, examples/panic.rs, examples/paragraph.rs, examples/scrollbar.rs, examples/sparkline.rs, examples/tracing.rs
We import from `ratatui::crossterm`` instead of crossterm directly in
the examples to ensure that the version of the crossterm crate used is
the same one as the one used by ratatui. This helps avoid compilation
errors resulting from multiple versions of the same crate.
Also avoids importing from the prelude in the examples.
=> docs(examples): use ratatui::crossterm in examples

src/text/text.rs
The `Display` impl for `Text` intentionally omits a trailing newline for the final line. This logic wasn't working for single-line text though. I added an additional text case, which previously was failing and now passes.
=> fix: remove trailing newline from single-line Text::Display

Cargo.toml, Makefile.toml, examples/demo/main.rs, examples/demo/termion.rs, examples/demo/termwiz.rs, src/backend.rs, src/lib.rs, src/prelude.rs, tests/backend_termion.rs
Termion is not supported on Windows, so we need to avoid building it.
Adds a conditional dependency to the Cargo.toml file to only include
termion when the target is not Windows. This allows contributors to
build using the `--all-features` flag on Windows rather than needing
to specify the features individually.
---
Testing:
cargo build --all-features now succeeds on windows (11 Arm 64)
=> build: simplify Windows build

src/terminal/terminal.rs
If the amount of characters in the screen above the viewport was greater than u16::MAX, a multiplication would overflow. The multiply was used to compute the maximum chunk size. The fix is to just do the multiplication as a usize and also do the subsequent division as a usize.
There is currently another outstanding issue that limits the amount of characters that can be inserted when calling Terminal::insert_before to u16::MAX. However, this bug can still occur even if the viewport and the amount of characters being inserted are both less than u16::MAX, since it's dependant on how large the screen is above the viewport.
Fixes #1322
=> fix: fix u16 overflow in Terminal::insert_before.

BREAKING-CHANGES.md, CHANGELOG.md, src/terminal/frame.rs
...nothing too major.
it's --> "it is"
its --> "it" possesses something
I noticed this in the deprecation message for Frame::area, and went looking for more mistakes. I only found three in total.
=> Doc only fixes: its vs it's mistakes

src/style/stylize.rs, src/text/line.rs, src/text/masked.rs, src/text/text.rs, src/widgets/reflow.rs, src/widgets/table/table.rs
A vector can be compared to an array.
=> test: Avoid unneeded allocations in assertions

Cargo.toml, examples/widget_impl.rs
This new example documents the various ways to implement widgets in
Ratatui. It demonstrates how to implement the `Widget` trait on a type,
a reference, and a mutable reference. It also shows how to use the
`WidgetRef` trait to render boxed widgets.
=> docs(examples): add widget implementation example

src/backend/test.rs, src/buffer/cell.rs, src/terminal/terminal.rs, tests/terminal.rs
Reimplement Terminal::insert_before. The previous implementation would insert the new lines in chunks into the area between the top of the screen and the top of the (new) viewport. If the viewport filled the screen, there would be no area in which to insert lines, and the function would crash.
The new implementation uses as much of the screen as it needs to, all the way up to using the whole screen.
This commit:
- adds a scrollback buffer to the `TestBackend` so that tests can inspect and assert the state of the scrollback buffer in addition to the screen
- adds functions to `TestBackend` to assert the state of the scrollback
- adds and updates `TestBackend` tests to test the behavior of the scrollback and the new asserting functions
- reimplements `Terminal::insert_before`, including …
=> fix(terminal): Terminal::insert_before would crash when called while the viewport filled the screen

src/widgets/table/table_state.rs
The part of the `TableState` docs that mention the examples, use an incorrect number of backticks.
Old:
New:
=> docs(table): fix incorrect backticks in `TableState` docs

examples/minimal.rs
For following the same convention with the other panic message in `event::read()`
=> style(example): update panic message in minimal template

.github/workflows/release-alpha.yml, .github/workflows/release-stable.yml
See: https://github.com/orhun/git-cliff-action/releases/tag/v4.0.0
This also makes me think if we should track GitHub Actions dependencies via Dependabot as well.
=> chore(ci): bump git-cliff-action to v4

src/backend/crossterm.rs, src/backend/termion.rs
Fixes https://github.com/ratatui/ratatui/issues/1348.
Simply adds a link to `stdout` vs `stderr` FAQ entry on ratatui.rs on the backend constructor.
=> docs(backend): added link to stdio FAQ

src/terminal/terminal.rs
Calling `Terminal::resize()` on a fixed viewport silently does nothing, because the inner `area` variable shadows the `area` parameter specified by user - this feels like a bug, because resizing fixed frames comes handy and I think it should be allowed.
=> fix: allow to resize fixed viewports

Cargo.toml
https://github.com/ratatui/ratatui/pull/991 created a new unstable feature, but forgot to add it to Cargo.toml, making it impossible to use on newer versions of rustc - this commit fixes it.
=> fix: create `unstable-backend-writer` feature

src/widgets/calendar.rs
=> fix: prevent calender render panic when terminal height is small

benches/main/block.rs, examples/block.rs, examples/chart.rs, examples/flex.rs, examples/gauge.rs, examples/inline.rs, examples/line_gauge.rs, src/widgets/block.rs, src/widgets/block/title.rs, tests/widgets_block.rs
`ratatui::widgets::block::Title` is deprecated in favor of using `Line` to represent titles.
This removes an unnecessary layer of wrapping (string -> Span -> Line -> Title).
This struct will be removed in a future release of Ratatui (likely 0.31).
For more information see: <https://github.com/ratatui/ratatui/issues/738>
To update your code:
```rust
Block::new().title(Title::from("foo"));
// becomes any of
Block::new().title("foo");
Block::new().title(Line::from("foo"));
Block::new().title(Title::from("foo").position(Position::TOP));
// becomes any of
Block::new().title_top("foo");
Block::new().title_top(Line::from("foo"));
Block::new().title(Title::from("foo").position(Position::BOTTOM));
// becomes any of
Block::new().title_bottom("foo");
Block::new().title_bottom(Line::from("foo"));
```
=> chore(block): deprecate block::Title

Cargo.toml
I'm not sure what is causing CI failures, but 0.1.14 contains breakig changes which we'll need to investigate.
Changes https://github.com/unicode-rs/unicode-width/compare/v0.1.13...v0.1.14
Fixes problems found in https://github.com/ratatui/ratatui/pull/1341
=> chore: lock unicode-width version to 0.1.13

examples/widget_impl.rs, src/layout/layout.rs
This PR renames `element` to `segment` in a couple of functions in the layout calculations for clarity. `element` can refer to `segment`s or `spacer`s and functions that take only `segment`s should use `segment` as the variable names.
=> refactor(layout): rename element to segment in layout

Cargo.toml, examples/ratatui-logo.rs, examples/vhs/ratatui-logo.tape, src/widgets.rs, src/widgets/logo.rs
Just an idea that I'm playing with, a subtle modification to the height of the logo so that it can be rendered nicely on 2 lines rather than 2.5
=> feat(logo): shorter logo now in widget form

src/layout/layout.rs
Fixes #1399 
I've looked through all the `assert_eq` and made sure that they follow the `expected, result` pattern. I wasn't sure if it was desired to actually pass result and expected as variables to the assert_eq statements, so I've left everything that seems to have followed the pattern as is.
=> refactor: Consistent result expected in layout tests

benches/main.rs, benches/main/table.rs
It is essentially the same as the `List` benchmark, the only logic difference being the variable column counts.
=> chore: add benchmark for `Table`

BREAKING-CHANGES.md, src/widgets/tabs.rs
`Tabs::select()` now accepts `Into<Option<usize>>` instead of `usize`.
This allows tabs to be deselected by passing `None`.
`Tabs::default()` is now also implemented manually instead of deriving
`Default`, and a new method `Tabs::titles()` is added to set the titles
of the tabs.
Fixes: <https://github.com/ratatui/ratatui/pull/1412>
BREAKING CHANGE: `Tabs::select()` now accepts `Into<Option<usize>>`
which breaks any code already using parameter type inference:
```diff
let selected = 1u8;
- let tabs = Tabs::new(["A", "B"]).select(selected.into())
+ let tabs = Tabs::new(["A", "B"]).select(selected as usize)
```
=> feat(tabs)!: allow tabs to be deselected

BREAKING-CHANGES.md, src/text/line.rs
BREAKING-CHANGES: `Line` now implements `From<Cow<str>`
As this adds an extra conversion, ambiguous infered values may no longer
compile.
```rust
// given:
struct Foo { ... }
impl From<Foo> for String { ... }
impl From<Foo> for Cow<str> { ... }
let foo = Foo { ... };
let line = Line::from(foo); // now fails due to ambiguous type inference
// replace with
let line = Line::from(String::from(foo));
```
Fixes: https://github.com/ratatui/ratatui/issues/1367
=> feat(line)!: impl From<Cow<str>> for Line

BREAKING-CHANGES.md, benches/main/buffer.rs, examples/canvas.rs, src/buffer/buffer.rs, src/layout/rect.rs, tests/terminal.rs
This change fixes the unexpected behavior of the Rect::new() function to
be more intuitive. The Rect::new() function now clamps the width and
height of the rectangle to keep each bound within u16::MAX. The
Rect::area() function now returns a u32 instead of a u16 to allow for
larger areas to be calculated.
Previously, the Rect::new() function would clamp the total area of the
rectangle to u16::MAX, by preserving the aspect ratio of the rectangle.
BREAKING CHANGE: Rect::area() now returns a u32 instead of a u16.
Fixes: <https://github.com/ratatui/ratatui/issues/1375>
---
TODO
height fit inside the u16 bounds as otherwise this would lead to non-indexable positions (and generally more overflows).
=> fix(rect)!: Rect::area now returns u32 and Rect::new() no longer clamps area to u16::MAX

BREAKING-CHANGES.md, src/lib.rs, src/style/color.rs
BREAKING-CHANGE: Previously `Color::from_hsl` accepted components
as individual f64 parameters. It now accepts a single `palette::Hsl` value
and is gated behind a `palette` feature flag.
```diff
- Color::from_hsl(360.0, 100.0, 100.0)
+ Color::from_hsl(Hsl::new(360.0, 100.0, 100.0))
```
Fixes: <https://github.com/ratatui/ratatui/issues/1414>
=> refactor(color)!: use palette types for Hsl/Hsluv conversions

BREAKING-CHANGES.md, src/layout/rect/iter.rs
BREAKING CHANGE: The Rect Positions iterator no longer has public
fields. The `rect` and `current_position` fields have been made private
as they were not intended to be accessed directly.
=> chore!: make Positions iterator fields private

src/prelude.rs, src/style.rs, src/widgets/table/table.rs, src/widgets/table/table_state.rs
Fixes: <https://github.com/ratatui/ratatui/issues/1150>
=> chore: remove the last prelude refs / glob imports from example code

src/text/line.rs, src/text/text.rs
This is a follow-up PR to https://github.com/ratatui/ratatui/pull/987, which implemented alignment-aware truncation for the `Line` widget. However, the truncation only checked the `Line::alignment` field, and any alignment inherited from a parent's `Text::alignment` field would not be used.
This commit updates the truncation of `Line` to depend both on the individual `Line::alignment`, and on any alignment inherited from the parent's `Text::alignment`.
=> fix(text): truncate based on alignment

src/terminal/terminal.rs
This is the same mistake as 0f4823977894cef51d5ffafe6ae35ca7ad56e1ac
The code that comes after is still incorrect, clearing from the cursor to the bottom of the screen multiple times.
I'm using this in an alternate "Inline" implementation, as described in https://github.com/ratatui/ratatui/issues/1426#issuecomment-2420571210, for which the latter problem doesn't matter, except perhaps to reduce flickering very very slightly.
I hope this patch is acceptable as is.
=> fix(terminal): use the latest, resized area when clearing

src/style/color.rs
The `from_hsl` and `from_hsluv` functions now clamp the HSL and HSLuv
values before converting them to RGB. This ensures that the input values
are within the expected range before conversion.
Also note that the ranges of Saturation and Lightness values have been
aligned to be consisten with the palette crate. Saturation and Lightness
for `from_hsl` are now in the range [0.0..1.0] while `from_hsluv` are
in the range [0.0..100.0].
Refs:
- <https://github.com/Ogeon/palette/discussions/253>
- <https://docs.rs/palette/latest/palette/struct.Hsl.html>
- <https://docs.rs/palette/latest/palette/struct.Hsluv.html>
Fixes: <https://github.com/ratatui/ratatui/issues/1433>
=> fix(color)!: hsl and hsluv are now clamped before conversion

src/buffer/buffer.rs, src/style/color.rs
Previously this function wrapped the index pass u16::MAX which caused
problems rendering.
Fixes: <https://github.com/ratatui/ratatui/issues/1441>
=> fix(buffer): buffer::get_pos() now correctly handles index > u16::MAX

README.md
README.md contains a link to unexisting example directory like it was before on root bu nowt it's in `ratatui` directory. 
I'm new to this repo this is probably due to a recent change.
=> docs: fix example link in readme

BREAKING-CHANGES.md, ratatui/src/backend.rs, ratatui/src/backend/crossterm.rs, ratatui/src/backend/termion.rs, ratatui/src/backend/termwiz.rs, ratatui/src/prelude.rs
Adds two traits `IntoCrossterm` and `FromCrossterm` for converting
between ratatui and crossterm types. This is necessary in order to avoid
the orphan rule when implementing `From` for crossterm types once the
crossterm types are moved to a separate crate.
Similarly Termwiz and Termwiz gain FromTermion, IntoTermion, FromTermwiz
and IntoTermwiz traits.
BREAKING CHANGE: The `From` and `Into` impls for backend types are now replaced
with specific backend traits.
```diff
+ use ratatui::backend::{FromCrossterm, IntoCrossterm};
let crossterm_color = crossterm::style::Color::Black;
- let ratatui_color = crossterm_color.into();
- let ratatui_color = ratatui::style::Color::from(crossterm_color);
+ let ratatui_color = ratatui::style::Color::from_crossterm(crossterm_color);
- let crossterm_color = …
```
=> chore(backend): change From<T> impls to new backend specific IntoBackend and FromBackend traits

.github/workflows/bench_track_fork_pr.yml
This changeset updates the Bencher CLI to the new recommended usage.
- Update deprecated CLI options: https://bencher.dev/docs/explanation/branch-selection/
- Safer and more succinct tracking from forks: https://bencher.dev/docs/how-to/github-actions/#pull-requests-from-forks
=> ci: Update Bencher CLI usage

.github/workflows/ci.yml
`install-action` uses `cargo-binstall` to install the pre-built binaries of `cargo-rdme` (which was released in https://github.com/orium/cargo-rdme/releases/tag/v1.4.7).
This will make the `check-readme` step faster in CI (now takes only 10 seconds).
=> chore(ci): install pre-built binaries for cargo-rdme

bacon.toml
No longer necessary as of bacon 3.3
=> chore: remove --color always flags from bacon.toml

ratatui-core/src/widgets/stateful_widget.rs, ratatui/src/widgets/stateful_widget_ref.rs, ratatui/tests/stateful_widget_ref_dyn.rs
When I want to use Box<dyn StatefulWidgetRef> I have to give a type for state. 
To be able to store different widgets this would need to be something like `dyn Any` too, which is not possible now, but is possible with this fix.
=> fix: Make StatefulWidgetRef work with dyn States.

README.md, ratatui/src/backend.rs, ratatui/src/backend/crossterm.rs, ratatui/src/backend/termwiz.rs, ratatui/src/lib.rs
Hello, this PR just corrects the examples hyperlink.
The PR #1459 introduced the workspace directory, but it missed this link.
* Before: https://github.com/ratatui/ratatui/tree/main/examples/README.md
* After: https://github.com/ratatui/ratatui/tree/main/ratatui/examples/README.md
=> docs(readme): correct examples link

BREAKING-CHANGES.md, ratatui-widgets/src/barchart.rs, ratatui-widgets/src/barchart/bar.rs, ratatui-widgets/src/barchart/bar_group.rs, ratatui/benches/main/barchart.rs, ratatui/examples/barchart-grouped.rs, ratatui/examples/demo2/tabs/weather.rs, ratatui/tests/widgets_barchart.rs
BREAKING CHANGE: label and text_value now accept `Into<>` types, which
breaks type inference.
```diff
- Bar::default().label("foo".into());
+ Bar::default().label("foo");
```
```diff
- Bar::default().text_value("bar".into());
+ Bar::default().text_value("bar");
```
=> feat(bar)!: update label and text_value to accept Into<>

ratatui-widgets/src/table.rs
Prior to this commit, a table would only display rows whose height could entirely fit within the available area.  As a result, table rows with `row.height > 1`, which require multiple terminal rows to display, could result in empty rows being rendered at the bottom of the table's display area.
This commit updates the rendering of `Table` to also include rows that may be partially visible within the available area.  That is, even if the display area does not have sufficient height to fully display an additional row of the table, it may still display the first few lines of an additional table row.
This change does not affect the change of the `offset`, which adjusts the viewing bounds to ensure that the selected row is displayed.  This is deliberate, since the view should be scrolled to …
=> fix(table): Allow display of additional table row, if row height > 1

ratatui-widgets/src/barchart.rs, ratatui-widgets/src/barchart/bar.rs, ratatui-widgets/src/barchart/bar_group.rs
implements a part of: https://github.com/ratatui/ratatui/issues/683
`new` and `with_label` constructors for `Bar`
`new` constructors for `BarGroup` and `BarChart`
=> feat(barchart): reduce barchart creation verbosity

ratatui-widgets/Cargo.toml, ratatui/Cargo.toml
We now expect that you disable the default features if you want less dependencies
=> chore(widgets): enable calendar widget as default

Cargo.lock, Cargo.toml, deny.toml, ratatui-core/Cargo.toml, ratatui-crossterm/Cargo.toml, ratatui-termion/Cargo.toml, ratatui-termwiz/Cargo.toml, ratatui-widgets/Cargo.toml, ratatui/Cargo.toml
This is just a PR to show what's being published in the first modularization -alpha release. It's a manual publish to ensure that all the crates are properly setup and to set a baseline for comparison in future release-plz checks etc.
This does not update / check the git-cliff setup / changelog
Part of: #1388
=> chore: prepare alpha modularization release

xtask/src/main.rs
Fixes the CI.
Also makes it possible to filter workspace packages by their targets which might be useful in the future (e.g. when we want to retrieve all the binary targets / examples, etc.)
=> chore(xtask): check lints for only library targets

ratatui-widgets/src/scrollbar.rs
This adds the `area.is_empty()` back into the scrollbar render method. Without it, the widget panics if the height is 0.
To reproduce this error, you can open the scrollbar demo2 in `/examples` (on the main branch) and continuously reduce the vertical height of your terminal window until it panics.
I also added a test, but I wasn't sure how to write the test correctly, currently there is no assert statement and the test suite will simply panic if the call to `is_empty()` is removed. 
You can also see that in the test, the buffer has a non-zero area. If the buffer area is 0, I don't think this error occurs. 
I was thinking, might make more sense if `scrollbar_area` returned a result instead of exiting with expect? 
Happy to make any changes.
=> fix(scrollbar): check for area.is_empty() before rendering 

BREAKING-CHANGES.md, README.md, ratatui-core/src/lib.rs, ratatui-core/src/terminal.rs, ratatui-core/src/terminal/frame.rs, ratatui-core/src/terminal/terminal.rs, ratatui-core/src/terminal/viewport.rs, ratatui-crossterm/Cargo.toml, ratatui-termion/Cargo.toml, ratatui-termion/src/lib.rs, ratatui/Cargo.toml, ratatui/src/init.rs, ratatui/src/lib.rs, ratatui/src/widgets.rs
- Move Terminal, TerminalOptions, ViewPort, CompletedFrame, Frame to
ratatui-core crate
- Move render_widget_ref() and render_stateful_widget_ref() to extension
trait (FrameExt) due as the Ref types are unstable and kept in the
main lib instead of -core
- Fix rustdoc errors / feature config issues
BREAKING CHANGE: to call `Frame::render_widget_ref()` or
`Frame::render_stateful_widget_ref()` you now need to import the
FrameExt trait from `ratatui::widgets` and enable the
`unstable-widget-ref` feature.
=> chore: move terminal types to ratatui-core

ratatui-widgets/src/canvas/circle.rs, ratatui-widgets/src/canvas/points.rs, ratatui-widgets/src/canvas/rectangle.rs
Allows constructing `Rectangle`, `Points` and `Circle` using the `new` method instead of initializing with the public fields directly.
=> feat(widgets): add the missing constructor to canvas types

ratatui-crossterm/src/lib.rs
The Dim removal should behave the same as the logic for Bold removal that sends NormalIntensity sequence and then restores Dim when needed.
=> fix(crossterm): terminal should keep Bold when removing Dim

Cargo.lock, examples/apps/input-form/Cargo.toml, examples/apps/input-form/README.md, examples/apps/input-form/src/main.rs
Demonstrates how to manage the cursor and input focus with a simple
form. Uses an enum to track the current input field and passes the
input events to the active field.
This is similar to the json tutorial on the website, but a bit simpler
=> docs: add input form example

ratatui-widgets/src/scrollbar.rs
As of now it is possible to change the position of the Scrollbar but not possible to retrieve the position for further use. e.g.
```rust
let mut state = ScrollbarState::default();
state.next();
```
This commit adds a new method "`current_position`" (since `position` is already taken by the fluent setter) for that purpose:
```rust
let index = state.get_position(); // yay
```
See #1545 for the concrete usage of this.
=> feat(scrollbar): support retrieving the current position of state

ratatui-widgets/src/canvas.rs
Fix end of sentence punctuation in canvas.rs docs.
=> docs: fix punctuation in canvas.rs documentation

Cargo.lock, ratatui-core/Cargo.toml, ratatui-core/src/style.rs, ratatui-core/src/style/anstyle.rs
https://crates.io/crates/anstyle makes it possible to define colors in
an interoperable way. This makes it possible for applications to easily
load colors from a variety of formats.
This is gated by the anstyle feature flag which is disabled by default.
=> feat: add conversions for anstyle

ratatui/examples/user_input.rs
Fix wording in `user_input.rs` example.
=> docs: fix wording in user_input example

ratatui-widgets/src/canvas/world.rs, ratatui-widgets/src/list/rendering.rs
The canvas map constants are now statics instead.
Fixes https://rust-lang.github.io/rust-clippy/master/index.html\#large_const_arrays
=> fix: rust 1.84 clippy lints

CHANGELOG.md, Cargo.lock, Cargo.toml, ratatui-core/Cargo.toml, ratatui-core/src/backend.rs, ratatui-core/src/backend/test.rs, ratatui-core/src/terminal.rs, ratatui-core/src/terminal/frame.rs, ratatui-core/src/terminal/terminal.rs, ratatui-crossterm/Cargo.toml, ratatui-termion/Cargo.toml, ratatui-termwiz/Cargo.toml, ratatui-widgets/Cargo.toml, ratatui/Cargo.toml
Previous PR merged too early (and removed with a force push). This currently does not publish due the the circular dependency in the dev-dependencies of -core on ratatui.
=> chore: release 0.30.0-alpha.1

.github/workflows/ci.yml
The cargo-deny action takes about 30s to run, because it downloads and
runs a docker image, but this should be generally closer to a 5-10
seconds when run directly. This is not a huge saving, but it allows other
CI jobs to start sooner and so to see results of CI quicker.
First test showed around 17s, but Iassume this will probably hit single
digit seconds as it is similar to the typos job.
=> ci: run cargo-deny directly rather than via action

ratatui-core/src/symbols/border.rs, ratatui-core/src/symbols/line.rs, ratatui-widgets/src/block.rs, ratatui-widgets/src/borders.rs
=> feat(symbols): add dashed borders (#1355)

ratatui-widgets/src/paragraph.rs, ratatui-widgets/src/reflow.rs, ratatui/benches/main/paragraph.rs
Hi,
Thanks for the great work on ratatui 🙏🏻 
_This PR introduces a slight change that I believe could end up significantly improving rendering times for paragraphs that do not depend on certain kinds of `LineComposer`s._
Currently all `LineComposer`s are considered to be state machines which means rendering a paragraph with a given Y offset requires computing the entire state up to Y before being able to render from Y onwards.
While this makes sense for Composers such as the `WordWrapper` (where one needs to consider all previous lines to determine where a given line will end up), it means it also penalizes Composers which can render a given line "statelessely" (such as the `LineTruncator`) which actually end up doing a lot of unnecessary work (and on the critical rendering path) when the …
=> perf(widgets): avoid unnecessary work when rendering paragraphs

ratatui-widgets/src/paragraph.rs, ratatui-widgets/src/reflow.rs
Currently whitespace only lines produces an extra line break when trimming is disabled, because both the trimmed as well as the non-trimmed line get inserted. Fix this by only inserting the non-trimmed one.
=> fix: avoid extra line break on whitespace only lines when wrapping paragraphs

Cargo.toml
Move `termion` up in the dependencies list in `Cargo.toml` so that they are sorted alphabetically and so that the `unicode-width` comment is directly above the `unicode-width` dependency.
=> chore: sort dependencies in Cargo.toml

Cargo.lock, examples/README.md, examples/apps/widget-ref-container/Cargo.toml, examples/apps/widget-ref-container/README.md, examples/apps/widget-ref-container/src/main.rs, ratatui/Cargo.toml
=> docs(examples): move widget-ref-container example to examples folder

Cargo.lock, examples/apps/advanced-widget-impl/Cargo.toml, examples/apps/advanced-widget-impl/README.md, examples/apps/advanced-widget-impl/src/main.rs, ratatui/Cargo.toml
see #1512 
also renamed to `advanced-widget-impl`
=> docs(examples): move widget-impl example to examples folder

.github/workflows/release-plz.yml, cliff.toml, release-plz.toml
We are currently discussing this [on a livestream](https://www.youtube.com/watch?v=cxIumpVggnI).
There are still some required steps (such as [adding tokens](https://release-plz.ieni.dev/docs/github/quickstart) and updating workflow files accordingly) but this will probably give you an idea how adding release-plz looks like. You can test the changes by running `release-plz update` locally.
Related/unrelated to this PR, there are some specific stuff that I want to look into:
- e.g. `changelog_order=1` value in the `[[package]]` section
We need to test if the correct changelog section is set in the GitHub release when we create a release. Marco suggests that we should test it in a different repository.
**Q**: Do we want to have GitHub releases for each crate or e.g. a single release for …
=> chore(release): initialize release-plz

ratatui-core/src/layout/rect/iter.rs
=> fix: `Rect::positions()` should be empty when width is 0 and height is nonzero

ratatui-core/src/text/text.rs
fixes the CI
We can't link to `widgets` from `core`... this was left over during the modularization probably.
=> docs(core): remove link to Paragraph widget

BREAKING-CHANGES.md, Cargo.lock, Cargo.toml
This should've been caught during the last dependabot run. Looking at the [logs](https://github.com/ratatui/ratatui/actions/runs/13374599653/job/37350868073) it says `2025/02/17 16:22:00 INFO <job_966002227> No update possible for termwiz 0.22.0`. Not sure what's up with that.
Based on the last several [termwiz commits](https://github.com/wezterm/wezterm/commits/main/termwiz), it looks like this release has a few fixes for hyperlinks and input handling, plus some dependency updates.
Tested with the demo app to ensure things still work.
=> chore(deps): bump termwiz from 0.22.0 to 0.23.0

Cargo.lock, Cargo.toml
changelog: https://gitlab.redox-os.org/redox-os/termion/-/blob/master/CHANGELOG.md
fixes #884
=> chore(deps): bump termion to 4.0.4

ratatui-core/src/style/color.rs
Other crates (e.g. colorgrad) that deal with colors can convert colors
to a tuple of 3 or 4 u8 values. This commit adds conversion methods from
these types to a `Color::Rgb` instance. Any alpha value is ignored.
```rust
Color::from([255, 0, 0]);
Color::from((255, 0, 0));
Color::from([255, 0, 0, 255]);
Color::from((255, 0, 0, 255));
```
=> feat: add generic RGB color conversion methods

ratatui-core/src/backend.rs, ratatui-core/src/buffer/assert.rs, ratatui-core/src/buffer/buffer.rs, ratatui-core/src/terminal/frame.rs, ratatui-core/src/terminal/terminal.rs, ratatui-core/src/text/span.rs, ratatui-widgets/src/block.rs, ratatui-widgets/src/block/padding.rs, ratatui-widgets/src/block/title.rs, ratatui-widgets/src/gauge.rs, ratatui-widgets/src/table.rs
AI coding assistants use the deprecation notes to automatically suggest
fixes. This commit updates the deprecation notes to push those tools to
suggest the correct replacement methods and types.
Specifically, AI tools often suggest using `Buffer::get(x, y)`, because
of their training data where this was prevalent. When fixing these
deprecations, they often incorrectly suggest using `Buffer::get(x, y)`
instead of `Buffer[(x, y)]`.
=> fix: make deprecation notes more helpful

BREAKING-CHANGES.md, ratatui-widgets/examples/list.rs, ratatui-widgets/src/list.rs, ratatui-widgets/src/list/rendering.rs
Allow styling for `List`'s highlight symbol
Currently there is no way to style the highlight symbol of a `List`. 
This change makes it so anything that implements `Into<Line>` can be used as a highlight symbol.
BREAKING CHANGE: `List::highlight_symbol` can no longer be used in const context
BREAKING CHANGE: `List::highlight_symbol` accepted `&str`. Conversion methods that rely on type inference will need to be rewritten as the compiler cannot infer the type.
closes: https://github.com/ratatui/ratatui/issues/1443
=> feat(list)!: highlight symbol styling

Cargo.lock, ratatui-core/Cargo.toml, ratatui-core/src/style/stylize.rs
The paste crate is no longer maintained. Replaces the usages of this in
the Stylize declarative macros with hard coded values. These macros are
internal implementation deatil to ratatui and so the changes should have
no impact on users.
Fixes: https://github.com/ratatui/ratatui/issues/1712
=> chore: remove paste dependency

examples/apps/demo2/src/app.rs
see #1721
Not sure what caused this - it's been there for a while probably and we didn't realize it since we used `demo2-destroy` mostly.
=> fix(demo): support tab key in demo2 example

ratatui-widgets/src/table.rs
While looking into the performance of table I noticed this. I changed it towards [the same approach used as in my table widget](https://github.com/EdJoPaTo/tui-rs-tree-widget/blob/6a5243243a7c4a608ef5f0b632b527baae649752/src/lib.rs#L208-L210).
It shouldn’t have much impact on small changes to offset / selection. Bigger changes upwards no longer require checking the height of many rows multiple times as the function has one less loop involved. The first loop still makes sure everything is correct.
This case might also exist in other widgets, haven’t checked so far.
=> perf(table): replace while loop with simple min operation

examples/apps/colors-rgb/src/main.rs, examples/apps/constraint-explorer/src/main.rs, examples/apps/inline/src/main.rs, examples/apps/input-form/src/main.rs, examples/apps/table/src/main.rs, examples/apps/todo-list/src/main.rs, ratatui-core/src/buffer/buffer.rs, ratatui-core/src/terminal/terminal.rs, ratatui-core/src/text/line.rs, ratatui-termion/src/lib.rs, ratatui-widgets/src/chart.rs, ratatui-widgets/src/scrollbar.rs, ratatui-widgets/src/table.rs
New version of rust (1.86.0) caused CI to fail.
=> fix: correct clippy errors introduced by rust 1.86.0 update

BREAKING-CHANGES.md, ratatui-core/src/layout.rs, ratatui-core/src/layout/alignment.rs, ratatui-widgets/src/block.rs, ratatui/src/prelude.rs
We don't anticipate removing or deprecating the type alias in the near
future, but it is recommended to update your imports to use the new
name.
Added a VerticalAlignment enum to make the API more consistent. We don't
have a specific use case for it yet, but it's better to add it now and
be able to use it in the future.
BREAKING-CHANGE: The `Alignment` enum has been renamed to
`HorizontalAlignment` to better reflect its purpose. A type alias has
been added to maintain backwards compatibility, however there are some
cases where type aliases are not enough to maintain backwards
compatibility. E.g. when using glob imports to import all the enum
variants. This should not affect most users, but it is recommended to
update your imports to use the new name.
```diff
- use …
```
=> feat!: rename Alignment to HorizontalAlignment and add VerticalAlignment

ratatui-core/src/style/stylize.rs
Implements `Styled` for other primitive types so you can do something like `1.red()` instead of `1.to_string().red()`. I also added the implementation for `Cow<'a str>` since it was missing. It would be nice to have a blanket impl of `Styled` for any type implementing `Display`, but that would mean calling `to_string()` on borrowed types and creating extra allocations, so I think this will have to suffice.
=> feat: implement styled for other primitives

Cargo.lock, ratatui-core/Cargo.toml
Looking at https://github.com/ParkMyCar/compact_str/blob/v0.9.0/CHANGELOG.md#090, there are a few API changes, but it doesn’t seem like anything there should be a problem given that `cargo test` still passes in `ratatui-core/`.
=> build(deps): update compact_str requirement from 0.8.1 to 0.9.0

ratatui-core/src/backend.rs, ratatui-core/src/backend/test.rs
core::ops::Range is only used with the feature `scrolling-regions`. Ensure a minimal `cargo check` reports no warnings.
=> fix: avoid unnecessary imports in minimal build

ratatui-core/src/backend.rs, ratatui-core/src/backend/test.rs, ratatui-core/src/buffer/assert.rs, ratatui-core/src/buffer/buffer.rs, ratatui-core/src/layout/alignment.rs, ratatui-core/src/layout/constraint.rs, ratatui-core/src/layout/direction.rs, ratatui-core/src/layout/layout.rs, ratatui-core/src/layout/margin.rs, ratatui-core/src/layout/position.rs, ratatui-core/src/layout/rect.rs, ratatui-core/src/layout/size.rs, ratatui-core/src/lib.rs, ratatui-core/src/style.rs, ratatui-core/src/style/color.rs, ratatui-core/src/style/stylize.rs, ratatui-core/src/symbols/border.rs, ratatui-core/src/symbols/line.rs, ratatui-core/src/symbols/marker.rs, ratatui-core/src/terminal/terminal.rs, ratatui-core/src/terminal/viewport.rs, ratatui-core/src/text/line.rs, ratatui-core/src/text/masked.rs, ratatui-core/src/text/span.rs, ratatui-core/src/text/text.rs, ratatui-core/src/widgets/stateful_widget.rs, ratatui-core/src/widgets/widget.rs
- Adds `#[no_std]` to `lib.rs`.
- Adds `extern crate std;` to `lib.rs`.
- Updates `ratatui-core` to explicitly `use` items from std and alloc.
- Prefers `use`-ing alloc over std when possible.
This allows usages of `std` in `ratatui-core` to be clearly pointed out and dealt with individually.
Eventually, when `std` is to be feature gated, the associated commit will be much cleaner.
=> refactor(no_std): Make usages of std explicit in ratatui-core.

ratatui-core/src/backend.rs, ratatui-crossterm/src/lib.rs, ratatui-termwiz/src/lib.rs
Pre-emptive fix for new lint to be added in 1.87 (currently in beta).
https://rust-lang.github.io/rust-clippy/master/index.html\#io_other_error
=> chore: fix io_other_error clippy lints

.github/workflows/ci.yml
This makes it possible to pre-emptively catch upcoming clippy issues. We
should not block PRs on these generally (unless the PR introduces a
valid clippy warning), so the workflow is set up to not fail on beta.
=> ci: run clippy using rust stable and beta

examples/apps/constraint-explorer/src/main.rs, examples/apps/constraints/src/main.rs, examples/apps/flex/src/main.rs, examples/apps/gauge/src/main.rs, examples/apps/input-form/src/main.rs, examples/apps/table/src/main.rs, examples/apps/todo-list/src/main.rs, examples/apps/user-input/src/main.rs, ratatui-core/src/buffer/cell.rs, ratatui-core/src/terminal/frame.rs, ratatui-core/src/terminal/terminal.rs, ratatui-crossterm/src/lib.rs, ratatui-termion/src/lib.rs, ratatui-termwiz/src/lib.rs, ratatui-widgets/examples/line_gauge.rs, ratatui-widgets/src/canvas.rs, ratatui-widgets/src/list/state.rs, ratatui-widgets/src/reflow.rs, ratatui-widgets/src/scrollbar.rs, ratatui-widgets/src/table/state.rs, ratatui/tests/state_serde.rs
The Clippy check for this (missing_const_for_fn) is already enabled, but catches more cases in upcoming toolchain versions.
This is part of the work to unblock #1727
=> chore: Add 'const' to functions where possible.

Cargo.lock, ratatui-crossterm/Cargo.toml, ratatui-termion/Cargo.toml, ratatui-termwiz/Cargo.toml, ratatui/Cargo.toml
This PR propagates the serde feature from the main ratatui crate to the ratatui-crossterm and ratatui-termion backend crates. Solves #1805
=> feat: Enable serde propagation to backend crates (crossterm, termion)

BREAKING-CHANGES.md, Cargo.lock, ratatui-core/Cargo.toml, ratatui-core/src/layout/layout.rs, ratatui/Cargo.toml, xtask/src/commands/backend.rs
Resolves #1780 
BREAKING CHANGE: Disabling `default-features` will now disable layout cache, which can have a negative impact on performance. `Layout::init_cache` and `Layout::DEFAULT_CACHE_SIZE` are now only available if `layout-cache` feature is enabled.
=> feat(no_std)!: option to disable layout cache for `no_std` compatibility

ratatui-widgets/Cargo.toml
Crossterm in widgets is used only in tests.
=> chore(widgets): move crossterm to dev-dependencies

ratatui-core/src/layout/layout.rs
This silences unused import warning, when `layout-cache` is disabled.
=> fix(layout-cache): import `NonZeroUsize` only when `layout-cache` is enabled

ratatui/Cargo.toml, ratatui/tests/widgets_calendar.rs
Since `time` is only used in `ratatui` in tests, I believe it should be moved to dev-dependencies.
=> chore: move time to dev-dependencies

Cargo.lock, Cargo.toml, ratatui-core/Cargo.toml
Disables `std` feature flags in dependencies and only enables them with `ratatui` and `ratatui-core`'s `std` feature flag.
~~Additionally bumps version of `kasuari`~~ _(moved to #1844)_, to get upstream changes that allow disabling dependency on `std`.
This partially fixes the issue of still depending on `std`, when `std` feature flag is disabled.
=> fix(no_std): propagate `std` feature flag to dependencies

ratatui-widgets/Cargo.toml, ratatui-widgets/src/calendar.rs
Removes the CalendarEventStore::today() function in no-std environments
=> feat: support no-std for calendar widget

ratatui-widgets/src/barchart.rs, ratatui-widgets/src/barchart/bar_group.rs
Add a new constructor to the `BarChart` widget that allows creating a
grouped barchart with multiple groups of bars.
Also add a new constructor to the `BarGroup` widget that allows creating
a group of bars with a label.
=> feat(barchar): add BarChart::grouped constructor

BREAKING-CHANGES.md, examples/apps/color-explorer/src/main.rs, examples/apps/demo2/src/tabs/weather.rs, ratatui-core/src/style.rs, ratatui-core/src/style/stylize.rs, ratatui-core/src/text/line.rs, ratatui-macros/src/span.rs, ratatui-termion/src/lib.rs, ratatui-termwiz/src/lib.rs, ratatui-widgets/src/canvas/line.rs, ratatui-widgets/src/canvas/rectangle.rs, ratatui-widgets/src/tabs.rs, ratatui/tests/widgets_gauge.rs, ratatui/tests/widgets_tabs.rs
This makes it possible to create constants using the shorthand methods.
```rust
const MY_STYLE: Style = Style::new().blue().on_black();
```
Rather than implementing Styled for Style and then adding extension
methods that implement the Stylize shorthands, this implements the
methods as const functions directly on Style.
BREAKING CHANGE: `Style` no longer implements `Styled`. Any calls to
methods implemented by the blanket implementation of Stylize are now
defined directly on Style. Remove the Stylize import if it is no longer
used by your code.
The `reset()` method does not have a direct replacement, as it clashes
with the existing `reset()` method. Use `Style::reset()` rather than
`some_style.reset()`
Fixes: #1158
=> feat!: implement stylize methods directly on Style

ratatui-core/src/layout/constraint.rs, ratatui-core/src/layout/direction.rs, ratatui-core/src/layout/flex.rs, ratatui-core/src/layout/layout.rs, ratatui-core/src/style/palette/material.rs, ratatui-core/src/style/palette/tailwind.rs, ratatui-widgets/src/block/padding.rs, ratatui-widgets/src/borders.rs, ratatui-widgets/src/list.rs, ratatui-widgets/src/scrollbar.rs, ratatui-widgets/src/sparkline.rs, ratatui-widgets/src/table/highlight_spacing.rs
This PR adds `#[derive(Serialize, Deserialize)]` to the following structs:
- `Constraint`
- `Direction`
- `Spacing`
- `Layout`
- `AccentedPalette`
- `NonAccentedPalette`
- `Palette`
- `Padding`
- `Borders`
- `BorderType`
- `ListDirection`
- `ScrollbarOrientation`
- `ScrollDirection`
- `RenderDirection`
- `HighlightSpacing`
Fixes #1877
=> feat(serde): derive Serialize/Deserialize for additional structs/enums

.github/workflows/release-alpha.yml
I can't sleep because every Saturday alpha release fails on my ratatui fork. This should fix my insomnia.
=> chore(ci): stop publish-alpha from running on forks

ratatui-widgets/src/borders.rs
Currently using `border!` macro requires explicit import of `Borders` which is unnecessary.
Follow up - move `border!` to `ratatui-macros`: #1829
=> feat: make `border!` work without importing `Borders`

ratatui-widgets/src/barchart.rs, ratatui-widgets/src/barchart/bar.rs
The split_at method requires that the split point is at a valid utf8
character boundary.
Fixes: https://github.com/ratatui/ratatui/issues/1928
=> fix: fix handling of multi-byte chars in bar chart

ratatui-core/src/symbols/bar.rs, ratatui-core/src/symbols/block.rs, ratatui-core/src/symbols/border.rs, ratatui-core/src/symbols/line.rs, ratatui-core/src/symbols/scrollbar.rs, ratatui-widgets/src/barchart.rs, ratatui-widgets/src/block.rs, ratatui-widgets/src/borders.rs, ratatui-widgets/src/gauge.rs, ratatui-widgets/src/scrollbar.rs, ratatui-widgets/src/sparkline.rs
This makes it possible to create symbol sets at runtime with non-static
lifetimes.
Fixes: https://github.com/ratatui/ratatui/issues/1722
=> feat: add lifetime to symbol sets

ratatui-core/src/widgets/stateful_widget.rs, ratatui-core/src/widgets/widget.rs, ratatui/src/lib.rs, ratatui/src/widgets.rs, ratatui/src/widgets/stateful_widget_ref.rs, ratatui/src/widgets/widget_ref.rs
Adds a good overview of the use and implementation of widget traits.
Goals with the doc rewrite:
- document the rationale for the ratatui-widgets crate with info for app builders and widget makers.
- Show how to use the widgets for rendering as well as implement the traits- document the differences and reasons for each trait
- document the historical perspective (to make it easy to understand older Ratatui apps as well as migrate to newer approaches
- give recommended approaches to implementing traits
- explain the differences between Consuming and Shared / Mutable Reference implementations of Widget
- explain the differences between using StatefulWidget and Mutable References
- Explain the use case for WidgetRef and StatefulWidgetRef
- Link out to third part widget lists
Fixes: …
=> docs: document widgets module

BREAKING-CHANGES.md
Related: https://github.com/fujiapple852/trippy/pull/1588
=> docs(breaking-changes): improve migration guide for `Backend::Error`

deny.toml
Only keep licenses in the allow list that are actually used
=> chore: remove OpenSSL license

ratatui-widgets/src/block.rs
Missed this in the review. 
Marking as chore, because it's not just changing docs, but I don't mind it being marked as docs or refactor either.
=> chore: remove `Title` references

ratatui-core/src/text/text.rs
It's possible to add two instances of `Text` together via the [`Add` trait](https://docs.rs/ratatui/0.29.0/ratatui/text/struct.Text.html#impl-Add-for-Text%3C'a%3E), but the `AddAssign` 
impl doesn't exist.
I added an `AddAssign` implmentation that does the same thing as `Add`.
=> feat(text): implement `AddAssign` for `Text`

.github/workflows/check-pr.yml, .github/workflows/check-semver.yml, .github/workflows/ci.yml, .github/workflows/release-alpha.yml, .github/workflows/release-plz.yml, .github/workflows/release-stable.yml, .github/workflows/zizmor.yml, bacon.toml
Fixes https://github.com/ratatui/ratatui/issues/1950
=> ci: audit github workflows with zizmor

.github/workflows/release-plz.yml
https://blog.rust-lang.org/2025/07/11/crates-io-development-update-2025-07/
https://crates.io/docs/trusted-publishing
I've setup the crate settings so that they will correctly issue OIDC tokens for this.
=> ci: use trusted publishing

Cargo.lock, xtask/Cargo.toml, xtask/src/main.rs
Removed to avoid needing to bump our msrv. See
https://github.com/rust-lang/cargo/issues/15746\#issuecomment-3071774343
for more details.
=> chore: remove clap-cargo from xtask

CONTRIBUTING.md
Removes a hanging opening code block:
````
```suggestion
````
=> chore: Fix typo in CONTRIBUTING.md

ratatui-widgets/src/barchart.rs, ratatui-widgets/src/block.rs, ratatui-widgets/src/calendar.rs, ratatui-widgets/src/canvas.rs, ratatui-widgets/src/chart.rs, ratatui-widgets/src/gauge.rs, ratatui-widgets/src/list.rs, ratatui-widgets/src/logo.rs, ratatui-widgets/src/mascot.rs, ratatui-widgets/src/paragraph.rs, ratatui-widgets/src/scrollbar.rs, ratatui-widgets/src/sparkline.rs, ratatui-widgets/src/table.rs, ratatui-widgets/src/tabs.rs
Fixes panic on overflow on horizontal `Barchart` and `RatatuiMascot`, adds proper tests to all widgets.
=> fix: panic when rendering widgets on too small buffer

ratatui-core/src/style/anstyle.rs
Underline color wasn't included in the style conversion logic.
=> fix: include underline color in anstyle conversion

ratatui-core/src/layout/rect.rs, ratatui-core/src/terminal/terminal.rs
`Rect::from(size)` returns a new Rect at the origin (0, 0) with the specified `Size`
=> feat: add conversion from Size to Rect

ratatui-core/src/text/line.rs, ratatui-core/src/text/span.rs, ratatui-core/src/text/text.rs
You can now calculate the width of any Text/Line/Span using the UnicodeWidthStr trait instead of the width method on the type. This also makes it possible to use the width_cjk() method if needed.
---
From https://github.com/joshka/tui-widgets/pull/94#discussion_r2241178372
=> feat: implement UnicodeWidthStr for Text/Line/Span

Cargo.lock, Cargo.toml, examples/apps/async-github/Cargo.toml, examples/apps/calendar-explorer/Cargo.toml, examples/apps/colors-rgb/Cargo.toml, examples/apps/demo/Cargo.toml, examples/apps/demo2/Cargo.toml, examples/apps/inline/Cargo.toml, examples/apps/mouse-drawing/Cargo.toml, examples/apps/table/Cargo.toml, examples/apps/tracing/Cargo.toml, examples/apps/weather/Cargo.toml, examples/concepts/state/Cargo.toml, ratatui/benches/main/buffer.rs, ratatui/benches/main/paragraph.rs, ratatui/benches/main/rect.rs, xtask/Cargo.toml
The goal of this is to reduce dependabot updates to generally only Cargo.lock updates
- Use "0.x" or "x" as the version generally.
- Specify versions only in the workspace manifest
- Bump versions to latest semver compatible (and update rstest / lru deps)
=> chore(deps): use less specific versions in manifests

cliff.toml
This is probably not optimal because we won't have access to the current `{package}` while running `git-cliff` but at least it will run _just_ fine.
While at it, I changed something in the commit parsers to avoid adding dependency updates to the changelog. So maybe rebase this PR instead of squashing.
=> chore(changelog): allow running git-cliff without release-plz

cliff.toml
https://github.com/ratatui/ratatui/pull/2025#issuecomment-3135177683
Left `v0.1.0-rc.1` there to not mess up old changelogs.
Can you update the changelog using that, @orhun?
=> chore: skip `alpha` and `beta` tags in `cliff.toml`

cliff.toml, ratatui/benches/main.rs, ratatui/benches/main/constraints.rs
I've added a new benchmark for constraints, which only takes into account the time it takes to generate a full layout using a single type of constraints only. Avoided rendering here as it resulted in more inaccurate benchmarks, and i believe it should be separated nonetheless.
=> test(bench): Added a benchmark for constraints

Cargo.lock
This PR updates the `slab` dependency from 0.4.10 to 0.4.11 to fix
[RUSTSEC-2025-0047](https://rustsec.org/advisories/RUSTSEC-2025-0047), a security
advisory about a bounds check bug in `get_disjoint_mut` that could lead to reading
uninitialized memory. Also updates `zerovec` to the latest non-yanked version to resolve cargo-deny warnings.
- Updated `slab` to 0.4.11
- Updated `zerovec` to latest available version
- Regenerated `Cargo.lock`
- https://rustsec.org/advisories/RUSTSEC-2025-0047
- https://github.com/ratatui/ratatui/actions/runs/16983398723/job/48147754711?pr=1963
=> fix(deps): update slab and zerovec

CONTRIBUTING.md
The `CONTRIBUTING.md` referenced `tests/widgets_block.rs`, but the correct path is `ratatui/tests/widgets_block.rs`. Updated the link so that readers can navigate to the test example without 404 error.
PS:
I also noticed that the Discord invite link in the docs seems to be expired. Could you please update it to the current valid one?
=> docs: fix link to `widgets_block_renders` test

.github/workflows/ci.yml
Summary
Fixes an issue where the "check" CI jobs for MSRV and stable were unintentionally using the stable toolchain from `rust-toolchain.toml` instead of the matrix-specified toolchain.
Details
- Added `RUSTUP_TOOLCHAIN: ${{ matrix.toolchain }}` to the "check" job in CI configuration.
Additional Context
- https://github.com/ratatui/ratatui/pull/2106
- https://discord.com/channels/1070692720437383208/1072879985762762812/1422345357131780177
- https://rust-lang.github.io/rustup/overrides.html#overrides
=> ci: set RUSTUP_TOOLCHAIN from matrix.toolchain

ratatui-core/src/layout/layout.rs, ratatui-core/src/terminal/terminal.rs
Updated the Terminal::get_frame section and added use cases, including an example from Dioxus showing how get_frame() can/should be used.
Also mentioned/pointed, that most people should be fine using Terminal::draw()
Closes : https://github.com/ratatui/ratatui/issues/1200
=> docs(Terminal::get_frame): Made usage of Terminal::get_frame() clearer
