CONTRIBUTING.md
Cargo.toml
README.md

This PR updates the readme and contributing guidelines to reflect the recent fork.

doc: Updated readme and contributing guide with updates about the fork

---

README.md

> Upstream: [#686](https://github.com/fdehau/tui-rs/pull/686)
Add EDMA to `tui-rs` application list

Add link to EDMA app in application list

---

README.md

> Upstream: [#675](https://github.com/fdehau/tui-rs/pull/675)
Also update xplr description.

docs: add tui-input and update xplr in README.md

---

.github/workflows/ci.yml

This PR adds macOS to CI as one of major platforms which should be supported by `tui` crate. The CI workflow was also parametrized to reduce duplicate steps for each OS.
I confirmed all jobs passed in my forked repository: https://github.com/rhysd/tui-rs-revival/actions/runs/4200844754

feat(ci): add MacOS to CI

---

README.md

Links to some 3rd party libraries including my tui-textarea crate were accidentally removed at #21. This PR fixes them.
Nothing to test since this is a small document change.

fix(doc): add 3rd party libraries accidentally removed at #21

---

README.md

Add poketex to 'apps using tui' in README.

docs(readme): add poketex to 'apps using tui' in README

---

README.md

Related: https://github.com/fdehau/tui-rs/pull/697

docs(readme): Add app kubectl-watch which uses tui

---

README.md

I have just updated the readme.md to include my application, [oxker](https://www.github.com/mrjackwills/oxker)

docs(readme): Add oxker to application list

---

.github/workflows/ci.yml

fix(ci): use env for the cargo-make version

---

.github/workflows/ci.yml

chore(ci): integrate `typos` for checking typos

---

README.md

https://github.com/orhun/systeroid

docs(readme): add systeroid to application list

---

README.md

This PR :
- **Updates tui mentions** -> ratatui
- **Add mention to original maintainer**

docs(readme): small edits before first release

---

src/style.rs

added a test to ensure it doesn't break in the future

fix(style): bold needs a bit

---

src/widgets/mod.rs
src/widgets/sparkline.rs

Finishes #1
- Renames LTR/RTL to LeftToRight and RightToLeft
- Adds tests
- rebases the changes on the ~260 odd changes since this PR was originally cut.
I'm unsure how exactly to update PR #1 (which is a copy of another user's fork that is a PR against tui-rs). I didn't find an obvious way to do this using git or github, so went with cutting a branch in my fork and doing a new PR from there. If I've missed something obvious, please let me know. I know that it's fairly easy to do when you own the repo and the original requester marks the PR as updatable by maintainers, but this has several edge cases on top.

feat(sparkline): finish #1 Sparkline directions PR

---

README.md

Adds acknowledgement to ratatui logo [creator](https://github.com/nawok).

docs(readme): add acknowledgement section

---

src/widgets/block.rs

Fixes https://github.com/tui-rs-revival/ratatui/issues/126

docs(block): add example for block.inner

---

src/widgets/paragraph.rs

Putting this in place to help ensure #149 doesn't break anything.
I wasn't 100% certain how the `zero_width_char_at_end_of_line` test was supposed to actually fail / not-fail as there's no assertion. Rewrote it to conform to the pattern of the other tests (but perhaps @orhun and @rhysd can add a bit more context if this is incorrect?

test(widget): add unit tests for Paragraph

---

Cargo.toml
src/style.rs

feat(color): add `FromStr` implementation for `Color`

---

src/backend/termwiz.rs
src/backend/test.rs
src/buffer.rs
src/layout.rs
src/text.rs
src/widgets/barchart.rs
src/widgets/block.rs
src/widgets/calendar.rs
src/widgets/canvas/line.rs
src/widgets/canvas/mod.rs
src/widgets/chart.rs
src/widgets/list.rs
src/widgets/paragraph.rs
src/widgets/reflow.rs
src/widgets/sparkline.rs
src/widgets/table.rs
src/widgets/tabs.rs
tests/widgets_canvas.rs

* `Default::default` is hard to read
* a few `map` -> `map_or`
* simplified `match` -> `let-if`

Minor lints, making Clippy happier

---

CODEOWNERS

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

docs: add CODEOWNERS file

---

Cargo.toml
src/backend/mod.rs
src/buffer.rs
src/layout.rs
src/terminal.rs
src/widgets/reflow.rs

A few more minor cleanups, mostly in documentation

chore: lint and doc cleanup

---

.cz.toml
CONTRIBUTING.md

add customized commitizen config to match repo needs
implement request mentioned in [#214](https://github.com/tui-rs-revival/ratatui/issues/214) by @joshka

chore(commitizen): add commitizen config

---

.cz.toml
.markdownlint.yaml
Makefile.toml
cliff.toml
committed.toml
rustfmt.toml
typos.toml

Also added links to the first comment line for easy access.

style(config): apply formatting to config files

---

.github/workflows/ci.yml

See <https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue>

chore(ci): enable merge queue for builds

---

.github/workflows/ci.yml

See <https://github.com/sagiegurari/cargo-make/releases>

chore(ci): bump cargo-make version

---

.github/CODEOWNERS

Auto review-requests were not working so let's try this way.

chore(github): simplify the CODEOWNERS file

---

.cargo-husky/hooks/pre-push
.github/workflows/ci.yml
CONTRIBUTING.md
Cargo.toml

Add cargo-husky to dev-deps, create hook, update `CONTRIBUTING.md`
#214

ci(pre-push hook): automate loading pre-push hook with cargo-husky

---

src/widgets/canvas/line.rs
src/widgets/canvas/mod.rs

There are a couple of small formatting changes in the current nightly

style(fmt): fix formatting

---

README.md

style(readme): update the style of badges in README.md

---

.editorconfig

chore(github): add EditorConfig config

---

Cargo.toml
src/widgets/barchart.rs

Adds unit tests in advance of https://github.com/tui-rs-revival/ratatui/issues/294
These tests should help ensure that existing code that uses `Barchart` will continue to work with the grouped version.
Pinging @karthago1 for review
Has full line coverage on the `Barchart` type.

test(barchart): add unit tests

---

src/style.rs

Fixes https://github.com/tui-rs-revival/ratatui/issues/305

docs(color): parse more color formats and add docs

---

examples/user_input.rs

Added cursor navigation to the user input example. User can now move cursor left and right. In addition user can also insert/delete characters at the cursor position. 
Could also put this demonstration into a new  example file if you prefer it this way.

feat(examples): cursor can be moved left/right and character at cursor position can be deleted/inserted

---

src/backend/crossterm.rs
src/buffer.rs
src/style.rs
src/text.rs
src/widgets/gauge.rs

Add underline color style for crossterm backend

---

README.md

Looks like `0.22.0` is out, update these two little items.

fix(readme): Update version in README.md

---

README.md

fix(readme): vim artifact?

---

examples/user_input.rs

fix(example): Fix typo

---

README.md

fix(readme): fix incorrect template link

---

.github/CODEOWNERS

chore(github): add kdheepak as a maintainer

---

README.md

Add scrollbar, clear. Fix Block link. Sort

docs(readme): fix widget docs links

---

README.md

Update README.md: fix broken link

---

examples/README.md
examples/block.rs
examples/block.tape

docs(examples): Update block example

---

src/widgets/block.rs

This PR fixes #349 the easy way (see issue). I think the _complex fix_ requires another separate PR.
I added a unit test and made sure it didn't pass prior to this modification. I added a lot of test cases because there are three separate places where this bug can occur.
I didn't change the corresponding example to demonstrate the behavior as there is already an [opened PR](https://github.com/ratatui-org/ratatui/pull/351) that will likely be merged.
I didn't want to create a new spans (or lines) because in the future they might contain more than just `content` and `style` and this would lead to some half cloned spans. Thus I preferred cloning and modifying them locally.

fix(block): Fixed title_style not rendered

---

examples/README.md

Updates the example for the fixes from #363

docs(examples): regen block.gif in readme

---

codecov.yml

Closes:  #372
Alternative: Use `cargo make` also in `bacon`, that way updates need to be only made in the `Makefile.toml`

ci(coverage): exclude examples directory from coverage

---

Cargo.toml
src/backend/crossterm.rs
src/lib.rs

[Changelog](https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md#version-027)
Upgrade `crossterm` to `v0.27`.
I don't think this is a breaking change, since the `crossterm` internals aren't exposed, is that correct?

build(deps): upgrade crossterm to 0.27

---

RELEASE.md

chore(docs): add doc comment bump to release documentation

---

benches/block.rs
benches/paragraph.rs

Replaced `Bencher::iter` by `Bencher::iter_batched` to clone the widget in the setup function instead of in the benchmark timing.
See [this PR](https://github.com/ratatui-org/ratatui/pull/377#discussion_r1285799256) for more information about `iter_batched` and its use.
See #262 for the original `paragraph` implementation.
See #368  for the original `block` implementation.
---
`Block` didn't really move, times were so low in the first place.
`Paragraph` saw increases of ~20% for 2048 lines and ~65% for 65000 lines. (`new` is still very high but its only copying memory, not much we can do ..., maybe we should remove it too?)
**Block**
**Paragraph**
---
PS : Not sure about the conventional commit type, feel free to edit

perf(bench): Used `iter_batched` to clone widgets in setup function

---

src/layout.rs

This PR changes all values for the `layout`'s `split`'s `vars` value to be known and labeled, this changes the code to be more readable and defines the values in a common place, also removing a extra match arm

refactor(layout): change "split"'s vars to be of known labeled values

---

src/layout.rs

docs(layout): add doc comments

---

src/layout.rs

The recent refactor (#405) missed the positive width constraint:
https://github.com/ratatui-org/ratatui/blob/ea48af1c9abac7012e3bf79e78c6179f889a6321/src/layout.rs#L380-L381
Addresses the bug noticed in https://github.com/ratatui-org/ratatui/pull/404#issuecomment-1681891809
ping @hasezoey - I took a quick look and this may change a few tests on #404. It might not yet be perfect and it may change again if https://github.com/ratatui-org/ratatui/pull/408 is merged on top of this.

fix(layout): ensure left <= right

---

src/layout.rs

Further simplification of `try_split` by removing the `area` element and constraints for that, and using the `start` and `end` values directly.

Simplify split function

---

src/backend/test.rs
src/buffer.rs
src/layout.rs

This makes it possible to deserialize/serialize the whole test buffer with the `serde` feature.

feat: expand serde attributes for `TestBuffer`

---

README.md

Incomplete merge request that asks for how to connect through Matrix.

Matrix URL

---

src/widgets/paragraph.rs

docs(paragraph): add more docs

---

src/text/span.rs

docs(span): finish docs and tests for Span

---

src/buffer.rs

feat(cell): add voluntary skipping capability for sixel
> Sixel is a bitmap graphics format supported by terminals.
> "Sixel mode" is entered by sending the sequence ESC+Pq.
> The "String Terminator" sequence ESC+\ exits the mode.
The graphics are then rendered with the top left positioned at the
cursor position.
It is actually possible to render sixels in ratatui with just
`buf.get_mut(x, y).set_symbol("^[Pq ... ^[\")`. But any buffer covering
the "image area" will overwrite the graphics. This is most likely the same
buffer, even though it consists of empty characters `' '`, except for
the top-left character that starts the sequence.
Thus, either the buffer or cells must be specialized to avoid drawing
over the graphics. This patch specializes the `Cell` with a
`set_skip(bool)` method, …

feat(cell): add voluntary skipping capability for sixel

---

src/widgets/canvas/rectangle.rs

test(canvas): add tests for rectangle

---

src/text/grapheme.rs

test(styled_grapheme): test StyledGrapheme methods

---

src/text/text.rs

 test(text): add unit tests

---

src/widgets/canvas/line.rs

Also add constructor to simplify creating lines

test(canvas): add unit tests for line

---

src/backend/test.rs

test(test_backend): add tests for TestBackend coverage

---

src/widgets/block.rs

test(block): test all block methods

---

src/widgets/clear.rs

test(clear): test Clear rendering

---

src/widgets/tabs.rs

test(tabs): add unit tests

---

Cargo.toml
README.md
src/lib.rs

docs(project): make the project description cooler

---

src/widgets/barchart/mod.rs

Calculating `label_offset` is unnecessary, if we just render the group label after rendering the bars. We can just reuse `bar_y`.
this commit is getting rid of `let label_offset = bars.len() as u16 * (self.bar_width + self.bar_gap) - self.bar_gap;`

refactor(barchart): reduce some calculations

---

CHANGELOG.md
Cargo.toml
README.md
cliff.toml
src/lib.rs

chore(release): prepare for 0.23.0

---

.github/workflows/check-pr-title.yml

- Use [`action-semantic-pull-request`](https://github.com/amannn/action-semantic-pull-request)
- Allow only reading the PR contents
- Enable merge group

chore(ci): improve checking the PR title

---

src/symbols.rs
src/widgets/canvas/mod.rs

Addresses https://github.com/ratatui-org/ratatui/issues/457

docs(canvas): add support note for Braille marker

---

Cargo.toml
examples/README.md
examples/colors_rgb.rs
examples/colors_rgb.tape

Helpful for diagnosing what's happening with https://github.com/ratatui-org/ratatui/issues/475

docs(examples): add colors_rgb example

---

.github/workflows/check-pr-title.yml

Fixes #481 
I tested that it works on a personal repo on mine.

chore: Fix check for if breaking change label should be added 

---

src/widgets.rs

docs(widgets): update the list of available widgets

---

src/text/line.rs

feat(line): add `Line::raw` constructor

---

src/terminal.rs

This PR makes a minor comment fix

docs: Fix terminal comment

---

.github/ISSUE_TEMPLATE/config.yml

Contact links will show up like this: https://github.com/orhun/git-cliff/issues/new/choose

chore(github): add contact links for issues

---

examples/barchart.tape
examples/block.tape
examples/calendar.tape
examples/canvas.tape
examples/chart.tape
examples/colors.tape
examples/colors_rgb.tape
examples/custom_widget.tape
examples/demo.tape
examples/demo2-social.tape
examples/demo2.tape
examples/docsrs.tape
examples/gauge.tape
examples/generate.bash
examples/hello_world.tape
examples/inline.tape
examples/layout.tape
examples/list.tape
examples/modifiers.tape
examples/panic.tape
examples/paragraph.tape
examples/popup.tape
examples/scrollbar.tape
examples/sparkline.tape
examples/table.tape
examples/tabs.tape
examples/user_input.tape

This is a nicer theme that makes the colors pop
See https://github.com/ratatui-org/ratatui/pull/573/files#diff-7b25a7e35f79011df03120f2aaf4801329772a7032050365e89e73b0b5a841ea for the PR that updates the images

docs(examples): udpate theme to Aardvark Blue

---

examples/README.md
examples/colors_rgb.tape
examples/generate.bash

remove VHS bug info, tweak colors_rgb image, update some of the instructions. add demo2

docs(examples): update examples readme

---

.github/dependabot.yml

This is the default dependabot yaml file that is generated by github

chore(github): create dependabot.yml

---

README.md
src/lib.rs

docs(readme): fix link to demo2 image

---

cliff.toml

chore(changelog): skip dependency updates in changelog

---

BREAKING-CHANGES.md
CHANGELOG.md
Cargo.toml
RELEASE.md
typos.toml

chore(release): prepare for 0.24.0

---

examples/README.md

See issues https://github.com/ratatui-org/ratatui/issues/594

docs(examples): fix run `demo2` command error

---

codecov.yml

Fixes https://github.com/ratatui-org/ratatui/issues/612

ci(codecov): adjust threshold and noise settings

---

src/style.rs
src/style/stylize.rs

fix: add #[must_use] attributes on (self: Style) methods

---

src/widgets/paragraph.rs

This PR refactors implementation of `Paragraph::render`. It allocates `LineComposer` trait object on heap memory and calls its methods via dynamic dispatch. However it can be easily changed to static dispatch with allocating the object on stack.
This PR does the change as refactoring. No rendering logic has changed.

refactor(widgets): remove unnecessary dynamic dispatch and heap allocation

---

src/widgets/list.rs

feat(list): support line alignment

---

src/lib.rs

docs(lib): tweak the crate documentation

---

src/widgets/tabs.rs

style(tabs): fix doc formatting

---

.github/CODEOWNERS

onboard @Valentin271 as maintainer

docs(github): update code owners

---

src/text/span.rs

feat(span): add setters for content and style

---

.github/workflows/check-pr.yml

ci: fix untrusted input in pr check workflow

---

src/layout.rs

Structs and enums at the top of the file helps show the interaction
between the types without having to find each type in between longer
impl sections.
Also moved the try_split function into the Layout impl as an associated
function and inlined the `layout::split()` which just called try_split.
This makes the code a bit more contained.
---
This is a redo of the refactor step from https://github.com/ratatui-org/ratatui/pull/641 to avoid losing code in a bad rebase.
For ease of checking that all the methods and structs are reorganized:
```shell
grep -E '^\s*(fn|pub|enum|struct|impl)' src/layout.rs | sed 's/^ *//' | sort > layout-refactor-sorted.txt
diff -u layout-main-sorted.txt layout-refactor-sorted.txt
```
```diff
--- layout-main-sorted.txt   2023-12-09 13:18:02
+++ …
```

refactor(layout): to natural reading order

---

src/backend/crossterm.rs

This PR includes the following `From` implementations:
- from `Attribute` to `Modifier`
- from `Attributes` to `Modifier`
- from crossterm `Color` to `Color`
- from `ContentStyle` to `Style`
This PR relates to #679. I've decided to split the work across multiple PRs to facilitate the reviewing process.

feat(style): implement `From` trait for crossterm to `Style` related structs

---

README.md

The apps wiki moved to awesome-ratatui

refactor(readme): reference awesome-ratatui instead of wiki

---

src/terminal.rs

docs(frame): add docs about resize events

---

BREAKING-CHANGES.md

docs(breaking): fix typo

---

src/style/color.rs

The deserialize implementation for Color used to support only the enum
names (e.g. Color, LightRed, etc.) With this change, you can use any of
the strings supported by the FromStr implementation (e.g. black,
light-red, #00ff00, etc.)
closes #704

feat(color): use the FromStr implementation for deserialization

---

src/widgets/table.rs

docs(table): fix typo

---

src/text/span.rs

This allows us to use Span as a child of other widgets, and to use
Span::render() to render it rather than calling buffer.set_span().
```rust
frame.render_widget(Span::raw("Hello, world!"), area);
// or
Span::raw("Hello, world!").render(frame, area);
// or even
"Hello, world!".green().render(frame, area);
```

feat(span): implement Widget on Span

---

src/widgets/table.rs

Previously, if `.widths` was not called before rendering a `Table`, no
content would render in the area of the table. This commit changes that
behaviour to default to equal widths for each column.
Fixes #510.
(Resubmission of https://github.com/ratatui-org/ratatui/pull/519 by @joshcbrown due to git footgun)

fix(table): render missing widths as equal

---

src/buffer.rs

This commit fixes a panic in set_style when the area to be styled is
outside the buffer's bounds.

fix(buffer): don't panic in set_style

---

src/backend/termwiz.rs

Closes #679
Important note: this also fixes a wrong mapping between ratatui's gray and termwiz's grey. `ratatui::Color::Gray` now maps to `termwiz::color::AnsiColor::Silver`

feat(termwiz): add `From` termwiz style impls

---

src/layout.rs

- feat(layout): add vertical and horizontal constructors
- docs(layout): document constructors and setters

feat(layout): add horizontal and vertical constructors

---

src/backend.rs

docs(backend): fix broken book link

---

src/layout.rs
src/layout/alignment.rs
src/layout/corner.rs
src/layout/direction.rs
src/layout/size.rs

- alignment -> layout/alignment.rs
- corner -> layout/corner.rs
- direction -> layout/direction.rs
- size -> layout/size.rs

refactor(layout): move the remaining types

---

src/layout/rect.rs

This method splits a Rect and returns a fixed-size array of the
resulting Rects. This allows the caller to use array destructuring
to get the individual Rects.
```rust
use Constraint::*;
let layout = &Layout::vertical([Length(1), Min(0)]);
let [top, main] = area.split(&layout);
```

feat(layout): add Rect::split method

---

src/layout/layout.rs
src/layout/rect.rs

docs(layout): document the difference in the split methods

---

CONTRIBUTING.md

I'd like for multiple maintainers to review this so we all agree.
Original discussion: [from this comment and below](https://github.com/ratatui-org/ratatui/pull/759#issuecomment-1879870412)
Note: I didn't mention any time-span because we might want to space out releases in the future.

chore(contributing): add deprecation notice guideline

---

src/terminal/frame.rs
src/terminal/terminal.rs
tests/terminal.rs

feat: Add frame count ✨

---

src/layout/rect.rs

Signed-off-by: Prisacaru Bogdan-Paul <paulbp68@gmail.com>
#752
This PR will allow users to use iterators for Rows and Columns in Rects in order to manage rows and columns. During iteration, each structure produces `Rect` instances representing each row and column within the given Rect.

feat(rect.rs): implement Rows and Columns iterators in Rect

---

src/widgets/table/table.rs

fix: broken tests in table.rs

---

src/layout/rect.rs
src/layout/size.rs

- add Size::new() constructor
- add Rect::as_size()
- impl From<Rect> for Size
- document and add tests for Size

feat(layout): add Rect -> Size conversion methods

---

src/layout/layout.rs

This PR specifies the current behavior of the layout solver with more tests.

feat: Add tests for `Constraint::Length` interacting with other constraints ✨

---

src/lib.rs

fix: update templates links

---

README.md
src/lib.rs

This PR updates links to the `templates` repository.

docs: Update links to templates repository 📚

---

src/widgets/chart.rs

refactor(chart): replace deprecated apply

---

examples/scrollbar.rs
src/widgets/scrollbar.rs

docs(scrollbar): complete scrollbar documentation

---

examples/flex.rs

This adds the `spacing` using `+` and `-` to the flex example:
https://github.com/ratatui-org/ratatui/assets/1813121/1980206d-8558-47f0-8631-c74ba98b224d
This was useful to find and debug spacing related bugs like this: https://github.com/ratatui-org/ratatui/pull/829

feat: Add spacing feature to flex example ✨

---

.github/workflows/ci.yml

chore(ci): update the job description for installing cargo-nextest

---

src/layout.rs
src/layout/position.rs
src/layout/rect.rs

This stores the x and y coordinates (columns and rows)
- add conversions from Rect
- add conversion with Size to Rect
- add Rect::as_position

feat(layout): add Position struct

---

examples/barchart.rs
examples/layout.rs
examples/list.rs
src/text/line.rs

Added convenience functions left_aligned(), centered() and right_aligned() plus unit tests. Updated example code.

feat(Line): add alignment convenience functions

---

src/text/text.rs

Added convenience functions left_aligned(), centered() and right_aligned() plus unit tests. No example code updated since none seems to be using Text::alignment().

feat(Text): add alignment convenience functions

---

examples/colors_rgb.rs
examples/constraints.rs
examples/demo2/root.rs
examples/flex.rs
examples/list.rs
examples/panic.rs
examples/paragraph.rs
examples/popup.rs
examples/table.rs
src/widgets/paragraph.rs

Added convenience functions left_aligned(), centered() and right_aligned() plus unit tests. Updated example code.

feat(Paragraph): add alignment convenience functions

---

examples/colors_rgb.rs

This commit refactors the colors_rgb example to implement the Widget
trait on mutable references to the app and its sub-widgets. This allows
the app to update its state while it is being rendered.
Additionally the main and run functions are refactored to be similar to
the other recent examples. This uses a pattern where the App struct has
a `run` method that takes a terminal as an argument, and the main
function is in control of initizing and restoring the terminal and
installing the error hooks.

refactor(colors_rgb): impl widget on mutable refs

---

examples/tabs.rs
examples/vhs/tabs.tape

Issue: https://github.com/ratatui-org/ratatui/issues/819
This PR adds:
impl `Widget` for `App`, `SelectedTab` in tabs example.

docs(examples): impl Widget for App, SelectedTab

---

src/text/span.rs

Implemented functions that convert Span into a left-/center-/right-aligned Line. Implemented unit tests.
Closes #853

feat(Span): add alignment functions

---

src/layout/layout.rs

This PR makes all the letters test use `rstest`

test(layout): Convert layout tests to use rstest 

---

src/layout/rect.rs

This is useful for performing hit tests (i.e. did the user click in an area).

feat(layout): add Rect::contains method

---

src/layout/layout.rs

This PR is a split of reworking the weights from #888 
This keeps the same ranking of weights, just uses a different numerical value so that the lowest weight is `WEAK` (`1.0`).
No tests are changed as a result of this change, and running the following multiple times did not cause any errors for me:
```rust
for i in {0..100}
do
cargo test --lib --
if [ $? -ne 0 ]; then
echo "Test failed. Exiting loop."
break
fi
done
```

feat: Better weights for constraints

---

src/layout/layout.rs

refactor: make layout tests a bit easier to understand

---

examples/constraint-explorer.rs

chore: small fixes to constraint-explorer

---

src/buffer/buffer.rs
src/text/line.rs
src/widgets/barchart.rs
src/widgets/barchart/bar.rs
src/widgets/barchart/bar_group.rs
src/widgets/reflow.rs

BarChart had some internal mutations that needed to be removed to
implement the Widget trait for &BarChart to bring it in line with the
other widgets.
-- include #896 - merge that PR first and update this PR before merging

feat: impl Widget for &BarChart

---

BREAKING-CHANGES.md

Follow up to: https://github.com/ratatui-org/ratatui/pull/881

docs: Update BREAKING-CHANGES.md with flex section

---

BREAKING-CHANGES.md
CHANGELOG.md
Cargo.toml
cliff.toml

chore(release): prepare for 0.26.0

---

BREAKING-CHANGES.md

docs: Update BREAKING-CHANGES.md summary

---

CHANGELOG.md

docs(changelog): add sponsors section

---

src/widgets/scrollbar.rs

fix: Scrollbar rendering when no track symbols are provided

---

src/widgets/block.rs

refactor: rearrange block structure

---

CHANGELOG.md
Cargo.toml

chore(release): prepare for 0.26.1

---

.github/CODEOWNERS

chore(github): add EdJoPaTo as a maintainer

---

src/widgets/list.rs

An overflow (pedantically an underflow) can occur if the highlight_symbol is a multi-byte char, and area is reduced to a size less than that char length.
I am not sure of the best way to create a test for this, I only discovered it after resizing my ratatui window to as small as possible.
There *might* be a number of other potential overflows in ratatui, but I am not well versed enough in the source to know if they could ever actually occur. Basically anywhere that uses a `Rect` that calculates width by a subtraction, `x-y`, instead of using `x.saturating_sub(y)`

fix(List): saturating_sub to fix highlight_symbol overflow

---

FUNDING.json

Adding the Open Source Collective safe multi-sig to collect funds and interact with Drips.network

chore(funding): add eth address for receiving funds from drips.network

---

CHANGELOG.md
Cargo.toml
cliff.toml

chore(release): prepare for 0.26.2

---

CHANGELOG.md

chore(changelog): fix changelog release links

---

src/widgets/gauge.rs

refactor(gauge): fix internal typo

---

src/style.rs

Fixes: https://github.com/ratatui-org/ratatui/issues/1085

feat: re-export ParseColorError as style::ParseColorError

---

cliff.toml

chore(changelog): put commit id on the same line as the message

---

src/style.rs

test(style): use rstest

---

src/widgets/block.rs

Group the builder pattern methods together and put the other methods below them

refactor(block): group builder pattern methods

---

examples/paragraph.rs

Related: https://github.com/ratatui-org/ratatui/issues/1157

docs(examples): simplify paragraph example

---

BREAKING-CHANGES.md
CHANGELOG.md
Cargo.toml

🧀
Highlights: https://github.com/ratatui-org/ratatui-website/pull/644

chore(release): prepare for 0.27.0

---

examples/README.md

docs(examples): add missing examples to README

---

src/widgets/block.rs

Fixes: https://github.com/ratatui-org/ratatui/issues/1129

docs(block): add docs about style inheritance

---

src/text/line.rs

Seems like the fact that a Cow is passed in was forgotten.

fix: useless allocations creating Line

---

src/text/span.rs

Fun fact: Another thing that wouldn't have happened with #1047

fix(span): prevent panic on rendering out of y bounds

---

src/buffer/buffer.rs

They are not rendered as expected but not completely wrong either so that's a win?

test(buffer): ensure emojis are rendered

---

src/layout/position.rs
src/layout/size.rs

~~Counterpart of `Rect::as_size`.~~

feat(layout): add Size::ZERO and Position::ORIGIN constants

---

deny.toml

Update `cargo-deny` config (noticed in https://github.com/ratatui-org/ratatui/pull/1263#pullrequestreview-2215488414)
See https://github.com/EmbarkStudios/cargo-deny/pull/611

chore: update cargo-deny config

---

examples/demo2/big_text.rs
src/prelude.rs
src/terminal/terminal.rs

Looks like the failing tests on #1260 where not noticed?

docs(terminal): fix imports

---

src/widgets/list/state.rs
src/widgets/table/table_state.rs

Implement new methods `scroll_down_by(u16)` and `scroll_up_by(u16)` for both `Liststate` and `Tablestate`
Closes: #1207

feat: add ListState / TableState scroll_down_by() / scroll_up_by() methods

---

README.md
src/lib.rs

Follow up to https://github.com/ratatui-org/ratatui/pull/1203

docs: update demo image

---

CODE_OF_CONDUCT.md

docs(github): Create CODE_OF_CONDUCT.md

---

CONTRIBUTING.md

docs(contributing): fix minor issues

---

Cargo.toml

https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md\#version-0281

chore(deps): bump crossterm to 0.28.1

---

BREAKING-CHANGES.md
CHANGELOG.md
Cargo.toml

chore(release): prepare for 0.28.0

---

examples/demo/ui.rs

docs(examples): show line gauge in demo example

---

MAINTAINERS.md

chore(maintainers): remove EdJoPaTo

---

examples/block.rs
examples/colors.rs
examples/constraint-explorer.rs
examples/demo2/tabs/email.rs
examples/demo2/tabs/traceroute.rs
examples/layout.rs
examples/table.rs
src/layout/constraint.rs
src/layout/layout.rs
src/text/text.rs

See https://github.com/ratatui/ratatui/pull/1336

refactor: Avoid unneeded allocations

---

examples/demo/app.rs
src/terminal/terminal.rs
src/widgets/reflow.rs
src/widgets/sparkline.rs

fix: clippy lints from rust 1.81.0

---

README.md
src/layout/layout.rs
src/layout/rect.rs
src/lib.rs
src/terminal.rs
src/terminal/terminal.rs
src/text/span.rs
src/widgets.rs
src/widgets/block.rs
src/widgets/scrollbar.rs

`size` is deprecated, use `.area()` as it's the more correct name.

docs: frame.size() is deprecated

---

.github/workflows/ci.yml
Cargo.toml

`cargo-machete` lints for unused dependencies. See https://github.com/bnjbvr/cargo-machete

refactor: remove unused dependencies; leverage cargo-machete on CI

---

BREAKING-CHANGES.md
src/layout/rect/iter.rs

feat: add an impl of `DoubleEndedIterator` for `Columns` and `Rows` (#1357)

---

Cargo.toml
src/backend/test.rs
src/buffer/buffer.rs

It is probably a good idea to take a look at those tests and why the output has changed to get a better idea of how this will impact the users.
See #1271
Closes #1385

chore(deps)!: pin unicode-width to 0.2.0

---

examples/canvas.rs

fun fact: I had to do [35 pushups](https://www.youtube.com/watch?v=eS92stzBYXA) for this...

feat(example): add drawing feature to the canvas example

---

BREAKING-CHANGES.md
CHANGELOG.md
Cargo.lock
Cargo.toml
cliff.toml

chore(release): prepare for 0.29.0

---

README.md

Fix broken Link in README.md

---

Cargo.lock
ratatui-widgets/Cargo.toml
ratatui-widgets/src/canvas.rs
ratatui-widgets/src/canvas/line.rs

Support draw Canvas Line if points off-grid and support Canvas bound access in Painter
Fixes: https://github.com/ratatui/ratatui/issues/1489

feat: add bounds accsess in Painter and off-grid Line points support

---

ratatui-widgets/src/barchart/bar.rs

implements `styled` for `Bar`: https://github.com/ratatui/ratatui/issues/683

feat(bar): impl Styled for Bar

---

ratatui-core/src/style/stylize.rs
ratatui-core/src/text/grapheme.rs
ratatui-core/src/text/line.rs
ratatui-core/src/text/span.rs
ratatui-core/src/text/text.rs
ratatui-widgets/src/barchart.rs
ratatui-widgets/src/barchart/bar.rs
ratatui-widgets/src/block.rs
ratatui-widgets/src/canvas.rs
ratatui-widgets/src/canvas/points.rs
ratatui-widgets/src/chart.rs
ratatui-widgets/src/gauge.rs
ratatui-widgets/src/list.rs
ratatui-widgets/src/paragraph.rs
ratatui-widgets/src/scrollbar.rs
ratatui-widgets/src/sparkline.rs
ratatui-widgets/src/table.rs
ratatui-widgets/src/table/cell.rs
ratatui-widgets/src/table/row.rs
ratatui-widgets/src/tabs.rs
ratatui/examples/custom_widget.rs
ratatui/examples/demo2/tabs/recipe.rs

https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes

fix: rust 1.83 clippy lints

---

Cargo.toml
ratatui-core/Cargo.toml
ratatui-core/src/text/text.rs
ratatui-crossterm/Cargo.toml
ratatui-termion/Cargo.toml
ratatui-termwiz/Cargo.toml
ratatui-widgets/Cargo.toml
ratatui/Cargo.toml

- Move lints to workspace manifest
- Add lint config to backend crates
- Fix one small lint error

chore: ensure lint config is correct

---

ratatui-widgets/examples/calendar.rs

docs(widgets): add example for calendar

---

ratatui-widgets/examples/chart.rs

<details>
<summary>inspired by:</summary>
</details>

docs(widgets): add example for chart

---

ratatui-core/src/text/line.rs
ratatui-widgets/src/list/rendering.rs

move the `if` outside the loop
should be a no-op

refactor: rearrange selection_spacing code

---

ratatui-widgets/Cargo.toml
ratatui-widgets/examples/gauge.rs

docs(widgets): add example for gauge

---

ratatui-widgets/examples/logo.rs
ratatui-widgets/src/logo.rs
ratatui/Cargo.toml

related #1512 
Also updates the code to make it consistent with the other examples

docs(widgets): move the logo example to widgets

---

ratatui-widgets/examples/table.rs

docs(widgets): add example for table

---

ratatui-widgets/examples/list.rs

docs(widgets): add example for list

---

ratatui-widgets/examples/scrollbar.rs

docs(widgets): add example for scrollbar

---

Cargo.lock
examples/apps/canvas/Cargo.toml
examples/apps/canvas/README.md
examples/apps/canvas/src/main.rs
ratatui/Cargo.toml

related #1512 
This moves the canvas example to the apps and adds some interactivity via changing the marker by pressing enter.

chore(examples): add canvas demo app

---

Cargo.lock
examples/apps/chart/Cargo.toml
examples/apps/chart/README.md
examples/apps/chart/src/main.rs
ratatui/Cargo.toml

related #1512 
Moves the chart example to apps

chore(examples): add chart demo app

---

Cargo.lock
examples/apps/color-explorer/Cargo.toml
examples/apps/color-explorer/README.md
examples/apps/color-explorer/src/main.rs
ratatui/Cargo.toml

related #1512 
Moves the colors examples to apps

chore(examples): add colors explorer demo app

---

ratatui/Cargo.toml
ratatui/examples/widget-ref-container.rs

Implements ideas alluded to by
<https://discord.com/channels/1070692720437383208/1072907135664529508/1323061053990637640>
and followup conversations.

docs: add widget-ref-container example

---

LICENSE

Update MIT Licence to copyright year 2025

docs(license): update copyright years 

---

Cargo.lock
examples/README.md
examples/apps/hello-world/Cargo.toml
examples/apps/hello-world/README.md
examples/apps/hello-world/src/main.rs
ratatui/Cargo.toml

docs(examples): move hello-world example to examples folder

---

Cargo.lock
examples/README.md
examples/apps/constraint-explorer/Cargo.toml
examples/apps/constraint-explorer/README.md
examples/apps/constraint-explorer/src/main.rs
ratatui/Cargo.toml

docs(examples): move constraint-explorer example to examples folder

---

Cargo.lock
examples/README.md
examples/apps/constraints/Cargo.toml
examples/apps/constraints/README.md
examples/apps/constraints/src/main.rs
ratatui/Cargo.toml

docs(examples): move constraints example to examples folder

---

Cargo.lock
examples/README.md
examples/apps/flex/Cargo.toml
examples/apps/flex/README.md
examples/apps/flex/src/main.rs
ratatui/Cargo.toml

docs(examples): move flex example to examples folder

---

Cargo.lock
examples/README.md
examples/apps/custom-widget/Cargo.toml
examples/apps/custom-widget/README.md
examples/apps/custom-widget/src/main.rs
ratatui/Cargo.toml

docs(examples): move custom-widget example to examples folder

---

Cargo.lock
examples/README.md
examples/apps/gauge/Cargo.toml
examples/apps/gauge/README.md
examples/apps/gauge/src/main.rs

docs(examples): move gauge example to examples folder

---

Cargo.lock
examples/README.md
examples/apps/inline/Cargo.toml
examples/apps/inline/README.md
examples/apps/inline/src/main.rs
ratatui/Cargo.toml

docs(examples): move inline example to examples folder

---

Cargo.lock
examples/README.md
examples/apps/scrollbar/Cargo.toml
examples/apps/scrollbar/README.md
examples/apps/scrollbar/src/main.rs
ratatui/Cargo.toml

docs(examples): move scrollbar example to examples folder

---

Cargo.lock
examples/apps/async-github/Cargo.toml
examples/apps/colors-rgb/Cargo.toml

`release-plz` trying to publish async-github example in #1671

chore(examples): do not publish the async-github example

---

examples/vhs/chart.tape

fix(examples): run the correct example for chart

---

cliff.toml

see https://github.com/ratatui/ratatui/pull/1671#issuecomment-2692469384

chore(changelog): bring back commit details

---

cliff.toml

chore(changelog): skip placeholder commits in changelog

---

.github/workflows/release-plz.yml

See https://github.com/jdssl/ratatui/pull/1#issuecomment-2739366609

chore(ci): disable running release-plz on forked repositories

---

Cargo.lock
ratatui-core/Cargo.toml
ratatui-core/src/backend.rs
ratatui-core/src/backend/test.rs
ratatui-core/src/buffer/buffer.rs
ratatui-core/src/layout/constraint.rs
ratatui-core/src/layout/layout.rs
ratatui-core/src/layout/margin.rs
ratatui-core/src/layout/position.rs
ratatui-core/src/layout/rect.rs
ratatui-core/src/layout/size.rs
ratatui-core/src/lib.rs
ratatui-core/src/style.rs
ratatui-core/src/style/color.rs
ratatui-core/src/style/stylize.rs
ratatui-core/src/terminal/viewport.rs
ratatui-core/src/text/line.rs
ratatui-core/src/text/masked.rs
ratatui-core/src/text/span.rs
ratatui-core/src/text/text.rs
ratatui-core/src/widgets/stateful_widget.rs

Resolves https://github.com/ratatui/ratatui/issues/1751

feat(no_std): remove redundant `std` usages in `ratatui-core`

---

Cargo.lock
ratatui-core/Cargo.toml
ratatui-core/src/layout/layout.rs

https://github.com/ratatui/kasuari

build(deps): use kasuari instead of cassowary

---

ratatui-core/Cargo.toml
ratatui-core/src/lib.rs

chore(lint): add `std` instead of `core`/`alloc` lints to `ratatui-core`

---

ratatui-core/src/buffer/buffer.rs
ratatui-widgets/src/scrollbar.rs

Applied via clippy --fix.
Available since 1.82.0.

chore: make use of iter::repeat_n()

---

ratatui-widgets/src/barchart.rs
ratatui-widgets/src/barchart/bar.rs
ratatui-widgets/src/barchart/bar_group.rs
ratatui-widgets/src/block.rs
ratatui-widgets/src/block/title.rs
ratatui-widgets/src/borders.rs
ratatui-widgets/src/calendar.rs
ratatui-widgets/src/canvas.rs
ratatui-widgets/src/canvas/map.rs
ratatui-widgets/src/chart.rs
ratatui-widgets/src/gauge.rs
ratatui-widgets/src/lib.rs
ratatui-widgets/src/list.rs
ratatui-widgets/src/list/item.rs
ratatui-widgets/src/list/rendering.rs
ratatui-widgets/src/mascot.rs
ratatui-widgets/src/paragraph.rs
ratatui-widgets/src/reflow.rs
ratatui-widgets/src/scrollbar.rs
ratatui-widgets/src/sparkline.rs
ratatui-widgets/src/table.rs
ratatui-widgets/src/table/highlight_spacing.rs
ratatui-widgets/src/table/row.rs
ratatui-widgets/src/tabs.rs

feat(no_std): make `ratatui-widgets` `no_std`

---

ratatui-core/src/style.rs

test: ensure Style::new() and Style::default() are equivalent

---

ratatui-core/src/layout/rect.rs

feat(rect): centering

---

ratatui-widgets/src/tabs.rs

Fixes https://github.com/ratatui/ratatui/issues/1836

fix: `padding_right()` should set right padding instead of left

---

Cargo.lock
ratatui-core/Cargo.toml
ratatui-widgets/Cargo.toml

build(deps): bump `kasuari` and `line-clipping`

---

.github/workflows/ci.yml
Cargo.toml
examples/apps/canvas/src/main.rs
examples/apps/chart/src/main.rs
examples/apps/scrollbar/src/main.rs

This is a small step toward fixing #1727

chore: Update to Rust version 1.85.0

---

examples/apps/input-form/README.md

Makes CI typos check pass again

docs(examples): fix a typo

---

examples/apps/gauge/src/main.rs
examples/apps/weather/src/main.rs
ratatui-core/src/buffer/buffer.rs
ratatui-core/src/terminal/terminal.rs
ratatui-core/src/text/line.rs
ratatui-core/src/text/text.rs
ratatui-widgets/src/block.rs
ratatui-widgets/src/calendar.rs

https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/lifetime_syntax/static.MISMATCHED_LIFETIME_SYNTAXES.html

chore: fix new lints

---

ratatui-core/src/layout/alignment.rs

feat(serde): derive Serialize/Deserialize for alignment enums

---

ratatui/src/widgets.rs

docs: add docs for authoring widget crates

---

ratatui-widgets/src/paragraph.rs

fix: Fix panic when rendering a `Paragraph` out of bounds

---

.github/workflows/release-plz.yml

https://github.com/rust-lang/crates.io/issues/11564#issuecomment-3066696820

ci: add environment to release workflow

---

ratatui-core/src/layout/layout.rs

docs(layout): Update documentation to point to `kasuari` solver

---

README.md

Related to:
- https://github.com/simple-icons/simple-icons/pull/13593
- https://github.com/ratatui/ratatui/pull/1967
The Ratatui icon is available on shields.io now :v:
And it's customizable. There are more configurations at https://shields.io/badges.
Here are some examples:
```markdown
```
I also created a PR to the ratatui-website project to update the badge. Here is the PR:
- https://github.com/ratatui/ratatui-website/pull/924

docs: use shields.io badge

---

ratatui-core/src/lib.rs
ratatui-crossterm/src/lib.rs
ratatui-termion/src/lib.rs
ratatui-termwiz/src/lib.rs
ratatui-widgets/src/lib.rs
ratatui/src/lib.rs

chore: remove obsolete doc_auto_cfg feature

---

.github/workflows/release-plz.yml

fix https://github.com/release-plz/release-plz/issues/2439
as described in https://release-plz.dev/docs/github/quickstart#3-setup-the-workflow

fix(ci): add contents write permission to release-plz PR

---

CHANGELOG.md
cliff.toml
ratatui-core/src/style/color.rs
ratatui-core/src/symbols/merge.rs

This fixes the pipeline after bumping typos.

chore: Fix typos
